### ISSUE TITLE
Audio glitches in callback stream

### ISSUE THREAD

**Issue by alfredwidell** [spatialaudio/python-sounddevice#100]
Hi,
I have an issue with audio glitches in my callback stream. I get audio out with short blocks of silence in between. I'm filtering 2 channels incoming data in frequency domain for 6 output channels. If I just copy the incoming data to the 6 outputs everything works fine `y_out[:, i] = x[:, i%2]`, no audio glitches. But as soon as I add some number crunching with the fft/ifft I start getting the audio glitches. I have checked that the problem does not lay in the filter process itself because when I send the indata directly to the output `y_out[:, i] = x[:, i%2]`, but keep the fft/ifft calculations in the loop I also get the glitches. I have also checked the load on the CPU and it is only working 4-5% of its maximum so I do not think that is the bottle neck. Is there something in the configuration/buffering that gives me this problem you think?

See code:
```
# Filter process
def filter_process(x, y_out, nr_samp, time, status):
    for i in range(NrOutChan):
        # y_out[:, i] = x[:, i%2]
        X = pyfftw.interfaces.numpy_fft.rfft(np.concatenate([x[:, i%2], x_zeros[i]]))
        y = pyfftw.interfaces.numpy_fft.irfft(X * H[i])
        y_out[:, i] = np.concatenate([overlap_save[i] + y[0:non_val[i]], y[non_val[i]:non_val[i] + val[i]]])
        overlap_save[i] = y[non_val[i] + val[i]:y_len[i] + 1]


def start(dev_index_in, dev_index_out, dev_chan_in, dev_chan_out, blocksize, dtype, fs):
    # Set PortAudio Stream configuration parameters
    if sounddevice.query_devices(dev_index_in)['hostapi'] != 2 or \
                    sounddevice.query_devices(dev_index_out)['hostapi'] != 2:  # If not an ASIO device
        extra_settings = None
        channels = None
    else:
        extra_settings = [sounddevice.AsioSettings(channel_selectors=dev_chan_in),
                          sounddevice.AsioSettings(channel_selectors=dev_chan_out)]
        channels = [len(dev_chan_in), len(dev_chan_out)]

    # Initialize PortAudio Stream
    st = sounddevice.Stream(samplerate=fs,
                            blocksize=block_size,
                            device=[dev_index_in, dev_index_out],
                            channels=channels,
                            dtype=dtype,
                            latency='high',
                            extra_settings=extra_settings,
                            callback=filter_process,
                            finished_callback=None,
                            clip_off=False,
                            dither_off=False,
                            never_drop_input=False,
                            prime_output_buffers_using_stream_callback=False)

    # Start stream
    st.start()

    # Return Stream object
    return st
```

**Comment by mgeier** [comment]
You should always check for xruns, have a look at the `status` argument!

A low system CPU usage doesn't tell you much, you should look at the [cpu_load](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.Stream.cpu_load) attribute (and that'll still not be 100% reliable).

What is your `block_size`?

**Comment by alfredwidell** [comment]
I added an if statement for all the variables in` status` like this:

 `if status._flags != 0 or status.input_overflow == True or status.input_underflow == True or status.output_overflow == True or status.output_underflow == True or status.priming_output == True:`
I put a breakpoint within the if statement to see if any parameter turned to `True` during execution. None of them did.

The `block_size` I use right now is 2^15 (32768). I have very long FIR filters. From an FFT point of view it should be efficient.

**Comment by alfredwidell** [comment]
How do I use the cpu_load properly? I'm supposed to get a value between 0 and 1 but I get two variables `fdel=None` and `fset=None` back from within the for loop, see below:
```
def filter_process(x, y_out, nr_samp, time, status):
    for i in range(NrOutChan):
        # y_out[:, i] = x[:, i%2]
        X = pyfftw.interfaces.numpy_fft.rfft(np.concatenate([x[:, i%2], x_zeros[i]]))
        y = pyfftw.interfaces.numpy_fft.irfft(X * H[i])
        test = sounddevice.Stream.cpu_load
        y_out[:, i] = np.concatenate([overlap_save[i] + y[0:non_val[i]], y[non_val[i]:non_val[i] + val[i]]])
        overlap_save[i] = y[non_val[i] + val[i]:y_len[i] + 1]
```

**Comment by alfredwidell** [comment]
Sorry did not mean to close

**Comment by alfredwidell** [comment]
I simplified the callback like shown below. I copy the [2, 32768] length data from input to output but I also add a fixed sleep time to see how much time I get to perform the calculations I need before the data is pulled. The sampling frequency is 44.1kHz so portaudio should only need to get new data each 32768/44100=0.74 seconds. But I notice that I cannot sleep for longer than 0.02-0.03 seconds before I start getting audio glitches (short pauses of silence). Any idea why this is? I would expect to have much more time to do the calculations before the data is being pulled. Is there some parameter setting that I miss to set properly?

I'm working on a Win10 system with ASIO drivers.

```
def filter_process(x, y_out, nr_samp, time, status):
    t.sleep(0.03)
    y_out[:] = x
```

**Comment by mgeier** [comment]
Your block size is really huge, I don't know if PortAudio or the host API can really handle that so well ...

I guess internally this would be split up into smaller blocks and that may be the reason why you have less time than expected (but I'm really just guessing here).
For better information, you could ask on the PortAudio mailing list.

I don't know if there is an upper limit, but something like `4096` already seems quite large to me.

If you need a larger block size for your calculations, you could try to use a queue to collect audio data in the callback, which you can then consume in bigger chunks. You could then write the results into another queue, which in turn can be read by the callback.

Regarding `status`: it should be enough to do

```python
if status:
    # do something
```

Are you sure that your breakpoint thing worked?
What about trying `print(status)` for now, just to be sure?
If you get dropouts, there really should be some detected xruns, otherwise PortAudio is broken.

> How do I use the cpu_load properly?

You were accessing it via the class, which doesn't work. You should access it via a stream instance, e.g. `print(st.cpu_load)`. You can do this either in the callback or from outside, both is allowed.

**Comment by alfredwidell** [comment]
I think PortAudio is able to handle these large block_sizes because I have a very similar implementation in MATLAB that works very well. In MATLAB I use the PsychPortAudio porting:  [http://docs.psychtoolbox.org/PsychPortAudio](url)
There is a parameter in PsychPortAudio where one is setting the size of the buffer one wants to use. This buffer needs to be larger than the `block_size`, I have put it to twice the size of the` block_size`, this works well. The data within the filter process is pulled each `block_size/fs` seconds when there is at least one `block_size` of the buffer free. Then there is plenty of time to pull the data without running out of samples.

`PsychPortAudio('GetAudioData',painput,2*block_size); ` 

> % Pre-allocate an internal audio recording buffer, twice the length of the block_size

I tried to `print(status)` but it only prints blanks, there is no info coming out.
```
def filter_process(x, y_out, nr_samp, time, status):
    t.sleep(0.1)
    y_out[:] = x
    print(status)
```
Then I managed to print the cpu_load it looks like this, no 1's but this is just a sampling, maybe it is choked sometimes but I did not catch it:
0.29530760970026854
0.11528313406110074
0.050049989232262726
0.021995917031796187
0.3644354373554331
0.1417299212661906
0.05555341069081988
0.021952020631744135
0.364155540781928
0.15714731666446283
0.06129264392716874
0.024191220069553928
0.40388197558164474
0.15714355163594826
0.06805725006978049
0.02975116195004524
0.018124301892902622
0.19353297658724883
0.07544353032323917
0.029686406397916018
0.017878129892970957
0.21456880169500875
0.07551095183609847
0.033202304225852255

**Comment by mgeier** [comment]
PsychPortAudio is a very different beast!
It doesn't expose the PortAudio API as directly as the `sounddevice` module does, it rather throws a few thousand lines of C code into the mix before exposing the functions to its users.

It looks like you can set the block size with the [Open](http://docs.psychtoolbox.org/Open) function, but incidentally it seems to be [limited to 4096 frames](https://github.com/kleinerm/Psychtoolbox-3/blob/c100115ac90cda70a7351feb7edc6865524ca45c/PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.c#L2216)!

You can use larger array sizes because PsychPortAudio does its own buffering. When using the `sounddevice` module, you'll have to do that on your own. I didn't look at it in detail, but probably you can implement something similar to what PsychPortAudio does internally.
Or you just try using two `queue.Queue`s, as I mentioned above.

As an alternative approach, you can try to use a "blocking I/O stream" (i.e. a stream without a callback function) and its `read()` and `write()` methods. Those methods can handle audio data that's longer than the block size (but they are, as the name suggests, blocking!).
I guess you'll also need to do some double-buffering in this case, and you'll probably need threads?
I have no experience with blocking streams, I normally use callbacks.

**Comment by alfredwidell** [comment]
Thanks for your insights Matthias. I will look into your suggestion to use queue's. If I solve the problem I will post it here.

**Comment by mgeier** [comment]
Good luck!

**Comment by mgeier** [comment]
@alfredwidell Any progress? Can I close this issue?

**Comment by alfredwidell** [comment]
Hi,
I did make it work after many trial and errors. I had to create an input buffer, an output queue and run the filter process in a separate thread. I'm now able to use arbitrarily long filter blocks like 32768 or more. It now works very smoothly even if it got a bit more complicated. It was your input that led me to a working system, thanks. I've pasted the code below including some comments that hopefully helps explain whats happening.

```
# Imports
import numpy as np
import sounddevice
import queue
import threading

# Init and start filter engine
def start(fs, dev_index, nr_chan, inp_chan, out_chan):
    # Initialize PortAudio Stream
    st = sounddevice.Stream(samplerate=fs,
                            blocksize=block_size,
                            device=[dev_index, dev_index],
                            channels=nr_chan,
                            dtype='float32',
                            latency='high',
                            extra_settings=[sounddevice.AsioSettings(channel_selectors=inp_chan), sounddevice.AsioSettings(channel_selectors=out_chan)],
                            callback=callback,
                            finished_callback=None,
                            clip_off=False,
                            dither_off=False,
                            never_drop_input=False,
                            prime_output_buffers_using_stream_callback=True)

    # Start stream
    st.start()

    # Return Stream object
    return st

# Sounddevice Callback
def callback(in_data, out_data, nr_samp, time, status):
    out_data[:] = q_out.get()  # Get data from output queue
    global in_buffer
    in_buffer = np.concatenate([in_buffer, in_data])  # Add data to input buffer
    if in_buffer.shape[0] == filter_block_size:  # Check for when input buffer gets filled equal to filter_block_size
        t = threading.Thread(name='Filter_Thread', target=filter_process, args=[in_buffer])  # Create new thread
        t.start()  # Start filter process thread
        in_buffer = np.zeros([0, 2])  # Empty the input buffer

# Filter process
def filter_process(x):
    y_out = np.zeros([filter_block_size, NrOutChan])  # Cannot be a global for unknown reasons? Need to def and reset here (otherwise glitches).
    for i in range(NrOutChan):  # Filter process
        # DO THE FILTERING
    for i in range(filter_block_size//block_size):  # Fill output queue with new filtered data of the right size
        q_out.put(y_out[i*block_size:(i + 1)*block_size])

NrOutChan = 8
filter_block_size = 2**15  # Processing block size. Next power of 2 larger than the longest filter for fft efficiency.
block_size = filter_block_size  # block_size = filter_block_size most efficient. Here one can choose an arbitrary power of 2 block size that is equal or smaller than filter_block_size.
in_buffer = np.zeros([0, 2])  # Define an input buffer
q_out = queue.Queue(maxsize=0)  # Define an output queue
for i in range(2*filter_block_size//block_size):  # The 2* adds twice the number of actual needed blocks to the queue so that the queue.get() cannot easily run out of blocks to feed sounddevice, even under temporary heavy CPU load.
    q_out.put(np.zeros([block_size, NrOutChan]))  # Add one block of zeros to the output queue.
```
