### ISSUE TITLE
Slow import times with cffi

### ISSUE THREAD

**Issue by tgarc** [spatialaudio/python-sounddevice#101]
What would you think about implementing the out-of-line ABI mode to improve import times? That mode is mentioned here in the docs:

http://cffi.readthedocs.io/en/latest/overview.html#out-of-line-abi-level

It still wouldn't require compiling the module, it just requires adding an extra file to the repository. I haven't given it a full look through, but was wondering if you would be open to the change. My issue is that the _FFI() and dlopen add hundreds of milliseconds of delay, even on my desktop ! You can imagine that on raspberry pi the delay would be even worse. I'm trying to use sounddevice to create a command line tool that should have a snappy start up time so that's personally why I'm interested but I think this change could improve overall usability.

**Comment by tgarc** [comment]
I did a quick implementation and some minimal time trials:

Here's the current sounddevice-0.3.8:

```
$ for i in {1..10}; do { time python -c 'import sounddevice' ; } 2>&1 | grep real; done
real    0m0.333s
real    0m0.252s
real    0m0.256s
real    0m0.165s
real    0m0.168s
real    0m0.213s
real    0m0.196s
real    0m0.228s
real    0m0.235s
real    0m0.192s
```

Here's the out-of-line build I quickly made:

```
real    0m0.113s
real    0m0.101s
real    0m0.100s
real    0m0.097s
real    0m0.086s
real    0m0.113s
real    0m0.077s
real    0m0.098s
real    0m0.112s
real    0m0.099s
```

Obviously this is a pretty high variability test but there is a significant reduction; maybe something like 80ms on the conservative side.

**Comment by tgarc** [comment]
Opened a PR #102

**Comment by mgeier** [comment]
#102 was merged, thanks again @tgarc!
