### ISSUE TITLE
Examples don't work 

### ISSUE THREAD

**Issue by alkopop79** [spatialaudio/python-sounddevice#109]
I've tried to run the spectrogram and the plot input examples (Ubuntu) and they yielded similar errors: 

```
  File "plot_input.py", line 48
    print(status, flush=True)
                       ^
SyntaxError: invalid syntax


------------------
(program exited with code: 1)
Press return to continue
```
and 
```
  File "spectrogram.py", line 70
    print(*line, sep='', end='\x1b[0m\n', flush=True)
          ^
SyntaxError: invalid syntax


------------------
(program exited with code: 1)
Press return to continue

```

What am I missing here? What'#s the deal with 'Flush'?

**Comment by alkopop79** [comment]
Ok, I figured it out: I need to launch them with python3 . However I still get errors with the examples. Apparently numpy can't handle floating point values anymore. see this: 

https://github.com/tomopy/tomopy/issues/252

Indeed, downgrading numpy helped helped: sudo pip install -U numpy==1.11.0

**Comment by tgarc** [comment]
thanks for the report. To clarify, the issue is that numpy doesnt accept floating point values as an index

**Comment by mgeier** [comment]
Yes, some examples don't work with Python 2, the `sounddevice` module itself should work on Python 2.6 and 2.7, though.

NumPy not accepting float indices is not a bug, this is an intentional change.

@alkopop79 Can you please provide the error message?

**Comment by alkopop79** [comment]
I've solved the original problems by downgrading numpy and running the examples with python3. I still get errors but I believe that has to do with settings on my system (Ubuntu running as VM on Mac OS X). I will give it a try on Mac OS X instead. Thank you for the kind help @mgeier and @tgarc, please feel free to close the issue!
