### ISSUE TITLE
Is there a way to call a function on individual samples / blocks when recording?

### ISSUE THREAD

**Issue by anath2** [spatialaudio/python-sounddevice#117]
I have a UI that responds to audio being recorded. Also, I want to calculate fast Fourier transform on each block for my pitch detection algorithm. Would that be possible?
Thanks a lot

**Comment by mgeier** [comment]
Sure, it's possible. But you'll have to implement it on your own (or using another library).
The `sounddevice` module is only for audio I/O, it's not for signal processing (that's called "separation of concerns").

You can also have a look at pyo or librosa. For a list of libraries for signal processing, see http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/signal-processing/index.ipynb.

**Comment by tgarc** [comment]
Hey @anath2 I'm doing similar things as you so thought I'd throw out some relevant info...

First off, I came across this pitch estimation algorithm a little while ago, haven't tested it myself but the author certainly knows what he's talking about

https://github.com/idiap/ssp

Also, likely you want to implement on recorded audio files first (for testing/implementation). PySoundFile has this really nice feature called 'blocks' you'll want to checkout:

http://pysoundfile.readthedocs.io/en/0.9.0/#block-processing

Here's an example of doing an STFT (1024 point, 50% overlap, hanning window):

```python
   import soundfile as sf, numpy as np

   blocksize = 1024

   with sf.SoundFile('my-file.wav') as sfh:
       window = np.hanning(blocksize)
       for x_l in sfh.blocks(blocksize, overlap=blocksize//2):
           X_l = np.fft.rfft(x_l * window)
```

Super simple right?? Thanks to people like @mgeier and @bastibe

Good luck!

**Comment by anath2** [comment]
@tgarc Super useful. Thanks a lot.
