### ISSUE TITLE
Displayed name in pulseaudio

### ISSUE THREAD

**Issue by Tadly** [spatialaudio/python-sounddevice#123]
I couldn't find anything regarding this so I'll just ask :)

I'm only using the `RawInputStream` for now but I assume this applies to everything be it input or output.

When active, pulsaudio shows the application as:
`ALSA plug-in [python]: ALSA Capture from           [available devices dropdown]`

Is there any way to change the name of it?

**Comment by mgeier** [comment]
I have no idea, but I assume there's nothing that can be done on the Python side.

How are other PortAudio applications (e.g. Audacity) shown?

I guess this has to be dealt with on the PortAudio level, you should probably ask on the PortAudio mailing list: http://portaudio.com/contacts.html

AFAIK, someone is (was?) working on a proper PulseAudio host API (without ALSA emulation) for PortAudio, which will probably display a better name.
I don't know what's the status of this.

**Comment by Tadly** [comment]
I kind of was expecting something like that.
Thanks for confirming :)

I also had a quick browse through th portaduio api and couldn't find anything that would allow it as of now.

Guess I'm stuck with that for now until I find the time to deal with portaudio directly.
