### ISSUE TITLE
Sudden "Invalid sample rate"

### ISSUE THREAD

**Issue by Tadly** [spatialaudio/python-sounddevice#124]
Erm...
I know this isn't an issue of this library but I honestly don't know where else to start so I'm kinda asking for guidance here.

This f.e now produces a `Invalid sample rate [PaErrorCode -9997]` exception:
```python
import sounddevice
sounddevice.RawInputStream(16000, 1024, channels=1, dtype='int16')
```
Here's the full stack:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tadly/Development/workspaces/python/jenny/.venv/lib/python3.6/site-packages/sounddevice.py", line 1064, in __init__
    **_remove_self(locals()))
  File "/home/tadly/Development/workspaces/python/jenny/.venv/lib/python3.6/site-packages/sounddevice.py", line 772, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/tadly/Development/workspaces/python/jenny/.venv/lib/python3.6/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawInputStream: Invalid sample rate [PaErrorCode -9997]
```

It was working just fine a few days ago.

I'm running archlinux with pulseaudio.
None of the alsa, pulseaudio or portaudio packages have been updated lately and now I'm not sure what to check next.
Are there any other packages I could/should check?

**Comment by Tadly** [comment]
So...
I was unmuting my input device in pulseaudio and now it's working again even if muted. (My notebook mic is horrendous so I keep it muted).

A previous reboot didn't "fix" it.

Sorry for bothering...
Just was just a random idea that popped into my head afterwards.

**Comment by Tadly** [comment]
Just gonna add that this issue keeps appearing and that toggling the mute state of my mic fixes it temporarily (for like 10 minutes or so).
Not sure what to make of that really...

**Comment by mgeier** [comment]
This is really strange. It reminds me a bit of https://github.com/bastibe/PySoundCard/pull/32.
But this seems to be a problem with the backend and I don't think there is anything I can do on the Python side.
You should try if you have similar problems with another (non-Python) PortAudio application (e.g. Audacity) and if yes, you should report it to the PortAudio mailing list.

**Comment by Tadly** [comment]
Not sure how much you care but it I think I found the issue...

My `.asoundrc` that I created because I was annoyed about my hdmi output being the default.
Never thought it could "break" that much :/
```
pcm.!default {                                                                 
    type hw                                                                    
    card 1                                                                     
}                                                                              
                                                                               
ctl.!default {                                                                 
    type hw                                                                    
    card 1                                                                     
}
```

**Comment by mgeier** [comment]
Thanks @Tadly for the additional information. I *do* care!
