### ISSUE TITLE
PortAudio in Ubuntu 17

### ISSUE THREAD

**Issue by azi92rach** [spatialaudio/python-sounddevice#126]
Hi, 

I have an issue to run sounddevice into Ubuntu 17. 

I installed Ubuntu in a new PC. Then I installed miniconda and I installed sounddevice. 
You can see that PortAudio is not found. Do you know why? Does it related to the Ubuntu 17?  

`$ python -m sounddevice 

Traceback (most recent call last):
  File "/home/parallels17/miniconda3/envs/pybpod-environment/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/parallels17/miniconda3/envs/pybpod-environment/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/parallels17/miniconda3/envs/pybpod-environment/lib/python3.6/site-packages/sounddevice.py", line 64, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found
`

Thanks in advance.

**Comment by mgeier** [comment]
How did you install the `sounddevice` module?

Unless the PortAudio library is included in the installation package, you have to install it yourself, see http://python-sounddevice.readthedocs.io/en/latest/#requirements.

**Comment by azi92rach** [comment]
@mgeier using 'pip install sounddevice' into conda environment. 
I installed PortAudio using 'sudo apt get portaudio19-dev' and it works, but I don't have in the query_devices my Xonar sound cards.

**Comment by mgeier** [comment]
You don't need `portaudio19-dev`, the package `libportaudio2` should suffice, as mentioned in the docs.

I'm glad that it works now, if some devices don't show up, please create a new issue for that (giving some more details).

**Comment by progtio** [comment]
![pexels-daniel-torobekov-11258468](https://user-images.githubusercontent.com/114249942/192170355-447d286a-a1e2-448e-a575-19fbb0369cf8.jpg)

yes
