### ISSUE TITLE
Recording speaker output

### ISSUE THREAD

**Issue by GelaniNijraj** [spatialaudio/python-sounddevice#129]
Is there any way to record the audio currently playing out of the speaker? If so, which device should I select?

Here's the list of available devices : 
```
>>> sd.query_devices()
  0 HDA Intel PCH: ALC3234 Analog (hw:0,0), ALSA (2 in, 0 out)
  1 HDA Intel HDMI: 0 (hw:1,3), ALSA (0 in, 8 out)
  2 HDA Intel HDMI: 1 (hw:1,7), ALSA (0 in, 8 out)
  3 HDA Intel HDMI: 2 (hw:1,8), ALSA (0 in, 8 out)
  4 HDA Intel HDMI: 3 (hw:1,9), ALSA (0 in, 8 out)
  5 HDA Intel HDMI: 4 (hw:1,10), ALSA (0 in, 8 out)
  6 sysdefault, ALSA (128 in, 0 out)
  7 pulse, ALSA (32 in, 32 out)
* 8 default, ALSA (32 in, 32 out)

```

**Comment by mgeier** [comment]
I don't think so.

But you could ask at the PortAudio mailing list: http://portaudio.com/contacts.html

This is also a very common question on https://stackoverflow.com/, so you might find an answer there.

What application is creating the audio you want to record?

If that application supports JACK, it is easy to re-route its output to another application that can record the signal.
Probably a similar thing is possible with PulseAudio?

Please report back what you find out!

**Comment by mgeier** [comment]
@GelaniNijraj Any news?

**Comment by GelaniNijraj** [comment]
Hey @mgeier, sorry for late response.

I was trying to rip songs played by the Firefox browser. I couldn't find a way to use python-sounddevice but I did find a tool small tool with GUI called audio-recorder which was able to do that. It also conveniently generates gst-launch-1.0 command to record the audio which then you can use inside your program.

**Comment by mgeier** [comment]
Thanks for the update! In case somebody else has the same problem, can you please provide a link to the program you used?

**Comment by GelaniNijraj** [comment]
Right, of course. Here's the [launchpad](https://launchpad.net/~audio-recorder) link and here's the [AUR](https://aur.archlinux.org/packages/audio-recorder) link that I used.

**Comment by mgeier** [comment]
Great, thanks!
