### ISSUE TITLE
RaspberryPi 3 Issue: ValueError: Not an input device: 'bcm2835 ALSA: - (hw:0,0)'

### ISSUE THREAD

**Issue by lgertel** [spatialaudio/python-sounddevice#133]
Hello everyone!
I'm with a error when trying to run on RaspberryPi3. The message is:

```
 File "remote.py", line 168, in start_recording
    device_info = sd.query_devices(device, 'input')
  File "/home/pi/berryconda3/lib/python3.6/site-packages/sounddevice.py", line 510, in query_devices
    'Not an {0} device: {1!r}'.format(kind, device_dict['name']))
ValueError: Not an input device: 'bcm2835 ALSA: - (hw:0,0)'
```

PortAudio is compiled and running, also the audio output is configured:

```
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
Subdevices: 1/1
Subdevice #0: subdevice #0
```

Anyone knows how to deal with this?

Thanks!

**Comment by tgarc** [comment]
It looks like you're trying to query the bcm2835 as an input (recording) device, which doesn't have any input channels. You need to specify your USB audio device to query_devices.
