### ISSUE TITLE
sounddevice play resets ASIO buffer size to what it was when sound device was initialized

### ISSUE THREAD

**Issue by joedeller** [spatialaudio/python-sounddevice#134]
This could well be a portaudio issue.

Using 32bit python 3.6 on windows 10 x64, sounddevice 0.3.9,
when I play a sound, the ASIO buffer size gets reset to whatever
the buffer size was when the script initialized the sound device.
It doesn't matter if I set `sd.default.blocksize = <current buffer size>`
nor setting blocksize in the play method

```python
import sounddevice as sd
import numpy as np

# code doing stuff for a while, another app changes ASIO buffer size during this time...
# Lets play a 2 channel wave, actually a sine generated in numpy
channels = 2
out_channels = np.linspace(1, channels, channels, dtype=int)
 # ASIO buffer size is what ever other app has set it to 
sd.play(my_wav, mapping =out_channels)
# ASIO buffer size has been changed back to what it was when the import sounddevice as sd 
# was executed
```

if I explicitly do:

```python
sd._terminate()
time.sleep(1)
sd._initialize()
sd.default.latency = 'low'
```

just before the sd.play,  this works around the problem, but itsn't ideal

**Comment by mgeier** [comment]
I guess this is just how the ASIO host API behaves. It might even be a basic ASIO limitation? I don't think there is anything on the Python side that I could do.

Your work-around looks reasonable.

If you want the behavior of the ASIO host API to change, you should ask at the PortAudio mailing list.

**Comment by joedeller** [comment]
Thanks for the speedy reply
As you say it's probably just the way things are, the workaround is working
fine, but might pursue PortAudio to see if there's anything they could do
to honor the blocksize parameters.

Thanks,

Joe

**Comment by mgeier** [comment]
OK, please keep us informed if you find more information.

I'm closing this issue, but feel free to open another one if something comes up!

**Comment by hockinsk** [comment]
I have a related issue where I use the ASIO Control Panel to e.g. set blocksize to 512, but as soon as SoundDevice connects, the blocksize switched to 1024? My understanding was ASIO protocol should only allow user to set blocksize, but maybe this is a PortAudio bug instead?

**Comment by Protoxy22** [comment]
> I have a related issue where I use the ASIO Control Panel to e.g. set blocksize to 512, but as soon as SoundDevice connects, the blocksize switched to 1024? My understanding was ASIO protocol should only allow user to set blocksize, but maybe this is a PortAudio bug instead?

Same problem here :/ When soundevice audio start it switch to an ASIO buffersize of 8 at 192kHz which of course gives a lot of glitch
