### ISSUE TITLE
playrec changes input_mapping if it is a numpy array

### ISSUE THREAD

**Issue by fhchl** [spatialaudio/python-sounddevice#135]
There is some strange behavior when using `sd.playrec` with the input_mapping as a ndarray.

```python
import sounddevice as sd
import numpy as np

input_mapping = np.array([1, 2])
sd.playrec([1.0], input_mapping=input_mapping, output_mapping=1, blocking=True)
print(input_mapping)

input_mapping = [1, 2]
sd.playrec([1.0], input_mapping=input_mapping, output_mapping=1, blocking=True)
print(input_mapping)
```
gives
```
[0 1]
[1, 2]
```

The `input_mapping` array is changed by `playrec` --- very confusing, if input_mapping is used several times.

**Comment by mgeier** [comment]
Thanks for the report!
I've created #136 to fix this bug. Can you please check if this works for you?

**Comment by fhchl** [comment]
Checked. The output is now
```
[1 2]
[1, 2]
```
Amazing! :smile_cat:

**Comment by mgeier** [comment]
@fhchl Thanks for testing, and thanks for the kind words!
