### ISSUE TITLE
Possible underrun buffers when using sd.play() with many output channels

### ISSUE THREAD

**Issue by fhchl** [spatialaudio/python-sounddevice#139]
I am using the `sounddevice.play()` function to play back audio over 18-30 separate audio channels over a Dante network on a Windows machine. The audio is also 18-30 channel, sampled at 48k and around 2 minutes long.
Now sometimes, though not always, some major artifacts are noticeable. Like very quick stoppings or clicking. In the Dante Virtual Soundcard I set the buffersize (2048 samples) and asio latency (20ms) to maximum and `sounddevice.default.latency = ('hight', 'high')`. Still these artifacts continue to appear.
Is there any way to check for under run buffers from within sounddevice?
Would it make sense to use OutputStreams instead of `play()` as in the [examples](https://python-sounddevice.readthedocs.io/en/0.3.11/examples.html) ? Any other suggestions?

**Comment by fhchl** [comment]
One should first read the documentation carefully ... seems like the output of `wait()` and `get_status()` is just what I need. 

Do you use `get_status()` after using `play()` to check for errors during that playback? Not clear from the documentation.

**Comment by mgeier** [comment]
I'm sorry if the documentation isn't clear enough. It would be great if you could make a pull request with improvements!

As you've mentioned, there are two ways to get information about xruns.
They both give you the same information, but `wait()` waits until playback/recording has finished before giving it to you.
If you know that playback/recording has already stopped, then there should be no noticeable difference between the two.

> Would it make sense to use OutputStreams instead of `play()`?

The `play()` function creates a new stream, immediately activates it and also starts playback.
Activating the stream can in some circumstances cause audible artifacts, but this normally only happens on very cheap sound cards (which I guess you don't have if you are using Dante). If you want to make sure this doesn't happen, you can start the stream sometime before you actually want to start your playback. Then you can either write your own callback function to start playing whenever appropriate, or you can use the `mystream.write()` function for playback.

> Any other suggestions?

Experiment with `blocksize` and `latency`. If you know your blocksize, you can also try to set `latency` to 0.
Check the latency reported by PortAudio, e.g. with `sd.get_stream().latency`.
Use `query_devices()` to get the default high and low latencies and check if they correspond to the values you have set in the virtual sound card/ASIO driver.
Note that sometimes high and low latency values are actually the same!

If you get audible artifacts *without* any reported xruns, this may be a problem in PortAudio, its ASIO back-end or perhaps even in the virtual sound card?

**Comment by mgeier** [comment]
@fhchl Are there any news? Or can I close this issue?

**Comment by fhchl** [comment]
Thanks for your input, @mgeier! I sadly can't accurately remember what I did there in the end, but I am not having such issues anymore. Can be closed.
