### ISSUE TITLE
Different input/output amplitudes in playrec loopback test

### ISSUE THREAD

**Issue by spidru** [spatialaudio/python-sounddevice#141]
I am using the ```playrec``` function to record an audio sample being played back on an ASIO audio interface configured in loopback mode. However, when comparing the input and output audio data, the output appears to be attenuated for some reason:

![capture](https://user-images.githubusercontent.com/11740200/40666959-3d41f802-6361-11e8-8472-fd11f63d8970.png)

I am calling ```playrec``` as follows (code snippet):

```python
import sounddevice as sdev
dataIn, fs = sfile.read(test_filename, dtype='float32')
dataIn = dataIn[:,0]    # strip off second channel
...
dataOut = sdev.playrec(dataIn, device=devId, samplerate=fs, blocking=True,
                channels=1, input_mapping=[1], output_mapping=[1])
```

Any ideas why this is happening?

**Comment by mgeier** [comment]
What about the mixer settings? Did you check the Windows audio settings? Or probably you have a specialized mixer application for your sound card? Or probably even hardware controls on your sound card?

Neither the `sounddevice` module nor the underliying PortAudio library change the volume of the audio channels. The only thing that changes the volume, is multiplying the sample values with a number (that's not `1.0`), but obviously you didn't do that (and `playrec()` doesn't do that either).

**Comment by spidru** [comment]
Solved: The problem was indeed that the Windows audio volume was about 80%, thanks for pointing this out. I feel incredibly silly for not noticing this earlier. Thanks for your time!
