### ISSUE TITLE
Segmentation fault on installation

### ISSUE THREAD

**Issue by kbrock84** [spatialaudio/python-sounddevice#142]
Getting error during install following the docs at:
http://python-sounddevice.readthedocs.io/en/0.3.11/

when running <code>python3 -m pip install sounddevice</code>

Output:
```
Successfully installed CFFI-1.11.5 pycparser-2.18 sounddevice-0.3.11
Segmentation fault
```

It looks everything was installed, but the last line <code>Segmentation fault</code>.

When I try to import the module it is not found. I am not getting  Segmentation fault errors on any other installs or commands, which leads me to believe it has something to do with the installation process.

EDIT:
I am using Raspbian GNU/Linux 9 (stretch)

**Comment by mgeier** [comment]
Please try installing `pycparser` first, then `CFFI`. Does the segmentation fault appear?

**Comment by kbrock84** [comment]
OK. I ran these commands in this order:
<code>python3 -m pip install pycparser</code>
<code>python -m pip install CFFI</code>

<code>pycparser</code> appears to be successfully installed.

On the <code>CFFI</code> install i am getting: 
```
Successfully installed CFFI-1.11.5 pycparser-2.18
Segmentation fault
```

Looks like it still attempts to install <code>pycparser</code>

**Comment by mgeier** [comment]
That's great news for me, because it seems unrelated to the `sounddevice` module.

You should have a look at the issue tracker of CFFI and if you don't find anything there, ask at their mailing list.

**Comment by kbrock84** [comment]
That's what I was thinking. Thanks for your advice.
