### ISSUE TITLE
Explanation of Over/Underflow errors in Read_the_Docs

### ISSUE THREAD

**Issue by Colin1964** [spatialaudio/python-sounddevice#155]
Extract from API section of  [Python--SoundDevice Read_the_Docs](https://python-sounddevice.readthedocs.io/en/latest/api.html#sounddevice.Stream)

> Input overflow.
> 
> In a stream opened with blocksize=0, indicates that data prior to the first sample of the input buffer was discarded due to an overflow, possibly because the stream callback is using too much CPU time. Otherwise indicates that data prior to one or more samples in the input buffer was discarded.
> 
> This can happen in full-duplex and input-only streams (including playrec() and rec()).
> 
> Output underflow.
> 
> Indicates that output data (or a gap) was inserted, possibly because the stream callback is using too much CPU time.
> 
> This can happen in full-duplex and output-only streams (including playrec() and play()).

I am receiving Underflow errors as described in the threads [here](https://github.com/googlesamples/assistant-sdk-python/issues/303) and [here](https://stackoverflow.com/questions/53224787/python-sounddevicestream-write-read-underflow-overflow-errors)

The error descriptions do not (for me as a Python novice) provide enough detail to allow me to investigate and correct the cause of the error. To be specific:

"Input Overflow. Otherwise indicates that data prior to one or more samples in the input buffer was discarded. "
Why was the data prior to the samples in the input buffer discarded? What test/ condition / flag indicated that the input buffer was full? How do you ensure that the input buffer is matched to the size of the data to prevent this? 

"Output underflow.

Indicates that output data (or a gap) was inserted, possibly because the stream callback is using too much CPU time."
What is meant by "Output data"? inserted into what (output buffer)? What is a "gap" defined as? How do you identify which "stream callback" this refers to? How does the user ensure that stream callback does not use too much CPU time.

In both cases, an example of how and why an Underflow and overflow condition has been triggered along with an explanation of how a user might modify parameters to correct the errors, would be very useful.

**Comment by mgeier** [comment]
Thanks for the report!

I've been quite lazy, because I have taken most of the documentation directly from the PortAudio documentation.

For example, this should sound familiar: http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#aea144f0edaf02d0ac8b113f41fb95c47

But you are right, some of the texts are not very helpful for understanding.

I'm planning to edit the documentation based on your suggestions, but I don't know when I'll have time to do that.

**Comment by Colin1964** [comment]
@mgeier Ok understood. Thank you for clarifying and I appreciate the response.

**Comment by mgeier** [comment]
We can leave this issue open as a reminder, it's definitely something that should be improved.

BTW, pull requests for improving the documentation are of course always welcome!

**Comment by mgeier** [comment]
I've just created #265.

Please leave your feedback there!
