### ISSUE TITLE
Detect silence during a stream recording

### ISSUE THREAD

**Issue by LoicSikidi** [spatialaudio/python-sounddevice#157]
Hello guys, i'm not familiar with your library yet and I would like to launch an action when the microphone catch a sound and do nothing when there is a silence.

For the moment, I did some tests based on this code example: spectrogram.py. In the callback function, what in the argument indata (object numpy) could inform me that there is noise caught or not.

```python
    def callback(indata, frames, time, status):
        if status:
            text = ' ' + str(status) + ' '
            print('\x1b[34;40m', text.center(args.columns, '#'),
                  '\x1b[0m', sep='')
        if any(indata):
          # HERE
        else:
            print('no input')
```
In my test, I never pass through the **else** condition.

Could you share with me a workaround?

Thank you in advance!

**Comment by LoicSikidi** [comment]
Hello @mgeier thank you for your feedback!

I will use your recommendation in my future developments.

**Comment by kasperschnack** [comment]
I'm looking for a similar sort of functionality. @LoicSikidi did you make progress with this?
