### ISSUE TITLE
Sounddevice doesn't release memory

### ISSUE THREAD

**Issue by AutomCoding** [spatialaudio/python-sounddevice#158]
After stopping an audio playback, sounddevice doesn't release the used data from memory. If the audio file is a few minutes long, more than a gigabyte of RAM has been devoured after four or five play/stop cycles.

```py
import sounddevice
import numpy
from scipy.io.wavfile import read
import time


a = read("audiofile.wav")

# Repeat the following lines a few times
sounddevice.play(numpy.array(a[1], dtype=float), a[0])
time.sleep(5)
sounddevice.stop()
time.sleep(2)
```

I'm using Python 3.7 on Windows 7 (64 bit) and all libraries are up to date.

**Comment by mgeier** [comment]
Thanks for the report, I'll have to look into this.

For now, I can just say there was a memory-related issue before: #58.

**Comment by mgeier** [comment]
There have been some improvements in the latest CFFI release 1.12: https://cffi.readthedocs.io/en/latest/whatsnew.html#v1-12.

@AutomCoding Can you please check if that improves the situation?

**Comment by AutomCoding** [comment]
Yes, I will have a look at it tomorrow.

**Comment by mgeier** [comment]
@AutomCoding Did you have a chance to check that in the meantime?

**Comment by catchanus** [comment]
I had the same problem.

Test program (Windows 7 64bit, Python 3.6.5, numpy 1.17.2, cffi 1.12.3, sounddevice 0.3.13, scipy 1.3.0):

```python
import sounddevice
import numpy
from scipy.io.wavfile import read
import time

time.sleep(5) #time to find the python.exe process in the list of processes
sample_rate, data = read("a2002011001-e02.wav") 
#http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02.wav
sounddevice.play(data, sample_rate)
time.sleep(10)
sounddevice.stop()
```
Memory usage of the process 'python.exe': start: 16 MB, end: 25 MB.

I solved memory leak as follows:

1. In test program I added the line 'data = None' at the end of the script.
2. In the 'stop ()' function of 'sounddevice.py' (319th line) I added the line '_last_callback.data = None' at the end of the 'if' statement.

It seems that the memory used by 'numpy' objects, in that case, has to be freed up manually.

**Comment by mgeier** [comment]
Can you please check if #250 fixes this for you?

**Comment by catchanus** [comment]
Great job!
It's good to remember if a variable like 'data' is created (numpy.ndarray), instead of passing numpy.ndarray object directly from read() (scipy) to play() (sounddevice), the program needs the 'data = None' line - its lack still means memory leak.

**Comment by mgeier** [comment]
Yes that's true.

`scipy.io.wavfile` uses the wrong order of outputs, but if you use https://python-soundfile.readthedocs.io/#soundfile.read, you can easily avoid the temporary variables (if you wish to do so):

```python
import soundfile as sf
import sounddevice as sd

sd.play(*sf.read('my-file.wav'))
sd.wait()
```

The two APIs have deliberately been designed to allow exactly this case.
