### ISSUE TITLE
Volume control?

### ISSUE THREAD

**Issue by segalion** [spatialaudio/python-sounddevice#159]
"python sound control" is very very fragmented over lots of pieces OS-dependant packages.
At my eyes, this package seems one of the most promissing because of portaudio related, but lacks one very important thing (that is missed in portaudio too): "the volume control".

play a wav file from python (that can run on all platforms) is a good thing, but maybe it doesnt sound because of volume is muted or something similar...

Are you planning to include (and try to "de-facto" standarize) a volume control functionality inside this library? 

Could be great to support get/set/mute/unmute all volume control (input and output) around in windows, linux (alsa/pulseaudio), and OSX, (even per-process when possible) all with the same api...

At this, a first aprox could be intregrate pycaw in windows, and a wrapper with amixer/aplay command-line, and something similar in OSX.

If in a future portaudio supports all this stuff, we could change the base libs and mantain the api so all programs work the same.

Obvously this is only a proposal of feature request.

**Comment by mgeier** [comment]
Thanks for your suggestions!

The `sounddevice` module is on the one hand just a PortAudio wrapper.

On the other hand, there are a few convenience functions that make it easy to play/record NumPy arrays (with some limitations, to keep it simple).

The convenience functions are implemented in pure, platform-independent Python.

I will not add another library dependency and I will not use any platform-dependent features (other than what PortAudio provides).

So unless PortAudio grows the ability to manipulate the volume control of the operating system (or audio framework), the `sounddevice` module will not be able to do that, either.

I have the feeling the topic "platform-independent volume control" is very complicated. I will not try to tackle this. And if somebody comes up with a way to do it, I will still *not* include it in the `sounddevice` module.

But nothing speaks against taking the `sounddevice` module and a hypothetical volume control module and combining the two into a new user-friendly package.

**Comment by jupiterbjy** [comment]
Just a reminder, up to certain limits with severe downside, controlling 'sound output' is at least possible via modifying sound data directly.

You can simply vector-multiply stream data, in this case *ndarray* to increase or decrease volume.

Increasing multiplier will make sound a bit louder, but with completely broken high freq. sound above certain level, probably due to value going over the limit. Usable range is around 1~2x.

Decreasing multiplier will lower output without notable issue, obviously. Ranging from 0~1x.

Here's example meant to be ran on python console.
```python
import sounddevice as sd
import soundfile as sf
import itertools
from numpy import ndarray


class VolumeChangeDemonstrator:
    def __init__(self):
        self.multiplier = 1
        self.offset = 0

    def load_audio(self, audio_dir: str):
        self.audio_file = sf.SoundFile(audio_dir)

    def callback_closure(self):
        last_frame = -1
        output_limiter = itertools.cycle((not n for n in range(10)))

        def callback(data_out: ndarray, frames: int, time, status: sd.CallbackFlags) -> None:
            nonlocal last_frame
            assert not status

            data_out[:] = self.audio_file.read(frames, fill_value=0) * self.multiplier + self.offset

            if last_frame == (current_frame := self.audio_file.tell()):
                raise sd.CallbackAbort

            last_frame = current_frame

            if next(output_limiter):
                print(f"Playback: {current_frame * 100 // self.audio_file.frames}%, "
                      f"Multiplier: {self.multiplier}, Offset: {self.offset}")

        return callback

    def play(self):
        self.stream = sd.OutputStream(
            samplerate=self.audio_file.samplerate,
            channels=self.audio_file.channels,
            callback=self.callback_closure()
        )
        self.stream.start()

    def __del__(self):
        self.stream.close(ignore_errors=True)
```

Usage:
```python
>>> from VolumeControlDemo import VolumeChangeDemonstrator
>>> stream_manager = VolumeChangeDemonstrator()
>>> stream_manager.load_audio("AUDIO_FILE_LOCATION")
>>> stream_manager.play()
...
>>> stream_manager.multiplier = 2  # change it while playing
```

**Comment by Sameer-hesta** [comment]
Hello, 
Can we handle the volume of output devices, as I am using Input to Output Pass-Through and I want to handle the volume(Or Mute/Un-mute) for the output devices after running the program by clicking on a button,

**Comment by HaHeho** [comment]
> Hello,
> Can we handle the volume of output devices, as I am using Input to Output Pass-Through and I want to handle the volume(Or Mute/Un-mute) for the output devices after running the program by clicking on a button,

Although not difficult to implement, I have the feeling that handling volume or mute here on the data stream level is not the most sensible approach. If you provide data to the output device with `sounddevice`, you should still be able to use your regular OS-specific hardware controls to regulate volume or mute. Right?

**Comment by Sameer-hesta** [comment]
Thank you for your response, I am new to this, 
I am using multiple headphones as output devices using Multi-threading and 
I just want to stop sharing  audio specified devices as( Mute)  and continue audio sharing as (Un-Mute)
Is it possible? If yes please let me know the way.

**Comment by HaHeho** [comment]
> I am using multiple headphones as output devices using Multi-threading and
> I just want to stop sharing audio specified devices as( Mute) and continue audio sharing as (Un-Mute)
> Is it possible? If yes please let me know the way.

I did not quite get what should be shared or muted?

Are the headphones individual audio devices? Or are they all being fed by the same audio interface?

**Comment by Sameer-hesta** [comment]
Let me explain by an example:
there are 3 Output devices connected to my system
 1. Default system speakers
 2. Earphones
 3. A bluetooth  Headphone/ Speaker
 Consider Input device as earphone's microphone
 I am taking input from microphone and Streaming it on all 3 outputs Using thread
 
 Now I want that Bluetooth headphone or default speaker should not receive the audio.
 or the person who is using headphone should not listen now until I want

**Comment by Sameer-hesta** [comment]
Thanks for your response, I have managed that with threading events.

**Comment by mike-lawrence** [comment]
@jupiterbjy Any chance you could advise on how to make your example work with looping audio?

**Comment by jupiterbjy** [comment]
@mike-lawrence

I would really discourage going that way as modifying stream data directly cause tons of problems - looking for other modules that use OS's volume control seems to be the best.

**Comment by mike-lawrence** [comment]
Recommendations against it granted, here's the looping version:

```python
class sound:
	def __init__(self,path,play,volume):
		self.volume = volume
		self.load_audio(path)
		if play:
			self.play()

	def set_volume(self,value):
		self.volume = value

	def load_audio(self, path: str):
		self.audio_file = sf.SoundFile(path)
		self.audio_data = self.audio_file.read()
		self.audio_file.close()
		self.tot_frames = len(self.audio_data)
		self.last_frame = 0
		self.num_channels = len(self.audio_data.shape)
		if self.num_channels==1:
			self.audio_data = np.column_stack([self.audio_data,self.audio_data])

	def callback_closure(self):
		def callback(data_out: np.ndarray, frames: int, time, status: sd.CallbackFlags) -> None:
			assert not status
			end_frame = self.last_frame + frames
			if(end_frame<=self.tot_frames):
				data_out[:] = self.volume * self.audio_data[self.last_frame:end_frame,]
			else:
				end_frame = end_frame - self.tot_frames
				tmp1 = self.audio_data[self.last_frame:,]
				tmp2 = self.audio_data[:end_frame,]
				if (tmp1.shape[0]==0):
					data_out[:] = self.volume * tmp2
				elif (tmp2.shape[0]==0):
					data_out[:] = self.volume * tmp1
				else:
					data_out[:] = self.volume * np.concatenate(tmp1,tmp2)
			self.last_frame = end_frame
		return callback

	def play(self):
		self.stream = sd.OutputStream(
			samplerate=self.audio_file.samplerate,
			channels=2,
			callback=self.callback_closure()
		)
		self.stream.start()

	def __del__(self):
		self.stream.close(ignore_errors=True)

```

**Comment by jupiterbjy** [comment]
Great work! Just watchout for sound glitch or even USB audio device malfunction, my JBL Quantum Duo broke down when fiddling with data directly - could be poorly designed product.

p.s. I recommend you to take a look at [PEP8 Style guide](https://peps.python.org/pep-0008/) as that's de facto standard.
