### ISSUE TITLE
How to generate 'ctrl+c' event or is there any internal function to stop the recording at any time?

### ISSUE THREAD

**Issue by dhineshdee** [spatialaudio/python-sounddevice#160]
I am developing a GUI which can record audio for an arbitrary duration using sounddevice and soundfile libraries. The recording process is stopped by pressing 'ctrl+c' button combination. I am trying to implement a GUI with a 'start' and 'end' button. The 'start' button should invoke the record function and the 'end' button should simulate 'ctrl+c' event. I don't know how this event can be implemented as a function in python. Or is there any other inbuilt function to stop the recording?
Here is the code. I want to implement the end_button_func() to stop the recording.

    import time
    import queue
    from PyQt5 import QtCore, QtGui, QtWidgets
    import soundfile as sf
    import sounddevice as sd
    import keyboard

    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(640, 480)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.pushButton = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton.setGeometry(QtCore.QRect(280, 190, 75, 23))
            self.pushButton.setObjectName("pushButton")
            self.pushButton.clicked.connect(self.record)

            self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_1.setGeometry(QtCore.QRect(380, 190, 75, 23))
            self.pushButton_1.setObjectName("pushButton")
            self.pushButton_1.clciked.connect(self.end_button_func)

            MainWindow.setCentralWidget(self.centralwidget)
            self.menubar = QtWidgets.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
            self.menubar.setObjectName("menubar")
            MainWindow.setMenuBar(self.menubar)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.pushButton.setText(_translate("MainWindow", "Start"))
            self.pushButton_1.setText(_translate("MainWindow", "End"))

        def record(self):
            self.q = queue.Queue()
            try:
                # Make sure the file is open before recording begins
                with sf.SoundFile('check.wav', mode='x', samplerate=48000, channels=2, subtype="PCM_16") as file:
                    with sd.InputStream(samplerate=48000, channels=2, callback=self.callback):
                        # 1 second silence before the recording begins
                        time.sleep(1)
                        print('START')
                        print('#' * 80)
                        print('press Ctrl+C to stop the recording')
                        while True:
                            file.write(self.q.get())

            except OSError:
                print('The file to be recorded already exists.')
                sys.exit(1)
            except KeyboardInterrupt:
                print('The utterance is recorded.')

        def callback(self, indata, frames, time, status):
            # TODO: Check for the existence of frames and time arguments
            """
            This function is called for each audio block from the record function.
            """

            if status:
                print(status, file=sys.stderr)
            self.q.put(indata.copy())

        def end_button_func(self):
            pass

    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

Thanks a lot.

**Comment by mgeier** [comment]
@dhineshdee Any news?

**Comment by dhineshdee** [comment]
Hello,

Thanks for your message. Sorry for not replying. 
Yeah, I solved this issue. The recording is run in a separate thread and the stop button raises a keyboard interrupt to stop the recording. However, I will take a look into your implementation.

Recently, I noticed another issue. Even though, we give 48kHz as the sampling rate parameter in the inputs for `soundfile` and `sounddevice` libs, the original recording is made according to the microphone recording setting (for example 8kHz) in the laptop and the lib converts the audio to 48kHz sampling rate. Actually, it is doing upsampling.

Do you have any idea how to solve this? I meant, the lib should be capable of recording as per the input parameters and not as per the laptops mic recording settings.

**Comment by mgeier** [comment]
> Actually, it is doing upsampling.

The underlying PortAudio library does resampling under some circumstances. Sadly, I don't know the exact rules for when it does that.
And I don't know how to check for the sample rates that are supported without resampling. There is the function [sounddevice.check_input_settings()](https://python-sounddevice.readthedocs.io/en/0.3.13/api.html#sounddevice.check_input_settings), but I think this doesn't provide a way to check for resampling.

Please ask at the PortAudio mailing list (http://portaudio.com/contacts.html) if you want to know details.

**Comment by mgeier** [comment]
@dhineshdee Any news?

**Comment by mgeier** [comment]
Closing due to lack of response.
