### ISSUE TITLE
Unable to access microphone

### ISSUE THREAD

**Issue by Sagov9** [spatialaudio/python-sounddevice#161]
Occurs when running python script from console, but not when calling python function from command promt, but again when executing the same command line from batch file. 'Run as administrator' does not help, microphone privacy settings are set to allow. Please help! The error message:

```
  File "C:\python27\WMF_FT_Audio.py", line 231, in buzzer_test
    recording = sd.rec(frames = int(fs*duration), samplerate = fs, blocking=True, channels = 2)
  File "C:\python27\lib\site-packages\sounddevice.py", line 224, in rec
    ctx.input_dtype, callback, blocking, **kwargs)
  File "C:\python27\lib\site-packages\sounddevice.py", line 2417, in start_stream
    **kwargs)
  File "C:\python27\lib\site-packages\sounddevice.py", line 1301, in __init__
    **_remove_self(locals()))
  File "C:\python27\lib\site-packages\sounddevice.py", line 780, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "C:\python27\lib\site-packages\sounddevice.py", line 2570, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'An invalid parameter was passed to a system function.' [MME error 11]
```

**Comment by mgeier** [comment]
It is strange that you have different behavior depending on how exactly you are using it.

Can you please show how exactly you are starting your script, how you use it at the command prompt and how you use it with a batch file?

Please also show the output of this command:

    python3 -m sounddevice

**Comment by Sagov9** [comment]
I run the function from the command line by typing something like this:
C:\python27\python -c "import MyFile; MyFile.MyFunction()"
The batch file just consists of the same line. I have made some progress trying to find the cause. For instance, I now know that it happens on computers at my work, but not at home, even though both run Windows 10. Also I have found that the same problem occurs when using different tools for recording; when using 'fmedia' to record from the command line it works fine, but if I put the same command in a batch file and run it, it fails. If I call the batch file from the command prompt however, everything works fine again. Any help pinpointing the cause of this behavior is appreciated.

**Comment by mgeier** [comment]
@Sagov9 Any news on this?

**Comment by Sagov9** [comment]
Yes, this has been resolved. The issue had to do with our protection software, which was restricting the access to the microphone. The reason the behavior was different dpending how the script was executed was due to right inheritance of parent application.

Kind regards, Thomas

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Matthias Geier <notifications@github.com>
Verzonden: Tuesday, April 2, 2019 6:42:35 PM
Aan: spatialaudio/python-sounddevice
CC: Sagov9; Mention
Onderwerp: Re: [spatialaudio/python-sounddevice] Unable to access microphone (#161)


@Sagov9<https://github.com/Sagov9> Any news on this?

**Comment by mgeier** [comment]
OK, thanks for the update!
