### ISSUE TITLE
sounddevice silently redirects stderr to /dev/null

### ISSUE THREAD

**Issue by pytaunay** [spatialaudio/python-sounddevice#166]
This is originally in reference to an issue in the psychopy Sound backend which uses sounddevice (see https://github.com/psychopy/psychopy/issues/2230)

`sounddevice` has a few lines of code that were added to remove the standard error output for convenience (pull request #12 in response to issues #11 and #10):
```
2670 def _ignore_stderr():
2671     """Try to forward PortAudio messages from stderr to /dev/null."""
2672     try:
2673         stdio = _ffi.dlopen(None)
2674         devnull = stdio.fopen(_os.devnull.encode(), b'w')
2675     except (OSError, AttributeError):
2676         return
2677     try:
2678         stdio.stderr = devnull
2679     except _ffi.error:
2680         try:
2681             stdio.__stderrp = devnull
2682         except _ffi.error:
2683             stdio.fclose(devnull)
2684 
2685 
2686 _ignore_stderr()
```
This redirects all of the standard error output to /dev/null and subsequently breaks built-in functions that use stderr display (e.g. "input"). This occurs in non-interactive sessions only (probably because of the way the CPython backend handles display with a prompt in interactive sessions).

mwe.py:
```
#!/usr/bin/python3

# This will display "Enter data" on the terminal
t = input("Enter data\n")

import sounddevice

# This does not 
t = input("Enter data\n")
```
`python3 mwe.py` will display "Enter data" the first time, but not the second time after sounddevice is imported. Commenting line 2686 in sounddevice.py gets rid of the issue.

stderr should **not** be redefined as /dev/null internally. I would suggest removing the `_ignore_stderr` function. For those who do not like stderr output, just use piping externally to redirect stderr to /dev/null or a log file.
Piping example:
```
#!/usr/bin/python3

# This will display "Enter data" on the terminal
t = input("Enter data\n")

print("Test")
```
`python3 pipe.py 2> /dev/null` will display only "Test". "Enter data" gets redirected to /dev/null.

**Comment by hoechenberger** [comment]
Related issue with the same cause: #37

**Comment by mgeier** [comment]
Thanks for the report!

First of all, I'm not planning to remove the "ignore stderr" feature by default, but I'm open to suggestions for making it optional.

This feature is very important, because for PyAudio (which doesn't have this feature), those warning messages cause a lot of confusion, as shown by these SO questions:

https://stackoverflow.com/questions/36956083/how-can-the-terminal-output-of-executables-run-by-python-functions-be-silenced-i
https://stackoverflow.com/questions/36912078/in-python-how-can-the-console-output-of-a-selection-of-code-be-suppressed
https://stackoverflow.com/questions/7088672/pyaudio-working-but-spits-out-error-messages-each-time
https://stackoverflow.com/questions/4672457/pyaudio-trying-to-use-jack
https://stackoverflow.com/questions/37733318/pyaudio-warnings-poluting-output
https://stackoverflow.com/questions/50162431/how-to-remove-pyaudio-errors
https://stackoverflow.com/questions/52927181/pyaudio-throws-warnings-on-raspberry-pi
https://stackoverflow.com/questions/49199935/python-error-and-pyaudio

FYI: the reason why the `input()` prompt doesn't work is related to a bug in CPython itself, see https://stackoverflow.com/questions/14009714/strange-redirection-effect-with-raw-input

It's really not that bad, because Python's `sys.stderr` isn't actually redirected, see my answer there: https://discourse.psychopy.org/t/sound-import-prevents-input-from-functioning-properly/6465/8
Can you come up with anything other than `input()` that's broken?

Luckily, there is a really simple work-around, see my answer there: https://discourse.psychopy.org/t/sound-import-prevents-input-from-functioning-properly/6465/4
And it looks like @peircej is willing to add this work-around to PsychoPy.

**Comment by pytaunay** [comment]
The `input` prompt "bug" is actually expected behavior (albeit surprising and not documented correctly). The function is defined in Python/bltinmodule.c as `builtin_input_impl`. It is designed to test if Python is operating in "interactive" mode or not. To do so it tests if the standard output is redirected. The behavior is as follows:

-  If the standard output is NOT redirected, then it uses the backend stdio_readline defined in Parser/myreadline.c; that function outputs the prompt on the standard error stream. This is why `python some_input.py 2> abc` redirects the standard error stream to "abc". 

- If the standard output is redirected, then now the function uses a call to `PyFile_WriteObject` whose two first arguments are the prompt and the standard output. In other words, if "input" detects that the standard output is redirected, it then outputs the prompt in said standard output. This is why `python some_input.py > abc` also has no output on the terminal: the prompt was sent to the standard output in this case, not the standard error. 

I have verified this behavior by adding print statements in the corresponding code sections in the C backend.

As far as I can tell sys.stderr is not broken. However, I ran into issues using `stderr` and `fprintf` directly in the C backend. Here is an example where I modified the built-in print function `builtin_print` defined in Python/bltinmodule.c:
```
fprintf(stdout, "%s", "stdout goes here\n");
fprintf(stderr, "%s", "stderr goes here\n");
PySys_WriteStderr("%s","stderr goes here from sys\n");
```
above `for (i = 0; i < PyTuple_Size(args); i++) {` (roughly line 1754). 
If everything is fine, then all of these statements are printed on the console. 
Here is the corresponding Python script that I ran with that:
```
import sys
input("Testing! ") # Outputs "Testing!" on the terminal

import sounddevice

input("ABC ") # Does not output "ABC" on the terminal
print("Test!") # Should output the various fprintf's, then "Test"
```
Corresponding output:
```
Testing! N
Y
stdout goes here
stderr goes here from sys
Test!
```
As expected the input prompt for ABC does not show up. What's more worrisome is that the `fprintf` statement on what should be `stderr` does not show up either. The one from the sys module shows up though. I think that a bunch of error statements from the C backend (e.g. memory errors) would suffer from the same problem. That seems dangerous to me.

What I do not understand is how `stderr` from the sys module is preserved, while the "main" standard error is not. The latter is called directly from the cffi cdefs as far as I understand, but again does not seem to impact the former.

I would argue that silencing error streams is problematic since you may miss something important. All of the output can also be controlled using standard terminal tools. If that's not possible then maybe have the user call the "initialize" function and pass it an argument that controls the verbosity of the output (e.g. False -> _ignore_stderr will be called). You can also silence the ALSA library entirely with a callback function:
```
#!/usr/bin/python3

import ctypes
from ctypes import POINTER
from sys import getsizeof

### Load the portaudio library
asound = ctypes.cdll.LoadLibrary('/usr/lib/x86_64-linux-gnu/libportaudio.so.2')

### Define our error handler type for this function call:
# include/error.h:59:typedef void (*snd_lib_error_handler_t)(const char *file, int line, const char *function, int err, const char *fmt, ...) /* __attribute__ ((format (printf, 5, 6))) */;
# CFUNCTYPE is a factory; it creates "types" for callback functions 
# CFUNCTYPE arguments are types
# 1. Return of the C function to which it points 
# (here void -> None)
# 2. Inputs of the C function to which it points 
# (here char*, int, char*, int, char* -> c_char_p, c_int, c_char_p, c_int, c_char_p 
# 3. The pointer to the variadic argument list is passed as c_void_p
ALSA_ERROR_HANDLER_FUNC = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_void_p)

### Define the Python wrapper will be used to call the C backend 
def ALSA_py_error_handler(filename, line, function, err, fmt,arg):
   # Pass to do nothing; or you can print filename, line, function, error number
    pass

### Create the C-callable callback ALSA_c_error_handler 
ALSA_c_error_handler = ALSA_ERROR_HANDLER_FUNC(ALSA_py_error_handler)

### Set the C-side error handler; it will use the Python callback but is callable from C 
asound.snd_lib_error_set_handler(ALSA_c_error_handler)

### No output created, even with _ignore_stderr commented
import sounddevice 
```
It'd be better to use a log file but ctypes can't reliably handle C variadic functions, which is what snd_lib_error_set_handler is... I could only retrieve the first argument every time, but not the second one when a second one appears.

I have not looked at other libraries.

**Comment by hoechenberger** [comment]
> I would argue that silencing error streams is problematic since you may miss something important. All of the output can also be controlled using standard terminal tools. If that's not possible then maybe have the user call the "initialize" function and pass it an argument that controls the verbosity of the output (e.g. False -> _ignore_stderr will be called).

I would Ike to see that implemented :)

**Comment by mgeier** [comment]
Thanks @pytaunay for the thorough research, that's really interesting and I really appreciate it!

> The `input` prompt "bug" is actually expected behavior (albeit surprising and not documented correctly).

It is indeed very surprising!
And whether expected or not, it is definitely either a bug in the behavior or a bug in the documentation.
So I will keep calling it a "bug" until either one is fixed.

And why is `import readline` changing the behavior?
Does that mean the `readline` module has a bug?
After importing `readline`, the behavior is definitely much more obvious to me.

> I think that a bunch of error statements from the C backend (e.g. memory errors) would suffer from the same problem. That seems dangerous to me.

As I see it, that's the price I'll have to pay for not being annoyed by PortAudio's useless messages all the time.

I'm willing to pay that price.

> I would argue that silencing error streams is problematic since you may miss something important.

Except out-of-memory errors, what could that possibly be?

> If that's not possible then maybe have the user call the "initialize" function

I consider it a very important usability feature of the `sounddevice` module, that the user doesn't have to worry about an "initialize" function.

The main use case I had in mind when I designed the API, was interactive use, and in this case I don't want to type an extra "initialize" command.

Some time ago, I was thinking about creating a separate module `sounddevice_lowlevel` (or something like that) which doesn't automatically "initialize" and wouldn't silence `stderr` and which is then used by the higher-level `sounddevice` module.
I even started working on it in the `lowlevel` branch: https://github.com/spatialaudio/python-sounddevice/compare/0.3.12...lowlevel

But sadly, I didn't get very far ...

If you want to continue in that direction, that would be great!

> You can also silence the ALSA library entirely with a callback function

This would only solve part of the problem. You would still get messages from JACK and you would get deprecation messages on some versions on macOS.

**Comment by mgeier** [comment]
An option to make silencing `stdout` (and probably initializing PortAudio) optional might be using an environment variable?

**Comment by pytaunay** [comment]
A pure Python context manager allows you to redirect stderr without messing with the C backend. I put together a solution based on https://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python for which I will submit a pull request. It suppresses the warnings that show up during the initialization of ALSA and friends but it can technically be extended to other. 

> And why is `import readline` changing the behavior?

Probably because readline overrides the built-in `input` command to parse input but I have not checked that yet.

> Except out-of-memory errors, what could that possibly be?

I want to emphasize again that while there may not be many errors raised by the C backend of Python, they may be serious. There are errors for: out of memory, overflow, parsing, input/output, file descriptor, memory allocation, gzip, etc.

> As I see it, that's the price I'll have to pay for not being annoyed by PortAudio's useless messages all the time.
> I'm willing to pay that price.

In effect this is messing with your car electronics and then removing the lightbulb behind the check engine light because driving with it on is annoying. You could be missing a simple reminder that the oil change is due, or a more important transmission issue. The errors are still there, they just don't show up anymore; if not addressed it may result in additional problems. 
I get warning messages are aggravating (I do tend to ignore a bunch of them when compiling stuff) but in this context they can hide more important things coming from the backend of Python.

**Comment by mgeier** [comment]
Thanks for the additional information and for PR #168!

You are right, there are some potentially important messages that are currently silenced.
But I really don't want the user experience to become bad in 99.9% of cases in order to be informed of an error that happens in 0.1 % of cases (or probably much less often).

As I said, the main use case I'm targeting is interactive use.

I'm open for options that can be switched on explicitly for other use cases, as long as they don't impede interactive use.

> In effect this is messing with your car electronics and then removing the lightbulb behind the check engine light because driving with it on is annoying.

That's exactly what it is!

Well, except for the "messing with your car electronics". I'm only removing the lightbulb.

I think the root problem is that PortAudio doesn't provide an error/warning handler that could be used to forward (or ignore) messages.

JACK actually has such a mechanism, but I really don't want to add a dependency to the JACK library. Same for ALSA (as you mentioned already).

**Comment by mgeier** [comment]
Since #176 (and since the latest release 0.3.14), the `sounddevice` module only redirects `stderr` during initialization.

This redirection is still not optional.
If somebody wants to work on making it optional, please open a new issue or pull request!
