### ISSUE TITLE
Mono .wav files are no longer playing

### ISSUE THREAD

**Issue by bradricketts** [spatialaudio/python-sounddevice#171]
Hi,

I've been having a problem recently with playing mono .wav files over any output channel.  I've used this same content for quite a while with Sounddevice without any issue, but just recently this content will no longer play.  There has been no change in drivers, python libraries, or equipment.  The file will begin playback for an instant, then stop playing.  

For more context, I'm using ASIO drivers in Windows 10 with a Lynx Studio Techologies AES16e AES3 PCIe card and a Lynx Studio Technologies Aurora(n).  The .wav files are created using sox, and the only difference between the files is the number of channels.  I've attached the mono and stereo files that I've tried.

I've tried the same content in Adobe Audition and a free player called Winyl and they both playback using the ASIO driver just fine.  

Given that I haven't changed anything in my Python scripts, though I have attempted to reinstall Python and created a new virtualenv with no effect, the only thing that I can think of is that something has been changed by Windows Update, but there's been so many changes/screwups by Microsoft there that I haven't been able to find any needles in the haystack.

Any ideas?

[content.zip](https://github.com/spatialaudio/python-sounddevice/files/2882087/content.zip)

P.S.  Thank you for writing (in my opinion) the best Python audio library out there.

**Comment by mgeier** [comment]
Thanks for the praise!

Sadly, given the information, I have no idea what's going wrong.

The `sounddevice` module cannot read from audio files, so I guess you are using some other library to do that. Probably that's going wrong?

Once you have read your files, you could probably plot the data to see if everything looks as expected?

Could you provide some minimal Python code that shows the problem?

**Comment by mgeier** [comment]
@bradricketts Can you please provide the requested information?

**Comment by mgeier** [comment]
Closing due to lack of response.

Feel free to add comments with new information.
