### ISSUE TITLE
Cancun Asio Driver not detected

### ISSUE THREAD

**Issue by yoachimhoryn** [spatialaudio/python-sounddevice#175]
Hello,

I hope you can help me with this issue
My release of sounddevice is 0.3.13 and my version of portaudio is V19.6.0-devel
I have a sound card connected, model CANCUN 442-Mic.
I have installed the latest drivers.
When I use another app, the CANCUN ASIO DRIVER is detected
However, when I use sd.query_devices(), I only get the following list :

```
   0 Mappeur de sons Microsoft - Input, MME (2 in, 0 out)
>  1 Microphone sur casque (Jabra EV, MME (2 in, 0 out)
   2 CANCUN AES In 1 (CANCUN 442-Mic, MME (2 in, 0 out)
   3 CANCUN AES In 2 (CANCUN 442-Mic, MME (2 in, 0 out)
   4 CANCUN Analog In 3/4 (CANCUN 44, MME (2 in, 0 out)
   5 CANCUN Analog In 1/2 (CANCUN 44, MME (2 in, 0 out)
   6 Mappeur de sons Microsoft - Output, MME (0 in, 2 out)
<  7 CANCUN Analog Out 1/2 (CANCUN 4, MME (0 in, 2 out)
   8 CANCUN AES Out 2 (CANCUN 442-Mi, MME (0 in, 2 out)
   9 CANCUN AES Out 1 (CANCUN 442-Mi, MME (0 in, 2 out)
  10 CANCUN Analog Out 3/4 (CANCUN 4, MME (0 in, 2 out)
  11 Casque pour téléphone (Jabra EV, MME (0 in, 2 out)
  12 Haut-parleurs / écouteurs (Real, MME (0 in, 2 out)
```

No sign of the CANCUN ASIO DRIVER

Any idea on how to solve this ?
Thanks for your help

**Comment by mgeier** [comment]
Are you using the version of the PortAudio library that is provided with the `sounddevice` module?

If you use a PortAudio library from a different source, it may have been compiled without ASIO support.

Can you please provide the output of the following:

    print(sd._libname)

> When I use another app, the CANCUN ASIO DRIVER is detected

Does this other app use PortAudio?
Did you try it with Audacity?

**Comment by yoachimhoryn** [comment]
Thank you for your help

I think the PortAudio library version was that provided by the sounddevice module
But I couldn't be sure.

The other app I was mentioning is an internal app, which was installed before sounddevice.
I know very little about it.
The only thing I know is that it is using portaudio, and that the CANCUN Asio Driver is detected with it.
But it's possible that multiple PortAudio be in conflict

The output of print(sd.libname) is 
C:\Users\username\AppData\Local\Continuum\anaconda3\bin\libportaudio-2.dll

The Asio Driver is not detected with Audacity as well

What should I do to solve this possible conflict ?

Thank you

**Comment by mgeier** [comment]
Thanks for the additional information!

So it looks like you installed the `sounddevice` module with `conda`, I guess using the `conda-forge` channel: https://anaconda.org/conda-forge/python-sounddevice.
I guess this uses the PortAudio library provided by `conda-forge`: https://anaconda.org/conda-forge/portaudio.

This is the development page: https://github.com/conda-forge/portaudio-feedstock
And there we have it, there's already an issue about missing ASIO support: https://github.com/conda-forge/portaudio-feedstock/issues/9

To get ASIO support, you should uninstall `python-sounddevice` and `portaudio` with `conda`.
Then you should install the `sounddevice` module with `pip`, see https://python-sounddevice.readthedocs.io/en/0.3.13/installation.html for details.
When you install it with `pip`, the PortAudio library should be automatically installed, an this version should support ASIO.

**Comment by yoachimhoryn** [comment]
Thank you for this solution
This was exactly the problem, and the method you suggested solved it.
I close this issue
Best regards

**Comment by mgeier** [comment]
Thanks @yoachimhoryn, I'm adding this to the documentation: #177.
