### ISSUE TITLE
Can I change windows default setting by sounddevice?

### ISSUE THREAD

**Issue by KzDog** [spatialaudio/python-sounddevice#179]
If there are two audio input interface on my windows: **Mac-in** and **Line-in** ,can I set one of them to be a default input and make it work on windows?

**Comment by mgeier** [comment]
You can use `sounddevice.default.device` to set the default device, see https://python-sounddevice.readthedocs.io/en/0.3.13/api.html#sounddevice.default.device.

For example, you could try this:

```python
import sounddevice as sd

sd.default.device = 'Line-in', None

# record some sound here!
```

**Comment by KzDog** [comment]
Thanks, it is working!
