### ISSUE TITLE
Exception: Exception: Error during playback: output underflow

### ISSUE THREAD

**Issue by amoxuk** [spatialaudio/python-sounddevice#180]
```python 
           data, fs = sf.read(music, dtype='int16')
            sd.default.channels = [2, 2]
            sd.default.device = [input, output]
            sd.default.samplerate = fs
            my_record = sd.playrec(data)
            status = sd.wait()
            if status:
                raise Exception('Error during playback: ' + str(status))
```
Traceback (most recent call last):
  File "F:/VCS-RF/Lib/AudioTest/AudioTest.py", line 252, in <module>
    at.paly_record("Standard_20s.wav", "new_Standard_20s.wav", input=u'MZ0380 PCI, Analog 01 Audio (MZ', output=u'DigitalOutput (NVIDIA High Defi')
  File "F:/VCS-RF/Lib/AudioTest/AudioTest.py", line 110, in paly_record
    raise Exception(type(e).__name__ + ': ' + str(e))
Exception: Exception: Error during playback: output underflow

I have tried to change `sd.default.blocksize = 512`. But it cannot work well.

**Comment by mgeier** [comment]
Thanks for the report!

Changing the `blocksize` is normally a good approach. Did you also try higher block sizes like `1024` or `2048`?

Alternatively, you could keep the default `blocksize=0` and experiment with something like

```python
sd.default.latency = 0.1
```

Could you please show your list of devices and which devices you have selected for playback and recording?

**Comment by amoxuk** [comment]
Thanks for you reply.
All the values I had tried but 0.1.
I found that if I only play the music, the output voice is normal. But when I play and record the music, the voice would be very slow. I try to change the sampleframes, but there is no improvement.

**Comment by amoxuk** [comment]
Unfortunately, blocksize=0 with latency=0.1 is not  a good solution.
It still cause error.

**Comment by mgeier** [comment]
@amoxuk Did you find a combination of settings that works?

**Comment by mgeier** [comment]
Closing due to lack of response.
