### ISSUE TITLE
Tutorial / Workflow

### ISSUE THREAD

**Issue by mc-seatown** [spatialaudio/python-sounddevice#182]
Pyaudio does not work with my current setup. Sounddevices appears to do everything I want, but I am unsure how to pass a RawStream to a device output. I have set up my devices. My raw streaming code runs without error, but I don't hear anything. Is there documentation with a simple workflow to simply load audio into a Raw Stream and record that stream? I can't find the answer anywhere. My sincere apologies for such a basic question. I believe my issue could be useful for those who are just beginning the process of signal processing. I can use Librosa to covert to frequency and create an array, but I'd like to simply record an input for now, save that file and open in Librosa. Again, apologies...

**Comment by mgeier** [comment]
You are very welcome to ask basic questions here, don't worry!

Sadly, I don't quite understand what you are trying to achieve.

First of all, `RawStream` is nearly the same as `Stream`, except that access to audio data is not provided via NumPy arrays but via plain old Python buffer objects. Everything else should be the same.

Did you have a look at the [examples](../blob/master/examples/)?

Do you want to play back some sound or record it?
Or do you want to do both at the same time?

Do you want to use NumPy or do you want to avoid using it?

There are examples for all those options. Some use "raw" streams, some use NumPy arrays.
Anything that can be done with NumPy arrays can also be done with "raw" buffers, but  you typically have to write a bit more code for that.

> I'd like to simply record an input for now

Again, there is an open question here: Do you know in advance how long your recording should be or do you want to start recording and decide at some later point when to stop?

The first case is quite simple, see https://python-sounddevice.readthedocs.io/en/0.3.13/usage.html#recording.

The second case is a bit more complicated, but there's also an example: [examples/rec_unlimited.py](../blob/master/examples/rec_unlimited.py).

> save that file and open in Librosa

The `sounddevice` module is not able to load and save files. You'll have to use a separate module for that. There are multiple options, see e.g. https://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/audio-files/index.ipynb.

I think LIbrosa also supports NumPy arrays, so you don't really have to save the recorded audio data to a file (unless you want to), but you can directly record into a NumPy array and pass that on to Librosa.

**Comment by CarrCode** [comment]
So I recorded to an array.

Now I need to figure out how to use a buffer / timer to process the audio in real time.

The code for audio passthrough is a little convoluted for my current understanding of this library.

Any best practices to work with a buffer and use Librosa in real time?

**Comment by mgeier** [comment]
> The code for audio passthrough is a little convoluted for my current understanding of this library.

It's 8 lines of code, including error reporting: https://python-sounddevice.readthedocs.io/en/0.3.13/usage.html#callback-streams

Is this really too convoluted?

> Any best practices to work with a buffer and use Librosa in real time?

I have no experience with Librosa. But I guess you can just call Librosa functions in the callback function using your `indata` array and write the results to the `outdata` array (and don't forget to use `outdata[:]` or something similar).

Alternatively, you can also have a look at http://ajaxsoundstudio.com/software/pyo/ (http://ajaxsoundstudio.com/pyodoc/), which is specifically made for real-time DSP.

Please note that I don't have any experience with Pyo either.

**Comment by CarrCode** [comment]
No, it isn't convoluted! I figured it out with your help. Thank you for everything. This has been a great service to me. Appreciate the time you took to step me through this.

**Comment by mgeier** [comment]
No problem! If you have any suggestions for improving the documentation (or any other aspect of the module), please open another issue!
