### ISSUE TITLE
Volume boosted to insane levels

### ISSUE THREAD

**Issue by SimLoads** [spatialaudio/python-sounddevice#183]
Not sure if this is just me, but anything I play with Sounddevices sounds like its being sent through an overdrive pedal. It's insanely loud - what can be done?

**Comment by mgeier** [comment]
Did you try the [examples](../blob/master/examples/)?

Did you try different host APIs?

Did you try another software that uses PortAudio (e.g. Audacity)?

**Comment by mgeier** [comment]
Closing due to lack of response.
