### ISSUE TITLE
How does Sounddevice handle simultaneous play and rec

### ISSUE THREAD

**Issue by Den336** [spatialaudio/python-sounddevice#186]
Hi 
Not an issue as such.
I want to develop an understanding of how sounddevice handles simultaneous playrec.

If I try sounddevice.play and sounddevice.rec in different processes via multiprocessing , the playback affects the recorded audio. To clarify I listen to the file being played through headphones while recording so the interference I presume is from input and output through soundcard.
Using sounddevice.playrec - no such interference is heard.

**Comment by mgeier** [comment]
You could try to manually create separate "streams" for each process, maybe that works better?

You could also check if #118 helps.

Do you actually need `multiprocessing`?

It's normally simpler to only use a single stream at a time. That's also what `playrec()` is doing. It's not using two different streams for playback and recording, it's just using a single (duplex) stream.

**Comment by antoinepryy** [comment]
Hi, 

The most efficient way would be to use sounddevice.Stream (doc [here](https://python-sounddevice.readthedocs.io/en/0.3.12/api.html#sounddevice.Stream)) that would allow you to manage at the same time input & output


```
import sounddevice as sd
duration = 5.5  # seconds

def callback(indata, outdata, frames, time, status):
    if status:
        print(status)
    outdata[:] = indata

with sd.Stream(channels=2, callback=callback):
    sd.sleep(int(duration * 1000))
```
is me minimal way to do it.

Also, `indata` represents an array with audio from microphone, and `outdata` an array that you have to fill and which will be sent each time the callback is called. So on the example the output will repeat what is played in the mic

**Comment by mgeier** [comment]
@Den336 Any progress?
