### ISSUE TITLE
In/out callback method on Linux

### ISSUE THREAD

**Issue by ryback08** [spatialaudio/python-sounddevice#188]
Hello

I try test sounddevice lib in callback mode with stream class (need 2 channels in+out at same time).
My program works fine in windows 10, with python 3.6, portaudio 1.9.6, with different mode
But, the same program didn't works on linux ubuntu with alsa (tested on different hardware 16.04, 18.04, 19.04, python 3.6, 3.7) and raspberry with usb soundcard. I have many random "crak" only on linux  when i generate my sound (just sinusoidal tone with numpy)

So I tested "Input to Output Pass-Through" ([wire.py](https://python-sounddevice.readthedocs.io/en/0.3.13/_downloads/wire.py)) in exemple program documentation.
Same conclusion and fault, works on windows, not in linux (didn't yet try in raspberry)
In configure manualy device with "sysdefault, ALSA"
`with sd.Stream(device=( x, x), .....`

I see that i have "status" flag on callback give input underflow, overflow or twice.

how can I solve the problem ?
what can i do to help you to solve the problem ?

_that is the output, you can see frame drop_
![sounddevice_wire](https://user-images.githubusercontent.com/24714750/60021355-287a3500-9692-11e9-9aa9-6b78de22d380.jpg)

Thanks

**Comment by mgeier** [comment]
Sorry for the late response!

You should experiment with the `latency` setting (keeping `blocksize=0`) or with the `blocksize` setting.

If a device is listed multiple times in the device list, you should try all of them.

**Comment by mgeier** [comment]
@ryback08 Any news?

**Comment by ryback08** [comment]
Hello Mgeier, 
Actually fully busy, the project is in standbye ;(
Of memory :
-  blocksize didn't change random crack
-  On linux, I think I remember that it worked perfectly with option "latency=low". 
-  i'm try PyAudio and the same crack appear, so, sounddevice isn't guilty

**Comment by mgeier** [comment]
OK, thanks, good to know.

`latency='high'` should produce less cracks than `latency='low'`.
You could also try to use a concrete latency value, e.g. `latency=0.1`.

I'm closing this issue, but if you have further details, please add more comments here.
