### ISSUE TITLE
Documentation: Give example of populating numpy array with sine wave and playing it 

### ISSUE THREAD

**Issue by cool-RR** [spatialaudio/python-sounddevice#189]

**Comment by mgeier** [comment]
Thanks for the suggestion!

I'm open for pull requests, contributions are very welcome!

In the meantime, here are two introductory notebooks:

https://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/simple-signals.ipynb

https://nbviewer.jupyter.org/github/spatialaudio/communication-acoustics-exercises/blob/master/intro.ipynb

**Comment by cool-RR** [comment]
Thanks for these!

**Comment by ryback08** [comment]
Hello, I'm working on similar project, i modified my code to generate configurable sinusoidale sound with OutputStream sounddevice fonction in callback mode. Tested on linux and windows, fully works.
I'm python beginner, I am listening to improvement.

Can you try to modify my code and replace OutputStream by Stream, modify too callback to add indata. The sound crack only on linux (lost frame ?? in data overflow ?? )


[makeSinStream.zip](https://github.com/spatialaudio/python-sounddevice/files/3355166/makeSinStream.zip)

`
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  2 08:07:53 2019
@author: Ryback08

This fonction play a sinus generate in realtime with numpy array. Sounddevice callback method is use.
don't forget to configure correctly your soundcard, check "DEVICE"

"""
import numpy as np


class MakeSinStream():
    """Generate sinusoidal numpy array for sounddevice lib"""
    def __init__(self, frame=256, samplerate =48000, amplitude=1, frequency=100, offset=0):
        ############# import variable ######################
        self.FRAME = frame              # buffer of your sound card
        self.SAMPLERATE = samplerate    # sampling rate of your sound card
        self.AMPLITUDE = amplitude      # Amplitude of sinus
        self.FREQUENCY =  frequency     # frequency out - only int as this time.
        self.OFFSET  = offset           # offset is included on -1 to 1, not use yet
        
        self.lastSinPosition = 0        # last position n-1 of sinus
        self.bufferOutReady = False
       
        """
        Eng : Creation reference sinusoidal numpy array, samplerate size, start 0, end 2pi so , frequency is 1Hz
        for 100Hz output, take a value every 100 step.
        Fr : Création d'une table sinusoidale de reference de la taille de l'enchantillonage (SAMPLERATE) de 0 à 2pi (donc 1Hz)
        pour 100 Hz en sortie, prendre une valeur dans le tableau par pas de 100.
        expression is : sin(2*pi*(table de 0 to samplerate)* samplerate)
        
        """
        self.refTableSin = self.AMPLITUDE*(np.sin(2*np.pi*np.arange(0,self.SAMPLERATE, dtype='float32' )/self.SAMPLERATE ))     # sinus 1Hz 0 to 2Pi
        self.tableBuffer = np.zeros(self.FRAME, dtype='float32')        # Buffer table, Sinus as good frequency
        self.tableMasque = np.arange(0, self.FRAME, 1, dtype='int32')   # Step masque table
        self.outStereo = np.concatenate((self.tableBuffer.reshape(self.FRAME,1),self.tableBuffer.reshape(self.FRAME,1)),
                                        axis =1)  #Init variable, Stereo sinus array

        
        
    def generationSinus(self):
        """group two mono buffer in stereo stream.
        regroupement des deux buffer mono en signal stereo
        """
        if self.bufferOutReady == False:
            
            self.bufferTableSinus()  #fill the buffer with sinus as good frequency
            frameChannel1 = self.tableBuffer
            frameChannel2 = self.tableBuffer
            # mix two mono channel in stereo
            self.outStereo =  np.concatenate((frameChannel1.reshape(self.FRAME,1),frameChannel2.reshape(self.FRAME,1)),
                                             axis =1 )  # Format C_CONTIGUOUS valid.
            self.bufferOutReady = True
            return self.outStereo
        else :
            return None
    
    
    def bufferTableSinus(self):
        """rolling sinus table in buffer audio
        roulement de la table sinus dans le buffer audio
        """
        ## 1er step : mask creation
        for i in range(0,self.FRAME):
            j = int(self.FREQUENCY + self.lastSinPosition)
            if j < self.SAMPLERATE :
                self.tableMasque[i:] = int(self.FREQUENCY + self.lastSinPosition)
                self.lastSinPosition = self.tableMasque[i]
            else :
                
                self.tableMasque[i:] = int(j-self.SAMPLERATE)
                self.lastSinPosition = self.tableMasque[i]
        ## 2em step : mask on sinus reference table       
        for i in range(0,self.FRAME):
            self.tableBuffer[i:] = self.refTableSin[self.tableMasque[i]]
        return

    def stream(self):
        """return stereo numpy sinus array"""
        buffer = self.outStereo       
        self.bufferOutReady = False
        self.generationSinus()
        return buffer


if __name__ == '__main__':
    import sounddevice as sd
    ######### CONFIGURATION #########
    duration = 10 # <= time in second.
    TONE = 100  # <= Output Frequency in Hz    
    
    ### Sounddevice Configuration ###
    SAMPLERATE=48000
    BLOCKSIZE = 1024
    DEVICE =[1,3]  # [IN, OUT]      <= Configure your device !
    CHANNEL=2
    DTYPE = "float32"   # use only "float32"
    ##### Mapping audio port  #####
    # Information :
    print("information sur portaudio", sd.get_portaudio_version())
    print(sd.query_devices())
    print("in/out par defaut", sd.default.device)
    
    # init Stream Module
    streamAudio = MakeSinStream(frame=BLOCKSIZE, samplerate =SAMPLERATE, amplitude=1, frequency=TONE, offset=0) #fonction to generate realtime sinus
    
    ######## callback sounddevice fonction ######
    def callback(outdata, frames,time, status):

        if status: #si status => overflow, exit
            print(status)
        
        else:
            outdata[:] = streamAudio.stream()
            
    ########## init sounddevice   ###############
    try :
        inputData = sd.OutputStream(samplerate=SAMPLERATE, blocksize=BLOCKSIZE, device=DEVICE, 
                                        channels=CHANNEL, dtype=DTYPE, latency='low', extra_settings=None,
                                        callback=callback, finished_callback=None, clip_off=None, dither_off=None,
                                        never_drop_input=None, prime_output_buffers_using_stream_callback=None)
        print(inputData._device)
            
    except Exception as the_error:
        import sys
        print("type error: "+ str(the_error))
        sys.exit()
    #################################################
    
    with inputData:
        sd.sleep(int(duration * 1000))
`

**Comment by mgeier** [comment]
I've created a little example that plays a sine signal: #193.

What do you think about it?

**Comment by cool-RR** [comment]
@mgeier This is good, thank you! 

To be honest, something much simpler would have been better, at least for me. The point for me was to have a copy-pasteable example of the simplest kind of sound generation, which I can then modify and add stuff to until it does what I want. (I already figured out how to use sounddevice.) Both the notebooks and the new script you added have so much more information, but for this use case I would have preferred more of an "hello world", a 10-line script that just makes a sound, without any command line arguments or long explanations.

In any case, thank you for working on my issue and adding this script.

**Comment by mgeier** [comment]
@cool-RR Thanks for the feedback!

> To be honest, something much simpler would have been better, at least for me.

I tried to make it simple. If you have concrete suggestions for making the example simpler, please tell me!

The problem is: I want those examples to actually work. And for some people the default device cannot be used, so there has to be a way to select a different device. And the argument parsing is a *somewhat* simple way to get this.
