### ISSUE TITLE
Python import sounddevice as sd (ImportError: No module name sounddevice)

### ISSUE THREAD

**Issue by Tondy** [spatialaudio/python-sounddevice#19]
I have python code that is running on raspberry pi B++ that uses the sounddevice library that lets you play and record sounds with python. I have successfully installed the modules. I can confirm through the python command line and enter import sounddevice as sd is works without errors. I have also confirmed by typing `help ('modules')` in python command line and sounddevice module appears. Only when I am running this code in an independent python program does the `ImportError: No module name sounddevice` appear.

Hope some one can help.

Here is the included code:

```python
import sounddevice as sd
```

The error:

    ImportError: No module name sounddevice

**Comment by mgeier** [comment]
Do you have different Python versions installed?

If yes, you have to install the module on each of them.

Or probably your "independent python program" uses a virtual environment?

**Comment by GarrettHartley** [comment]
$ pip freeze
cffi==1.5.2
Pillow==3.1.1
PyAudio==0.2.9
pycparser==2.14
sounddevice==0.3.2

I show all of the above modules installed, using pip freeze, but I still get this same error 

import sounddevice as sd
The error:
ImportError: No module name sounddevice

**Comment by Tondy** [comment]
Hello I solved the problem by removing --user when installing with pip. So the install command will be pip install sounddevice without --user.

**Comment by mgeier** [comment]
@Tondy That's strange, it should work with the `--user` option.

Did you install the library with the same user account as you are using it later?
Did you happen to use `sudo` in any of the commands?

The reason for the `--user` option is that you don't need `sudo` (or the `root` password) at all.

@GarrettHartley note that you may have different versions of `pip` installed. You may also have `pip3` or `pip-3.5` or similar.

To make sure to use the correct Python version for pip-installing, you can also use:

    python3 -m pip install sounddevice

**Comment by GarrettHartley** [comment]
I got it to work by including '#!/usr/bin/env python3' at the top of my file. Sorry this was sorta a silly issue.

**Comment by mgeier** [comment]
@GarrettHartley No problem, I know it can be confusing to handle those different versions. I'm glad that it works now for you.

@Tondy Any news from your side?

**Comment by saranya2611** [comment]
Thank you mgeier....!!! Your solution cracked the error finally...!
