### ISSUE TITLE
[error] Runtime Error in pa_win_wdmks.c

### ISSUE THREAD

**Issue by zzxjl1** [spatialaudio/python-sounddevice#190]
PS C:\Users\z> python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sounddevice
Assertion failed!

Program: C:\Users\z\AppData\Local\Programs\Python\Python36\python.exe
File: src/hostapi/wdmks/pa_win_wdmks.c, Line 1081

Expression: FALSE

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by mgeier** [comment]
This looks like the same error as in #7.

**Comment by zzxjl1** [comment]
https://github.com/adfernandes/precompiled-portaudio-windows 
this woks for me
