### ISSUE TITLE
wait() not working on short sound-files

### ISSUE THREAD

**Issue by Rackor** [spatialaudio/python-sounddevice#191]
I experienced the bug, that when im using play() and wait() with a short .wav file, like a single beep (~under 1 sec), the program stops without any sound, but its working great if im using something longer, like 6 secs.
If i am adding a short time.sleep statement between play and wait, like 0.5 sec, it works with the short beep, too.

**Comment by mgeier** [comment]
Thanks for the report!

Please provide a link to an example file (or several) as well as a minimal (but working) code example that shows the problem.

Please also mention your OS, host API, and other such things.

**Comment by mgeier** [comment]
Closing due to lack of response.
