### ISSUE TITLE
Playing a file to two or more devices at once

### ISSUE THREAD

**Issue by JoJolM** [spatialaudio/python-sounddevice#192]
Hi 
I'm using this library for a project and I'm currently trying to play a file to two connected devices. I tried threading but the sound would still play on the first device and then on the other one, I also tried launching two instances of the play method with the blocking set to false. I wanted to know if it is possible to play to more than one device at a time a file and if it is how would you do it and execute the functions in a rapid succession.
I thank any of you who'll help me and btw the library works very well

**Comment by mgeier** [comment]
The `play()` function is meant for single use, typically in an interactive Python session. Whenever you call `play()` a second time, the playback from a previous invocation will be stopped.

In your case, you should use one of the "stream" classes. If you need only output, your choice should probably be `OutputStream`.

It should be possible to create two instances of `OutputStream`, each one using a different `device` setting. But I've never actually tried this. If it doesn't work for you, please let me know.

Depending on your operating system and on your devices, you might also be able to combine the devices into a single "virtual" device, which might be easier to use with the `sounddevice` module.

**Comment by xumengfei** [comment]
> The `play()` function is meant for single use, typically in an interactive Python session. Whenever you call `play()` a second time, the playback from a previous invocation will be stopped.
> 
> In your case, you should use one of the "stream" classes. If you need only output, your choice should probably be `OutputStream`.
> 
> It should be possible to create two instances of `OutputStream`, each one using a different `device` setting. But I've never actually tried this. If it doesn't work for you, please let me know.
> 
> Depending on your operating system and on your devices, you might also be able to combine the devices into a single "virtual" device, which might be easier to use with the `sounddevice` module.

I implemented the simultaneous output of two sounds to two different devices, each playing as a  threading.
What should I do to be able to pause and resume playing each stream during playback?

`from tkinter import*
import sounddevice
import threading
import soundfile

DATA_TYPE = "int16"

class myThread(threading.Thread):
    def __init__(self, args):
        threading.Thread.__init__(self)        
        self.args=args        
    def run(self):
        playmp3(self.args)
        
class streamData:
    def __init__(self, index):
        self.outstream = create_running_output_stream(index)
        
class musicData:
    def __init__(self, path):
        self.music = load_sound_file_into_memory(path)

def load_sound_file_into_memory(path): 
    audio_data, _ = soundfile.read(path, dtype=DATA_TYPE)
    return audio_data

def get_device_number_if_usb_soundcard(index_info): 
    index, info = index_info 
    if "扬声器" in info["name"] and info["hostapi"]==3:
        return index
    return False
    
def create_running_output_stream(index): 
    output = sounddevice.RawOutputStream(
        device=index,
        dtype=DATA_TYPE
    )
    return output

sound_card_indices = list(filter(lambda x: x is not False,
                                         map(get_device_number_if_usb_soundcard,
                                             [index_info for index_info in enumerate(sounddevice.query_devices())])))

song1 = musicData("E:\\multi.audio\\111.wav")
song2 = musicData("E:\\multi.audio\\123.wav")
stream1 = streamData(sound_card_indices[0])
stream2 = streamData(sound_card_indices[1])

def playmp3(args):
    if args==1:
        stream1.outstream.write(song1.music)
    else:
        stream2.outstream.write(song2.music)

def play1():
    global thread1
    thread1 = myThread(1)
    stream1.outstream.start()
    thread1.start()
    
def play2():
    global thread2
    thread2 = myThread(2)
    stream2.outstream.start()
    thread2.start()
    
def stop1():
    stream1.outstream.stop()
    print(thread1.isAlive())
    
def stop2():
    stream2.outstream.stop()
    print(thread2.isAlive())

myWindow = Tk()

myWindow.title('Python MP3 player')
Label(myWindow, text="").grid(row=0)
Label(myWindow, text="").grid(row=1)
Label(myWindow, text="").grid(row=2,column=0,sticky=W, padx=15, pady=15)
Button(myWindow, text='wav.1', command=play1).grid(row=2, column=1,sticky=W, padx=5, pady=5)
Label(myWindow, text="").grid(row=2,column=2,sticky=W, padx=15, pady=15)
Button(myWindow, text='wav.2', command=play2).grid(row=2, column=3, sticky=W, padx=5, pady=5)
Label(myWindow, text="").grid(row=2,column=4,sticky=W, padx=15, pady=15)
Label(myWindow, text="").grid(row=3)
Label(myWindow, text="").grid(row=4,column=0,sticky=W, padx=15, pady=15)
Button(myWindow, text='stop', command=stop1).grid(row=4, column=1,sticky=W, padx=5, pady=5)
Label(myWindow, text="").grid(row=4,column=2,sticky=W, padx=15, pady=15)
Button(myWindow, text='stop', command=stop2).grid(row=4, column=3, sticky=W, padx=5, pady=5)
Label(myWindow, text="").grid(row=4,column=4,sticky=W, padx=15, pady=15)

myWindow.mainloop()
`

**Comment by mgeier** [comment]
> What should I do to be able to pause and resume playing each stream during playback?

I would try to play the files in a block-by-block fashion (instead of all-at-once). Then you can implement some logic for pausing and resuming between blocks.
You might want to use fade outs and fade ins to avoid artifacts.

See [examples/play_long_file.py](../blob/master/examples/play_long_file.py) for one possibility to handle file playback.

While "paused", the callback function should simply fill the output buffer with zeros.

You could of course also use the "blocking" API (i.e. `outstream.write()`) if you prefer that for some reason.

**Comment by xumengfei** [comment]
**While "paused", the callback function should simply fill the output buffer with zeros.**

Thank you very much!

**Comment by JoJolM** [comment]
thank you all for your answers this greatly helped me

**Comment by Sameer-hesta** [comment]
Can I stream my system sound on both devices instead of a single file?
If yes please let me know how can I do this.

**Comment by HaHeho** [comment]
No, you will need the help of a "virtual sound card" to capture and route the sound from other application. What application might be available depends on the OS.

**Comment by Sameer-hesta** [comment]
Thank you for your response,
Can we stream input audio on both devices at the same time?

**Comment by HaHeho** [comment]
Yes, that should be possible. You probably don't need to implement threads but only
1 `InputStream` -> 1 `Queue` -> 2 `OutputStream` (instead of a `SoundFile` e.g. in [rec_unlimited.py](https://github.com/spatialaudio/python-sounddevice/blob/master/examples/rec_unlimited.py)).

Of course, you need to be careful to prevent acoustic feedback from the output back into the input.

**Comment by Sameer-hesta** [comment]
If I don't use threads then how can I stream it on multiple devices?

**Comment by Sameer-hesta** [comment]
> You probably don't need to implement threads


If I don't use threads then how can I stream it on multiple devices?

**Comment by HaHeho** [comment]
> If I don't use threads then how can I stream it on multiple devices?

Hm, maybe you do. But shouldn't something like this, with the respective implementation of the callback functions to fill 2 (!) queues, work?
```python
in = sd.InputStream(samplerate=samplerate, device=dev_in,
                    channels=channels, callback=callback_in)
out1 = sd.OutputStream(samplerate=samplerate, device=dev_out1,
                       channels=channels, callback=callback_out1)
out2 = sd.OutputStream(samplerate=samplerate, device=dev_out2,
                       channels=channels, callback=callback_out2)

try:
    with in, out1, out2:
        print('press Ctrl+C to stop')
        while True:
            pass
except KeyboardInterrupt:
    print('\nInterrupted by user')
    exit(0)
```

Not sure if that is the best way. Maybe that blocking loop should also be just an `event.wait()` (that will never be reached bot only interrupted) or something.
