### ISSUE TITLE
Feature request: Provide a way to play sound from a function

### ISSUE THREAD

**Issue by cool-RR** [spatialaudio/python-sounddevice#194]
I think that a popular pattern with sounddevice is to create an array from a function (like sine, or a complicated sum of sines) and then play that array. Then, if you want to play the sound before building the array is finished, you have to use sounddevice's stream API, which in my opinion is a bit complicated.

Here's a cool idea: Let me run code like this: 

```
def f(x):
    return a * sin(b * x)

sounddevice.play_function(f, sample_rate=10_000, length=60)
```

Instead of me creating an array, sounddevice will just automatically use the stream API based on the function.

It's also possible to make the length change dynamically, in case you don't want to decide in advance what the length will be.

**Comment by mgeier** [comment]
Thanks for the suggestion!

I'm not sure if it's worth adding such a functionality.

You can easily try out your function `f()` like this (untested):

```python
import numpy as np
import sounddevice as sd

fs = 48000
sd.default.samplerate = fs

t = np.arange(2 * fs) / fs

sd.play(f(t))

# If the script ends here:
sd.wait()
```

You really just need one additional line, the one that defines `t`.
And it is even more flexible, because you can decide if the `x` in your function is the time in seconds or in frames.

**Comment by cool-RR** [comment]
A couple of thoughts:

1. Would your example work given that f is a function that takes a number, not a numpy array?

2. What if the duration is long, and it takes a while to calculate? If the package took a function, it could automatically figure out calculating the array on demand instead of in advance.

**Comment by mgeier** [comment]
> Would your example work given that f is a function that takes a number, not a numpy array?

No, but your example wouldn't work with both, either!
This illustrates how hard it is to come up with a good API for `sounddevice.play_function()`. It's much easier to just implement it in user code.

BTW, You should generally try to write functions that work on NumPy arrays. That's often much more efficient, and often it's also easier to read (at least more concise).

You can use [numpy.vectorize()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html) to turn a "normal" function into one that acts on arrays, but note that this is typically slow!

> What if the duration is long, and it takes a while to calculate? If the package took a function, it could automatically figure out calculating the array on demand instead of in advance.

I think this case is very rare. If you want to run a function that is so CPU intensive, maybe Python isn't the right choice in the first place?

And if you really need that, you can easily create a callback function, it's only a few lines of code. I've added an example for that in #193.

**Comment by cool-RR** [comment]
Thanks @mgeier .
