### ISSUE TITLE
silent record audio on mac os

### ISSUE THREAD

**Issue by tsungruihon** [spatialaudio/python-sounddevice#196]
I try to use `sounddevice` to record. But the output record audio is just silent on mac os.

It would be very grateful if someone could give me a hint. Thanks a lot.

**Comment by mgeier** [comment]
Would you mind providing a bit more information?

**Comment by esap120** [comment]
Having a similar issue, the numpy array coming back from using the `sounddevice.rec` function returns a numpy array that contains all 0s. I am also using Mac OS mojave so could be related? I have confirmed that I can record via quicktime so the mic does not seem to be the issue.

Similar question asked here: https://stackoverflow.com/questions/53717870/unable-to-record-sound-with-sounddevice

**Comment by tsungruihon** [comment]
I use pycharm and could record using `pyaudio`.

**Comment by WeberJulian** [comment]
I had a similar problem because vscode's terminal wasn't asking permission from the OS to use the microphone. Once I launched it on a regular terminal and accepted the request, it worked just fine in both terminals. Hope I could help
