### ISSUE TITLE
Why does my tone sound better with lower samplerate

### ISSUE THREAD

**Issue by cool-RR** [spatialaudio/python-sounddevice#198]
Hi guys,

Here is a snippet of code that I wrote that produces a piano-like tone using sounddevice:

```python
import sys
import numbers
import math

import numpy as np
import sounddevice


note_length = 3
frequency = 400
half_life = 0.2
volume = 1

def get_pressure(time: numbers.Rational) -> numbers.Rational:
    overtones = {i: 2 / (i ** 1.3) for i in range(1, 13)}
    if time < 0 or time > note_length:
        return 0
    result = 0
    for overtone, overtone_volume in overtones.items():
        result += overtone_volume * math.sin(
            time * frequency * overtone * (math.pi * 2)
        )
    result *= volume * 2 ** (- time / half_life)
    return result


def play(hz):
    n_frames = int(hz * note_length)

    t = np.linspace(0, note_length, n_frames, False)

    array_1 = np.vectorize(get_pressure)(t)

    # Ensure that highest value is in 16-bit range
    array_2 = array_1 * (2 ** 15 - 1) / np.max(np.abs(array_1)) * 0.5
    # Convert to 16-bit data
    array_2 = array_2.astype(np.int16)

    sounddevice.play(array_2, samplerate=hz)

    sounddevice.wait()


sample_rate = int(sys.argv[1] if len(sys.argv) >= 2 else 8000)
play(sample_rate)
```

I was surprised to learn that when you play it at 8KHz, which is the default, it sounds really life-like, but if you raise it to 16Khz, it sounds too computer-generated. Try it by copying it to a file and running it with the samplerate as the argument, like this: `python foo.py 16000` or `python foo.py 32000` .

Is there something weird here I'm not thinking about that is causing this phenomenon? And if not, and it's just a crazy fluke, how can I preserve this quality of sound even when I'm playing at a higher quality?

**Comment by mgeier** [comment]
That's an interesting exercise you've come up with!

Depending on your knowledge of signal processing this can have a quick answer, or it might need some longer explanations ...

Are you aware of the sampling theorem (a.k.a. Shannon's law or something like that)?

Did you have a look at the frequency values of your partial tones?

> it sounds really life-like

Are you listening to the sound on laptop loudspeakers?

If I listen to it on laptop loudspeakers, it sounds surprisingly nice, but when I listen to it with headphones, not so much anymore.

**Comment by cool-RR** [comment]
> That's an interesting exercise you've come up with!

Thanks Matthias! I'm planning a cool project with sounddevice, but I won't reveal it yet, because I'm not sure I'll have the time to finish it :)

> Are you listening to the sound on laptop loudspeakers? If I listen to it on laptop loudspeakers, it sounds surprisingly nice, but when I listen to it with headphones, not so much anymore.

No, I listened with high-quality speakers and it sounded good to me. I tried to connect my USB headphones to listen but that resulted in #199 .

> Are you aware of the sampling theorem (a.k.a. Shannon's law or something like that)?

I googled it now and oh boy :D why does math have to show up every time to ruin the party. So the answer is no.

> Did you have a look at the frequency values of your partial tones?

Well, I know that they are integer multiples of the base frequency, so 2x, 3x, 4x, 5x etc. Not sure what I should do with that information.

**Comment by mgeier** [comment]
OK, so let me try to give you a very short and superficial summary:

* The sampling theorem states that sampling only works properly if the sampling frequency is at least twice the value of the highest frequency in the signal. For example, if you use a sampling rate of 8000 Hz, the highest signal frequency should not be higher than 4000 Hz.

* People who make sound cards know the sampling theorem, therefore they include a so-called "anti-aliasing filter" when converting a digital signal to analog. This filter is designed to block all frequencies above half the sampling rate. With a sampling rate of 8000 Hz that means that everything above 4000 Hz is blocked (i.e. filtered out).

* If I'm not mistaken, the frequency values of your example are `[400, 800, 1200, 1600, 2000, 2400, 2800, 3200, 3600, 4000, 4400, 4800]`.

Are you seeing the problem now?

**Comment by cool-RR** [comment]
I'll think about it. Thanks Matthias!

**Comment by mgeier** [comment]
@cool-RR Did you have any insights you want to share here?

**Comment by cool-RR** [comment]
If I remember correctly, a few weeks ago I tried putting 3 waves together with a phase difference, and I think it made the quality a little better when the sample rate is high. But it still didn't solve the problem completely. Honestly I'm pretty much an ignorant when it comes to synthesizing sound, so I don't really know how to solve a problem like that. 

The project that I'm planning is a live-coding talk in which I'll build a synthesizer and have it play MIDI files. It's not finished yet, I hope to finish it soon.

**Comment by mgeier** [comment]
If you are building a synthesizer, you should definitely know about the phenomenon called "aliasing". You should search the interwebs for this or read about it in some book about digital signal processing.

**Comment by cool-RR** [comment]
I'll check it out, thanks!
