### ISSUE TITLE
Split `sounddevice.py` to multiple files

### ISSUE THREAD

**Issue by cool-RR** [spatialaudio/python-sounddevice#206]
I took a glance at `sounddevice.py` to figure out #204. Oh boy, it's quite a big file, at 2781 lines. I suggest breaking it down to a package with around 5-10 files.

**Comment by mgeier** [comment]
Having one big file has advantages and disadvantages.

I'm open to splitting the file, but only if there are good reasons, other than being larger than an arbitrary threshold.

**Comment by cool-RR** [comment]
I agree that there are advantages to having everything in one file. I find it more convenient to find the different parts of the code (streams, convenience functions, utility functions) if they are broken down to different files. But it's a matter of taste, and since you do most of the work on this code, it'll make sense to keep it this way.
