### ISSUE TITLE
Recording and processing audio that gets played by the speakers

### ISSUE THREAD

**Issue by ziebam** [spatialaudio/python-sounddevice#210]
Hi!

I'd like to ask if it's possible to record/listen to the audio output (like Spotify music playing in the background) and then analyze/process it somehow? So far I've only succeeded in recording audio from the input device (i.e. the microphone) and I'm struggling to find a way to make it work how I want it.

**Comment by mgeier** [comment]
Just repeating my recent comment from https://stackoverflow.com/q/58780206/:

> The `sounddevice` module can only record what the underlying [PortAudio](http://portaudio.com/) library provides as "input devices". To record the output of some other application(s), you would need to turn it into a usable input device, which cannot be done with the `sounddevice` module and PortAudio. Depending on your operating system there may be ways to do this [...]

**Comment by ziebam** [comment]
I see. Thanks for the reply! I'm closing the issue.
