### ISSUE TITLE
Mention in readme and docs main page that sounddevice is cross-OS

### ISSUE THREAD

**Issue by cool-RR** [spatialaudio/python-sounddevice#211]
Many people who's use sounddevice are not familiar with PortAudio, and might not understand whether sounddevice is Windows-only or what. Mentioning that it works on Windows, Mac and Linux would be helpful, both on the readme and the main page of the docs.

**Comment by mgeier** [comment]
That sounds like a good idea!

Would you like to make a PR?

> both on the readme and the main page of the docs

The `README.rst` is automatically included in the main page, so it should be sufficient to only edit `README.rst`.

**Comment by cool-RR** [comment]
I'll pass, not a lot of free time nowadays...

**Comment by raphaelpaiva** [comment]
Do you guys mean something like this [Notice](https://github.com/raphaelpaiva/pywaves/blob/master/README.md#python-version-36) ?

**Comment by mgeier** [comment]
I've made a suggestion in #212, what do you think about it?

@raphaelpaiva I wouldn't want to go into too much detail in the README, but I've documented the somewhat complicated PortAudio situation in https://python-sounddevice.readthedocs.io/installation.html.
