### ISSUE TITLE
Comparison with soundcard

### ISSUE THREAD

**Issue by mpariente** [spatialaudio/python-sounddevice#216]
Thanks a lot for the soft, that looks very nice !

I've been working with `soundcard` until now and I'd just like to know how it compares to it for real-time recording and playback loops. Did you do any comparison? 
Thanks in advance

**Comment by mgeier** [comment]
I guess you mean https://github.com/bastibe/SoundCard?

I don't know, I've never tried it.

Probably someone else who reads those issues? Anyone?

**Comment by mpariente** [comment]
Oh sorry, I figured you used it because you were part of some discussions in soundcard's issues.. 
I'll look into it when I have time then, thanks.

**Comment by mgeier** [comment]
Or are you talking about https://github.com/bastibe/PySoundCard?

Despite the similar name, that's an entirely different thing which I was very much involved in at some point.

The project owner didn't like some of my suggestions though, that's why I had to create the `sounddevice` module instead.

Architecturally, the two modules are extremely similar, I just moved the user-facing API into a different direction.

**Comment by mpariente** [comment]
I was talking about [https://github.com/bastibe/SoundCard](https://github.com/bastibe/SoundCard). 

> Despite the similar name, that's an entirely different thing which I was very much involved in at some point.
>
Yes, one depends on portaudio and the other not. 
Pysoundcard is not maintained anymore because bastibe believes the right way is to interact with the native libraries directly. 
That's why I wondered if a thorough test had been done to compare both approaches.

**Comment by mgeier** [comment]
I like the idea of using platform-native libraries and I would like to hear how well this works in practice.

It would be nice to have examples to play around with.

If you feel like it, you could port some of the `sounddevice` [examples](../blob/master/examples) to `soundcard`?
I guess this would already allow for better comparisons.

**Comment by mpariente** [comment]
I'll see if I get time to do this. It would be the best way to compare for sure. 
I'll close this for now, thanks.
