### ISSUE TITLE
Cannot find a way to send signal to a specific ouput

### ISSUE THREAD

**Issue by fatchild** [spatialaudio/python-sounddevice#218]
I have a Lexicon Omega Audio interface. I have written a small program from examples to send a sinewave to the output through MME. This works. I have had a go at selecting an ASIO output and using the channel_selector argument, but no luck. I get invalid number of channels. Is there a way I am missing to be able to pass an argument that says I want outdata to go to a specific output of the device I am using?

```
import sounddevice as sd
import numpy as np
import scipy.stats as ss
import queue

asio_out = sd.AsioSettings(channel_selectors=[1, 2])

out_q = queue.Queue()

global start_idx
start_idx = 0

def callback(outdata, frames, time, status):

    global start_idx
    t = (start_idx + np.arange(frames)) / 48000
    t = t.reshape(-1, 1)
    sine = 0.9 * np.sin(2 * np.pi * 1000 * t)

    outdata[:] = sine
    out_q.put(sine)

    start_idx += frames

with sd.OutputStream(device=24, samplerate=48000, channels=4, blocksize=4096, callback=callback, extra_settings=asio_out):
    while True:
        pass

```

Thanks in advance.

**Comment by mgeier** [comment]
Just a guess: You have two channels in `channel_selectors=[1, 2]` but four channels in `channels=4`?

**Comment by fatchild** [comment]
Ah yes! So that managed to run, but not to my audio interface!?

My previous output channel which was working was this...
`<  9 Speakers (3- USB Audio Device), MME (0 in, 2 out)`

Would I be able to use a channel map to select a single out from the '2 out'. So then i could send a signal to left channel / right channel depending on the channel map?

**Comment by fatchild** [comment]
`               To actually assign data to the buffer itself, you can use
               indexing, e.g.::

                   outdata[:] = my_data

               ... which fills the whole buffer, or::

                   outdata[:, 1] = my_channel_data

               ... which only fills one channel.`

Using this in the docstring for stream I would imagine that writing data to outdata[:, 1] would send the data to channel 1 and writing data to outdata[:, 2] would go to channel 2.

**Comment by fatchild** [comment]
I have found the solution. I apologise for my inexperience. This could be a good stream of consciousness for those who get stuck in the future. 

To assign a specific output channel within the output device you need to map using the following...
**device**

**Both Channels - as standard:** `outdata[:,** [0, 1]] = data`
**Both Channels - as standard:** `outdata[:,** [0, 1]] = data`

**Comment by mgeier** [comment]
Great that you found the solution yourself!

For the "explicit" case you could also write: `outdata[:, :] = data`, which does the same if `outdata` has 2 channels.

In the "one channel" cases, the inner brackets are not necessary, you can write: `outdata[:, 0] = data`, which I think would be more idiomatic.

**Comment by mgeier** [comment]
I guess this issue is resolved, right?
