### ISSUE TITLE
Playing 2D arrays leads to channel 'bleed' (OS X 10.11.3)

### ISSUE THREAD

**Issue by harenbrs** [spatialaudio/python-sounddevice#22]
First, set up a stereo signal. Here: white noise on the left channel, and a silent right channel.

```python
import sounddevice
import numpy as np

noise = np.random.randn(44100)
silence = np.zeros_like(noise)
signal = np.array(zip(noise, silence))
```

It looks as expected:
```python
>>> signal
array([[-1.31754488,  0.        ],
       [-0.87951546,  0.        ],
       [ 1.09275125,  0.        ],
       ..., 
       [ 0.42013106,  0.        ],
       [ 1.25192917,  0.        ],
       [-1.08305476,  0.        ]])
```

Now, play back this 2D array using `sounddevice.play`.
```python
sounddevice.play(signal)
```

I expect the right channel to be completely silent. However, **it isn't!** A quieter version of the noise on the left channel is being played back on the right channel. The left channel sounds as expected.

The same happens when I switch the channels, and with any `dtype` (I tried `int8`, `float32`, `float64`). Each channel bleeds into the other. It is most easily heard when wearing earphones.

I have of course verified that the balance of my system audio output is centered, and that other audio software (e.g., Audacity) behaves correctly. I have also rebooted. The culprit does seem to be python-sounddevice.

Can anyone confirm that I'm not the only one with this issue? I'm on a late 2013 rMBP 13", running OS X 10.11.3.

**Comment by mgeier** [comment]
This effect is called [crosstalk](https://en.wikipedia.org/wiki/Crosstalk).

Are you sure this is not caused by the hardware?

Did you try to save the abovementioned signal as a sound file and listen to it with a "normal" soundfile player?

You can save it, e.g with the `soundfile` module like this:

```python
import soundfile as sf
sf.write('noise.wav', signal, 44100)
```

How much quieter is the unwanted signal?

**Comment by harenbrs** [comment]
Thanks for your quick response.

When I write the signal to file as you suggest, the plot thickens. Audacity sees a correct, silent right channel, and plays it back as expected. **When Quick Looking the wave file in Finder, however, the crosstalk reappears.** So whatever is messed up on my system (PortAudio?) is not limited to python-sounddevice. Certainly this issue may be closed then!

Would you have any further ideas for troubleshooting this, though? A hardware issue seems unlikely, since it happens both with the internal and an external sound interface, and given the fact that Audacity is not affected. Might reinstalling portaudio help?

**Comment by mgeier** [comment]
AFAIK, Audacity also uses PortAudio, so this is really strange ...
They might use different versions, though.

I would check how your audio devices are recognized by PortAudio. You can try this to get a list of devices:

    python3 -m sounddevice

If there are multiple choices for an output device, you can try them like that (using the device numbers from the list):

```python
sounddevice.play(signal, device=0)
```

You could try the same with Audacity, where you should be able to switch the output device somewhere in the settings.
