### ISSUE TITLE
Example live plotting not working

### ISSUE THREAD

**Issue by DominikRoB** [spatialaudio/python-sounddevice#224]
Hey,
when I tried the live input plotting example, the code runs for 1-2 seconds, then plots a zero-line graph once, and then finishes the program.
I am using Python 3.6.10 and run the script in PyCharm with default arguments.

In comparison, the text-mode spectogram runs as expected. Edit: Works expected in showing the spectogram - the While loop within the Input-Stream is only executed once for me, as well

**Comment by mgeier** [comment]
I have no experience with PyCharm.

Have you tried running the script(s) on a "normal" terminal?

    python3 examples/plot_input.py

**Comment by DominikRoB** [comment]
I should have realized that myself..
In the system terminal it works fine and after setting the configuration in PyCharm to execute with the Python console (Which I thought was already the case, thus the stupid question), it's working there as well.

Thank you - I'll go ahead and close the issue.
