### ISSUE TITLE
Win10: AttributeError: partially initialized module 'sounddevice' has no attribute 'rec'

### ISSUE THREAD

**Issue by LenStruttmann** [spatialaudio/python-sounddevice#225]
I seem to be have trouble using sounddevice on Win10:

D:\SDRSharp\Recordings>pip3 list
Package         Version
--------------- --------
BitVector       3.4.9
cycler          0.10.0
kiwisolver      1.1.0
matplotlib      3.1.2
numpy           1.18.1
opencv-python   4.2.0.32
pandas          0.25.3
pip             20.0.2
pyparsing       2.4.6
python-dateutil 2.8.1
pytz            2019.3
scipy           1.4.1
setuptools      41.2.0
six             1.14.0

D:\SDRSharp\Recordings>pip3 install sounddevice-0.3.14-cp38-cp38-win_amd64.whl --no-cache-dir
Processing d:\sdrsharp\recordings\sounddevice-0.3.14-cp38-cp38-win_amd64.whl
Collecting CFFI>=1.0
  Downloading cffi-1.14.0-cp38-cp38-win_amd64.whl (177 kB)
     |████████████████████████████████| 177 kB 656 kB/s
Collecting pycparser
  Downloading pycparser-2.19.tar.gz (158 kB)
     |████████████████████████████████| 158 kB 3.3 MB/s
Installing collected packages: pycparser, CFFI, sounddevice
    Running setup.py install for pycparser ... done
Successfully installed CFFI-1.14.0 pycparser-2.19 sounddevice-0.3.14

D:\SDRSharp\Recordings>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sounddevice as sd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\SDRSharp\Recordings\sounddevice.py", line 7, in <module>
    myrecording = sd.rec(duration * fs, samplerate=fs, channels=2, dtype='float64')
AttributeError: partially initialized module 'sounddevice' has no attribute 'rec' (most likely due to a circular import)

**Comment by mgeier** [comment]
The problem might be that you named your script `sounddevice.py`?

This way it is shadowing the `sounddevice` module.

Can you try re-naming your script?

**Comment by LenStruttmann** [comment]
Gaa! That was it. Sorry about that simple mistake that I should have
caught.

 -------Original Message-------
