### ISSUE TITLE
Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME error 1]

### ISSUE THREAD

**Issue by tigershan1130** [spatialaudio/python-sounddevice#233]
`
import sounddevice as sd

if __name__ == '__main__':
    duration = 2
    print(sd.query_devices())

    #sd.default.device[0] = 6
    sd.default.channels = 2

    print("start recording..")
    print(sd.default.device)
    print(sd.default.channels)
    print(sd.default.extra_settings)
    mydata = sd.rec(int(16000 * duration), blocking=True)
    print("end recording...")
   
    sd.wait()
    sd.play(mydata)`

 Below is my audio input and output 
 Input>  1 Microphone (Realtek(R) Audio), MME (2 in, 0 out)
 output<  4 Speakers/Headphones (Realtek(R), MME (0 in, 2 out)
I had very simple code to run on my laptop trying to use my laptop's default realtek audio recording...

**Comment by mgeier** [comment]
Did you try other host APIs, e.g. WASAPI?

**Comment by tigershan1130** [comment]
Solved, for some reason refresh windows->privacy->microphone settings and running python as administrator allow app to be popped up with permission of anti-virus software notice.

**Comment by ileben** [comment]
@tigershan1130 could you please elaborate on your solution? I've ran into the same issue, but I don't understand what you mean by "refresh windows->privacy->microphone settings".

**Comment by ileben** [comment]
That is what I had to do to resolve the issue - running as administrator was not required, and there was seemingly no anti-virus interaction.
![image](https://user-images.githubusercontent.com/370626/101123969-1bfd5880-364a-11eb-9190-ed8d13c5a65b.png)
