### ISSUE TITLE
Record audio with any duration. 

### ISSUE THREAD

**Issue by rodrigomaia17** [spatialaudio/python-sounddevice#24]
Hi, I am trying to create a 'loop pedal' emulator, and I need to start recording audio without a duration already specified. Something like 'record audio until I want'. I dont know how to do that in sounddevice. Is this possible?

**Comment by mgeier** [comment]
This is certainly possible but you'll have to implement it yourself using the callback API.

The reason why `sounddevice.rec()` uses a pre-defined duration, is to be able to allocate all necessary memory in one big NumPy array beforehand.

You could extend that to arbitrary durations by appending to a `list` of audio blocks in each callback.
Once you have enough, you can `stop()` (or `abort()`) the stream and afterwards join your list of audio blocks into a big NumPy array (if needed).

Note that allocating memory within the time-constrained callback may take too long, which may lead to drop-outs in your recording. You should be able to detect those with the `status` argument of your callback function. As long as `status` doesn't contain any error bits, you should be fine.

**Comment by mgeier** [comment]
I've created an example showing how to record for an arbitrary amount of time: [rec_unlimited.py](https://github.com/spatialaudio/python-sounddevice/blob/master/examples/rec_unlimited.py).

Does this help?

**Comment by rodrigomaia17** [comment]
Helps A LOT! thank you so much. I will experiment a little bit and try to do my 'loop pedal emulator'. this is extremely helpful. This module is awesome.

**Comment by Pranav578** [comment]
Dude you gave me the exact thing which i needed, thanks

**Comment by egzon-korenica** [comment]
> I've created an example showing how to record for an arbitrary amount of time: [rec_unlimited.py](https://github.com/spatialaudio/python-sounddevice/blob/master/examples/rec_unlimited.py).
> 
> Does this help?

This code is amazing, I was wondering though, is it possible to do multiple recordings in one session? I mean when you click ctrl+c the whole program shuts down.

**Comment by HaHeho** [comment]
> This code is amazing, I was wondering though, is it possible to do multiple recordings in one session? I mean when you click ctrl+c the whole program shuts down.

I mean, that is what the code does. There is nothing happening after catching the `KeyboardInterrupt`. You can modify that of course, like adding similar code afterwards or putting it inside a loop.
