### ISSUE TITLE
Docs say NumPy is optional, but I can't play anything without it

### ISSUE THREAD

**Issue by januryga** [spatialaudio/python-sounddevice#25]
The docs say 

> NumPy is only needed if you want to play back and record NumPy arrays. 

However, when I try playing a normal python bytes object, the program errors with

> ImportError: NumPy must be installed for play()/rec()/playrec().

Is there something I'm missing here? I hope so, because I really like the high-level interface instead of manually wrangling streams with PyAudio. But if the basic functionality isn't available without NumPy, maybe you should make it more explicit in the docs?

**Comment by mgeier** [comment]
Thanks for the issue.

You are right, it wasn't clear from the docs that play()/rec()/playrec() only work on NumPy arrays. I've made this more explicit in c8b72b905c3696948618177799756c0ff40cbd59 ([updated docs](http://python-sounddevice.readthedocs.io/en/latest/index.html#sounddevice.play)). I hope it is clear now?

As for playing plain Python buffers:

I'm just curious, what's the reason you cannot use NumPy?

Not having NumPy, you could try:

```python
with sd.RawOutputStream(channels=..., dtype=...) as stream:
    stream.write(mybuffer)
```

You can easily put this into a function for your own use, but I don't think it makes sense to include that as part of the `sounddevice` module. Recording should be similarly simple.
Implementing `playrec()` for plain buffer objects will be a bit more involved, but I don't think there is popular demand for that anyway, right?

**Comment by mgeier** [comment]
@januryga What about the updated docs?
Do you want me to change anything else?

**Comment by januryga** [comment]
Yeah, it's good now.
