### ISSUE TITLE
Mac Mic Stream only giving indata as 0's

### ISSUE THREAD

**Issue by vineyugave** [spatialaudio/python-sounddevice#267]
I am using a streamer like this 

``` 
self.audio_streamer = sd.Stream(device=self.input_device, channels=self.channels,
                                        samplerate=self.sampling_rate, dtype='int16',
                                        callback=self.update_audio_feed, blocksize=self.audio_block_size,
                                        latency='low')



def update_audio_feed(self, indata, outdata, frames, time, status):
        print("update_audio_feed")
        if status:
            print(status, file=sys.stderr)

        print(indata)
        outdata.fill(0)


Output :

The indata is an array with 0's always from the callback.
update_audio_feed
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]

Sounddevice is detectingt the mic fine but not getting the signal :
Device Info: {'name': 'MacBook Pro Microphone', 'hostapi': 0, 'max_input_channels': 1, 'max_output_channels': 0, 'default_low_input_latency': 0.04852607709750567, 'default_low_output_latency': 0.01, 'default_high_input_latency': 0.05868480725623583, 'default_high_output_latency': 0.1, 'default_samplerate': 44100.0}
Sampling rate: 44100.0 
```

Any ideas what is going on ? I checked that PortAudio is installed fine ..

**Comment by mgeier** [comment]
I'm not a macOS user myself, but I've heard about problems with the microphone permissions on macOS.

Maybe this helps: https://www.reddit.com/r/MacOS/comments/9lwyz0/mojave_not_privacy_settings_blocking_all_mic/

**Comment by mgeier** [comment]
Same question on SO: https://stackoverflow.com/q/63109391/

**Comment by mattgwwalker** [comment]
Hi,

I'm no expert, but I've been using sounddevice without major issues on a number of Macs for a few months now, and I've not touched anything to do with permissions in my code (my users have however clicked "yes" when asked on, for example, OSX10.15).

Firstly, have you tried the [`wire.py`](https://python-sounddevice.readthedocs.io/en/0.4.0/examples.html#input-to-output-pass-through) example?  That works out of the box for me.

Two things that I noticed in your code:

- I haven't tried specifying the blocksize.  I have only used the default value of 0.  I could well believe that may be causing you issues.
- You've specified a "low" latency Stream.  At the very least on OSX10.13 this produces very unstable audio (lots of input underflows).  If stable audio is important to you, I would recommend you consider latency options higher than "high".  For reference, Audacity uses 100ms and obtains stable audio.

Hope that helps,

Matthew

**Comment by mattgwwalker** [comment]
(Oh, and input underflows often produce input with all zeros.)

**Comment by mattgwwalker** [comment]
@vineyugave I think I may just have reproduced the same issue as you had.

I have not had a problem at all with sounddevice until I attempted to code-sign my application.  Now, on Catalina (OSX 10.15.6), I too am getting nothing from the microphone.  The code works fine on OSX10.13.6, but even after adding the `com.apple.security.device.microphone` entitlement, I am not getting anything from the mic.

Is this the same scenario as you were having?  Did you find a solution?

**Comment by mattgwwalker** [comment]
However, I was able to get the microphone to work when I gave my app the `com.apple.security.device.audio-input` entitlement.  I haven't yet tried it in the Sandbox.

**Comment by vineyugave** [comment]
Issue on my Mac was a permission / security issue .. when I ran the python script throught Visual Studio Code console it did not work .. But when I ran it through mac Terminal it prompted for mic access and it started working ..
