### ISSUE TITLE
Bluetooth headphones not showing in sd.query_devices()

### ISSUE THREAD

**Issue by MrHoseongLee** [spatialaudio/python-sounddevice#273]
I'm running python3.8 on arch linux. When I use `sd.play()` it plays the audio to the built-in speaker. To change the device used `sd.query_devices()` but the output is 
```
   0 HDA Intel PCH: ALC3266 Analog (hw:0,0), ALSA (2 in, 2 out)
   1 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
   2 HDA Intel PCH: HDMI 1 (hw:0,7), ALSA (0 in, 8 out)
   3 HDA Intel PCH: HDMI 2 (hw:0,8), ALSA (0 in, 8 out)
   4 HDA Intel PCH: HDMI 3 (hw:0,9), ALSA (0 in, 8 out)
   5 HDA Intel PCH: HDMI 4 (hw:0,10), ALSA (0 in, 8 out)
   6 sysdefault, ALSA (128 in, 128 out)
   7 front, ALSA (0 in, 2 out)
   8 surround40, ALSA (0 in, 2 out)
   9 surround51, ALSA (0 in, 2 out)
  10 surround71, ALSA (0 in, 2 out)
  11 hdmi, ALSA (0 in, 8 out)
* 12 default, ALSA (128 in, 128 out)
  13 dmix, ALSA (0 in, 2 out)
```
From my understanding none of these is the Bluetooth headphone connect to my laptop. How can I get sounddevice to detect my bluetooth headphones?

**Comment by MrHoseongLee** [comment]
Tinkering with the bluez-alsa package and installing pulseaudio-alsa solved this issue!

**Comment by ApplicationNinja** [comment]
> Tinkering with the bluez-alsa package and installing pulseaudio-alsa solved this issue!

I'm having the same issue, what tinkering did you do to get all this to work?

**Comment by HaHeho** [comment]
@ApplicationNinja see https://github.com/spatialaudio/python-sounddevice/issues/343#issuecomment-875038235. Maybe that helps.
