### ISSUE TITLE
Help: record sound volume is much lower than using linux 'arecord' command

### ISSUE THREAD

**Issue by hyansuper** [spatialaudio/python-sounddevice#291]
I am using raspberry pi zero and I followed [this instruction on adafruit](https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-test) to add support for the INMP441 record module.
When I use the following command to record, the sound is loud and clear:
```
arecord -D dmic_sv -c2 -r 16000 -f S32_LE -t wav -V mono -v recording.wav
```

But If I record sound in python using the sounddevice lib as following, sound volume is very low:
```python
import sounddevice as sd, soundfile as sf, numpy as np
from time import sleep

samplerate = 16000
channels = 1
blocksize = int(samplerate*channels*0.1) # 0.1 second
dtype = 'int32'

try:
    with sf.SoundFile('sound.wav', mode='w', samplerate=samplerate, channels=channels, subtype='PCM_24') as file:

        def cb(indata, frames, time, status):
            nonlocal file
            if status:
                print(status, file=sys.stderr)
                raise sd.CallbackAbort
            data = np.frombuffer(bytes(indata), dtype=dtype)
            file.write(data)

        with sd.RawInputStream(callback=cb, samplerate=samplerate, blocksize=blocksize, channels=channels, dtype=dtype):
            while True:
                sleep(0.1)

except KeyboardInterrupt:
    print('Recording finished: ')
except Exception as e:
    print(e)
```

My question is: Is the python code equivalent to the linux command, or, are there any difference in parameter setting?
can you help me? THANK YOU

**Comment by mgeier** [comment]
It looks OK, but I'm not very familiar with using `int32`.

Is there a reason why you use `RawInputStream` instead of `InputStream`?

What happens if you use the default `dtype`?

This is most likely not related, but instead of your `blocksize` calculation you can just use:

```python
blocksize = 0
latency = 0.1
```

In fact, `blocksize=0` is the default, so you really only need `latency=0.1`.

**Comment by hyansuper** [comment]
at first I use `int32` because the linux command uses `S32_LE`.
then I tried different dtypes includeing int16 and float32(default), and setting blocksize=0 and latency=0.1, same result.
I also tried [this code](https://realpython.com/playing-and-recording-sound-python/#pyaudio_1) using pyaudio instead of sounddevice, same result. so this is not sounddevice's problem.

the code I showed is simplified version of my application. I want to capture audio from raspberry pi and send it to my computer, that's why I use `RawInputStream` to send the bytes.

**Comment by hyansuper** [comment]
I workaround it by multiply the numpy array by 10. still curious what caused it

**Comment by mgeier** [comment]
If the problem appears with `sounddevice` and PyAudio, but not with `arecord`, it is very likely a problem with the PortAudio library.

If you want to investigate further, you should probably ask at their mailing list (http://portaudio.com/contacts.html) or open an issue at https://github.com/PortAudio/portaudio.

**Comment by tikonen** [comment]
@hyansuper Try to record as stereo `channels = 2` and from data use only left channel. This might be caused by using stereo device as mono device. Stereo device has to halve signal level (-6dB) when summing left and right to mono.
