### ISSUE TITLE
Pauses on end-to-end recording

### ISSUE THREAD

**Issue by JBloodless** [spatialaudio/python-sounddevice#297]
Hi. I'm trying to to put some denoise algorithm between mic input and system output using virtual sound device as a hub. So I tried to implement some frame-by-frame reader which will capture for example 30ms of audio, put it through denoiser and then yield denoiser output to virtual driver, which will be able to transfer it to other system software. I made something like that:

```
import sounddevice as sd

sr = 16000
sd.default.samplerate = sr
sd.default.channels = 1

sd.default.device = 'Microphone (Realtek High Definition Audio), Windows DirectSound', 
'CABLE Input (VB-Audio Virtual Cable), Windows DirectSound'     #input from a microphone, output to virtual driver

fr_dur = 30                                                   #frame length in ms


def rec_frame(fr_dur, sr):
    fr_audio = sd.rec(int(fr_dur*sr/1000))
    sd.wait()
    return fr_audio


def denoise(frame):
    return frame                                                       #placeholder for now


if __name__ == '__main__':
    frame_last = rec_frame(fr_dur, sr)
    while True:
        processed = denoise(frame_last)                  #basically throw input frame to output
        frame = sd.playrec(processed)
        sd.wait()
        frame_last = frame
```

I'm faced some kind of leakage, because when I run this, nothing is captured from virtual driver by Audacity recorder, and when I increase window size to 3s, I see 0.5s pauses between 3s frames: [screenshot](https://imgur.com/a/ZKMYyM4)

 Where am I wrong?

**Comment by JBloodless** [comment]
Also, putting time.time() around sd.rec,
```
sr = 16000
fr_dur = 30
def rec_frame(fr_dur, sr):
    t2 = time.time()
    fr_audio = sd.rec(fr_dur*sr//1000)
    sd.wait()
    t1 = time.time()
    print('0 ', t1 - t2)
    return fr_audio
```
 I found that time of evaluation is not even close to what is set as recording time; for example, if I put frame duration as 3s, then this print will show 3.1974024772644043, and if I put my desired 30ms,  then it will be 0.22706222534179688, which not even close to 30ms. Where is  delay happening?

**Comment by mgeier** [comment]
> Where am I wrong?

You are using the wrong tool for the job.

See https://python-sounddevice.readthedocs.io/en/0.4.1/api/convenience-functions.html#sounddevice.rec:

"If you need more control (e.g. block-wise gapless recording, overlapping recordings, …), you should explicitly create an `InputStream` yourself."
