### ISSUE TITLE
python sound-device not recording properly

### ISSUE THREAD

**Issue by willywillycow** [spatialaudio/python-sounddevice#308]
I cannot use the sd.rec function, its output is entirely 0.

**Comment by mgeier** [comment]
Which OS?
Did you grant the necessary permissions?

**Comment by willywillycow** [comment]
> Which OS?
> Did you grant the necessary permissions?

Never mind I just figure it out, it is because that my terminal somehow is not asking for access so I restarted my computer a few times and it works fine now.
