### ISSUE TITLE
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error

### ISSUE THREAD

**Issue by mariomanalu** [spatialaudio/python-sounddevice#313]
I am trying to run the eSpeak program using portaudio, and I am getting the error outlined in the title. I know someone else encountered a similar problem, and they solved it by reinstalling portaudio using the --HEAD flag. I did that, but it has not worked.

FYI, I am using a Big Sur machine on Apple M1 processor.

**Comment by mgeier** [comment]
For reference:  #299

As I mentioned there, this is a problem with PortAudio and should be reported over there (if it hasn't been fixed already).
