### ISSUE TITLE
unable to record audio from macbook pro mic when specifying extra core audio settings

### ISSUE THREAD

**Issue by lstrgar** [spatialaudio/python-sounddevice#315]
Hi. I'm prototyping a script on my macbook pro that will ultimately be used with a mtrack 8 usb interface. 

I've borrowed much from this example 

https://python-sounddevice.readthedocs.io/en/0.4.1/examples.html#recording-with-arbitrary-duration

and have attempted to extend it such that I can specify which channels I want to record from.

After some search I've discovered this can apparently be done with 

https://python-sounddevice.readthedocs.io/en/0.3.15/api/platform-specific-settings.html#sounddevice.CoreAudioSettings

Testing this on my macbook pro (single channel audio input) is failing -- no audio appears to actually be written

```
 66     with sf.SoundFile(args.filename, mode='x', samplerate=args.samplerate,
 67                       channels=args.channels) as file:
 68         with sd.InputStream(samplerate=args.samplerate, device=args.device,
 69                             extra_settings=extra_settings, channels=args.channels):
 70             print('#' * 80)
 71             print('press Ctrl+C to stop the recording')
 72             print('#' * 80)
 73             while True:
 74                 file.write(q.get())
```

where ```extra_settings``` is given as ```sd.CoreAudioSettings(channel_map=args.indices)``` and ```args.indices``` is ```[0]```. 

Anybody have any feedback or guidance here? Many thanks in advance. 

Luke

**Comment by mgeier** [comment]
You *can* use the platform-specific settings to select channels, but you can also just record multiple channels and then select the channel data you are interested in (e.g. by NumPy array indexing).

But if you only want to record the first channel, why would you even need any of it?
You can just use `channels=1`.

As for why it is failing ... I don't know. Does it work if you don't use `CoreAudioSettings`?

**Comment by lstrgar** [comment]
I was prototyping something that I want to use with a multi channel input device. The program would be more flexible and useful if you could actually select channels... which supposedly you can do but it doesn't seem to be working for me. With any input device not just my mac mic.
