### ISSUE TITLE
[Asyncio]Pass-Through Example

### ISSUE THREAD

**Issue by jyoonab** [spatialaudio/python-sounddevice#329]
Hello, I am trying to apply "Asyncio" to Sounddevice code so I can boost up the speed of my code.

I wonder if there is any "Asyncio-applied" sample code which passes input directly to output
just like "Input to Output Pass-Through" sample from the Example Site.
(https://python-sounddevice.readthedocs.io/en/0.4.1/examples.html#input-to-output-pass-through)

Please let me know if there is. 
Thanks

**Comment by mgeier** [comment]
> [...] so I can boost up the speed of my code

Is this the only reason for you to use `asyncio`?

If there are no other reasons, you should probably do yourself the favor and *not* use `asyncio`.

Nothing against `asyncio`, it's just sometimes not the right tool for the job.

It's probably better to use a callback stream (which automatically runs in a separate thread, not making your other code slower) and communicate with the main thread via queues (which I guess would also classify as "asynchronous").

`asyncio` won't make this any faster, but probably more complicated (unless you are using `asyncio` already for different reasons, than it's OK).

> I wonder if there is any "Asyncio-applied" sample code which passes input directly to output
just like "Input to Output Pass-Through" sample from the Example Site.

There is:

https://github.com/spatialaudio/python-sounddevice/blob/d353fbf6c751a7a91169c614df8f905f2c55821c/examples/asyncio_generators.py#L73-L83

However, the implementation is not as simple as the callback example and it actually uses a callback function internally.
And it is actually slower in the sense that it adds latency, but it is probably also slower in the sense that it uses more CPU!

**Comment by jyoonab** [comment]
Ah, I see what you meant from your last comment.
I guess I also need to try a callback stream which you just suggested.
Thanks for giving me a sample code though = ]
