### ISSUE TITLE
Channel mapping with RawInputStream

### ISSUE THREAD

**Issue by raecke** [spatialaudio/python-sounddevice#33]
I want to record 2 channels from a multi-channel soundcard. I thought that would be possible with the mapping parameter, but found out that the stream (e.g. RawInputStream) do not support this.

Is there another way to record selected channels with a stream?

**Comment by mgeier** [comment]
PortAudio doesn't provide a platform-independent way to select arbitrary channels. You can only specify a certain number of channels N, which means that the channels 1 to N are used.

For convenience, I added the `mapping` argument to [play()](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.play) and [rec()](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.rec) and `input_mapping`/`output_mapping` to [playrec()](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.playrec). However, this simply checks for the largest channel number, requests this number of channels from PortAudio and fills the unneeded output channels with zeros (and ignores the unneeded input channels). It's not ideal if you have many unneeded channels, but it gets the job done

And that's what you can do in your code using `RawInputStream`, too.

Having said that, PortAudio also has some platform-specific functions to select certain channels (see http://portaudio.com/docs/v19-doxydocs/group__public__header.html), but those are currently not implemented in python-sounddevice (see #4). If you think they should be implemented, please leave a comment at #4. On what platform/host API would you need that feature?

**Comment by mgeier** [comment]
Selecting arbitrary channels is now possible with ASIO (see #34). If you need other platform-specific features, please comment on #4 or open a new issue.
