### ISSUE TITLE
Cannot record audio on mac Apple Silicon under Big Sur

### ISSUE THREAD

**Issue by jproy** [spatialaudio/python-sounddevice#332]
Hi ! Impossible to record audio on my mac mini M1 with Big Sur.
No error, but all frames are 0.
Maybe a problem with authorizing mic access in Big Sur ? Not sure.
Did I miss something ? (seems same with PyAudio). I saw this king of thread with Java too.
My mic works fine with authorized apps (GarageBand, etc).
And by the way securing the mic is a right move.
Thanks.

**Comment by jproy** [comment]
OK, I changed my IDE to Spyder4 under Anaconda, and it works fine (I was using Thonny with my son for simplicity). When asked for permission to access the mic, just say Yes. It seems that many software do not yet respect the security barriers of modern MacOS. But it is sad that there is no error from the Python side.

**Comment by mgeier** [comment]
See also #267.
