### ISSUE TITLE
Update PortAudio to version 19.7.0

### ISSUE THREAD

**Issue by aelray** [spatialaudio/python-sounddevice#333]
Hello,
I noticed there was recently a release of PortAudio (19.7.0) which could be integrated into python-sounddevice. I locally tried loading a self build DLL with version 19.7.0 and it initialized nicely and I could query all devices (did not do any further testing). Is there a reason not to update PortAudio within python-sounddevice?

**Comment by mgeier** [comment]
I was waiting for https://github.com/mxe/mxe/pull/2631 to be merged. MXE is used to cross-compile the Windows DLLs on Linux, see https://github.com/spatialaudio/portaudio-binaries.

If that takes too long, I can also build the DLLs using the PR without it being merged.

As for the macOS `.dylib`, I'm waiting for the next time I get my hands onto a Mac. If anybody else wants to help out, I'm open for contributions.

**Comment by mgeier** [comment]
@aelray I've created fresh DLLs at https://github.com/spatialaudio/portaudio-binaries/pull/7. Could you please check if they work for you?

**Comment by mgeier** [comment]
I've also created a dylib for macOS: https://github.com/spatialaudio/portaudio-binaries/pull/8.

**Comment by mgeier** [comment]
I have just created #340, can you please check if that works for you?

**Comment by aelray** [comment]
Sorry, I did not yet have the time to verify that it works. I will try this week.

**Comment by aelray** [comment]
Just tried it today. Works fine in our application.
