### ISSUE TITLE
Sound Device Can't Get The Right Device !

### ISSUE THREAD

**Issue by Karim-Fadi** [spatialaudio/python-sounddevice#337]
I have This Python Script That uses sound device and Vosk to perform Speech Recognition:
```python
import os
import queue
import sys
import sounddevice as sd
import vosk
import json


q = queue.Queue()
recognized = ""


def callback(indata, frames, time, status):
    if status:
        print(status, file=sys.stderr)
    q.put(bytes(indata))


try:
    samplerate  = 16000
    model = vosk.Model("model")

    with sd.RawInputStream(samplerate=samplerate, blocksize=8000, dtype='int16', channels=1, callback=callback):
        rec = vosk.KaldiRecognizer(model, samplerate)
        print("Listening...")
        while True:
            data = q.get()
            if rec.AcceptWaveform(data):
                recognized_json = json.loads(rec.Result())
                recognized += recognized_json['text']
                print(recognized)
                exit()

except KeyboardInterrupt:
    print("\nDone")
```
And The Script Works Really Well except one problem. I have a laptop and the internal Mic is trash so i use an external Mic, but the problem is that when i plug in the Mic before starting the script, the script uses the internal one even thought the external one is the system default. But if i plugged in the external mic while the script is running, it then uses the external Mic. So in short, it don't use the external Mic (Which is the System Default) unless i plug it in during the run time of the script. It is also worth mentioning that if the external mic is plugged in and i start the script, sometimes it uses the internal mic and sometimes it give me "sounddevice: portaudio error: Can't query device -1". So this is really annoying actually.

System Info:
Arch Linux (Alsa, pulseaudio installed).

The output of ```python -m sounddevice```:

```
  0 HDA Intel PCH: ALC269VB Analog (hw:0,0), ALSA (2 in, 2 out)
  1 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
  2 sysdefault, ALSA (128 in, 128 out)
  3 front, ALSA (0 in, 2 out)
  4 surround40, ALSA (0 in, 2 out)
  5 surround51, ALSA (0 in, 2 out)
  6 surround71, ALSA (0 in, 2 out)
  7 hdmi, ALSA (0 in, 8 out)
* 8 default, ALSA (128 in, 128 out)
  9 dmix, ALSA (0 in, 2 out)
```
I would really appreciate it if you helped me on this. Also feel free to ask if you want any more system info or any info in general. Thanks.

**Comment by mgeier** [comment]
Normally, when you change the hardware configuration during runtime, you should run this to re-initialize the PortAudio library:

```python
sd._terminate()
# change the hardware here
sd._initialize()
```

See also https://python-sounddevice.readthedocs.io/en/latest/api/expert-mode.html.

Does your device list look different if the mic is plugged in or not?

Apart from re-initializing PortAudio, I think there is nothing that can be done on the Python side, the rest is just the behavior of the PortAudio library.

Have you tried the latest PortAudio release?

If the problem still appears with the latest release, you could report it at https://github.com/PortAudio/portaudio.

**Comment by Karim-Fadi** [comment]
Thanks for the reply. Well i don't want to reinitialize the Port Audio Library as i don't want to change the hardware config during runtime. Changing the hardware config during runtime is just a workaround that i found by chance. Also i tried it and it didn't help.

As for my device list, it is same regardless. So it didn't change.

I am already using the latest PortAudio release.

Do you suggest anything i could do or i go report it at the PortAudio Repo ?

Thanks for the help.

**Comment by mgeier** [comment]
> Do you suggest anything i could do or i go report it at the PortAudio Repo ?

I think you should report it there.

It would be ideal if you could reproduce your problem with PortAudio's own example programs (which are written in C).

If not, you should try to find the PortAudio error number that's reported in the `sounddevice` exception you are experiencing.

Finally, you could also try out the yet unfinished PulseAudio Host API, see https://github.com/PortAudio/portaudio/pull/336.

**Comment by Karim-Fadi** [comment]
Ok thanks.

**Comment by mgeier** [comment]
You can keep this open until you have got an answer from the PortAudio people (please update this issue accordingly).

It is still an open issue, even if we can't do anything here ...
