### ISSUE TITLE
record 2 devices at the same time?

### ISSUE THREAD

**Issue by comes04** [spatialaudio/python-sounddevice#338]
Hi,
I am quite new to the “sounddevice” librarie, I have just use it to record some stuff before.
However, at the moment I would like to record at the same time from 2 different devices with the same script and get 2 separate files.
¿Could someone help me to do this?
I already check with query_devices and i can see that the 2 USB micros that i want to use are listed, also i can select one of them as the default input but not sure how to get both of them working at the same time.
Thanks in advance.

**Comment by mgeier** [comment]
You could try to create two `InputStream` objects, one for each device.

Depending on your OS and the used host API(s), this may or may not work.

Are you getting an error when creating two streams?

**Comment by comes04** [comment]
Hi Matthias, thanks for your reply,

I just figure out how to create those InputStream and saw that you can select any device.

This is the actual code I use that allow me to record from one inputand works

`import queue
import sys

import sounddevice as sd
import soundfile as sf
import numpy  # Make sure NumPy is loaded before it is used in the callback
assert numpy  # avoid "imported but unused" message (W0611)

sr = 44100
ch = 2
dir_1 = "C:/Users/moti/Documents/HOBBY/PLABS 3D/pruebas_audio_y_webcam/prueba_10_L.wav"

q = queue.Queue()

def callback(indata, frames, time, status):
    """This is called (from a separate thread) for each audio block."""
    if status:
        print(status, file=sys.stderr)
    q.put(indata.copy())

with sf.SoundFile(file=dir_1, mode='x', samplerate=sr, channels=ch, subtype=None) as file:
    with sd.InputStream(samplerate=sr, device=1,
                        channels=ch, callback=callback):
        print('#' * 40)
        print('recording')
        print('#' * 40)
        while True:
            file.write(q.get())`

However, when I try to put 2 InputStream, each one with a different device, it just record one of them. This is the code I try with the 2 InputSream, and I guess there is something wrong on how I put it all together:

`import queue
import sys

import sounddevice as sd
import soundfile as sf
import numpy  # Make sure NumPy is loaded before it is used in the callback
assert numpy  # avoid "imported but unused" message (W0611)

sr = 44100
ch = 2
dir_1 = "C:/Users/moti/Documents/HOBBY/PLABS 3D/pruebas_audio_y_webcam/trial_10_A.wav"
dir_2 = "C:/Users/moti/Documents/HOBBY/PLABS 3D/pruebas_audio_y_webcam/trial_10_B.wav"

q = queue.Queue()

def callback(indata, frames, time, status):
    """This is called (from a separate thread) for each audio block."""
    if status:
        print(status, file=sys.stderr)
    q.put(indata.copy())

with sf.SoundFile(file=dir_1, mode='x', samplerate=sr, channels=ch, subtype=None) as file:
    with sd.InputStream(samplerate=sr, device=1,
                        channels=ch, callback=callback):
        print('#' * 40)
        print('recording')
        print('#' * 40)
        while True:
            file.write(q.get())
            
with sf.SoundFile(file=dir_2, mode='x', samplerate=sr, channels=ch, subtype=None) as file:
    with sd.InputStream(samplerate=sr, device=2,
                        channels=ch, callback=callback):
        print('#' * 40)
        print('recording')
        print('#' * 40)
        while True:
            file.write(q.get())`

Thanks again for your time.

**Comment by HaHeho** [comment]
@comes04 for future requests (you can also edit the last response).
Please post your code in a readable way. Right now, the indentation got lost as well, which creates some uncertainty what the actual code was (as indentation matters in Python).

In GitHub Markdown, you can post code blocks including syntax highlighting for the language in this way:
````
```python
print('Code')
```
````
Which would be rendered like this 🙂 :
```python
print('Code')
```

**Comment by HaHeho** [comment]
The example you've built is too simple, as it contains that the recordings would be done consecutively. I assume you've intended to record from both devices simultaneously?

In that case you need to create separate threads (or processes). I have simplified the example provided at https://github.com/spatialaudio/python-sounddevice/blob/master/examples/rec_gui.py for something that might suit your needs? The code would like something like this
```python
import sys
from os.path import join
from queue import Queue
from threading import Thread
from time import sleep

from sounddevice import InputStream
from soundfile import SoundFile

import numpy  # Make sure NumPy is loaded before it is used in the callback

assert numpy  # avoid "imported but unused" message (W0611)


def file_writing_thread(*, q, **soundfile_args):
    """Write data from queue to file until *None* is received."""
    # NB: If you want fine-grained control about the buffering of the file, you
    #     can use Python's open() function (with the "buffering" argument) and
    #     pass the resulting file object to sf.SoundFile().
    with SoundFile(**soundfile_args) as f:
        while True:
            data = q.get()
            if data is None:
                break
            f.write(data)


def record_device(device_id):
    def audio_callback(data, frames, time, status):
        """This is called (from a separate thread) for each audio block."""
        if status:
            print(status, file=sys.stderr)
        audio_q.put(data.copy())

    file_name = join(rec_dir, f"rec_dev{device_id}_ch{channels}.wav")

    print("#" * 40)
    stream = InputStream(
        samplerate=fs, device=device_id, channels=channels, callback=audio_callback
    )
    stream.start()
    print(f"started stream {stream} ...")

    audio_q = Queue()
    print(f"generated queue {audio_q} ...")

    thread = Thread(
        target=file_writing_thread,
        kwargs=dict(
            file=file_name,
            mode="w",
            samplerate=int(stream.samplerate),
            channels=stream.channels,
            q=audio_q,
        ),
    )
    thread.start()
    print(f"started thread {thread} ...")
    print(f'recording file "{file_name}" ...')
    print("#" * 40)


if __name__ == "__main__":
    fs = 44100
    channels = 2
    rec_dir = "./"

    try:
        record_device(device_id=1)
        sleep(1)
        record_device(device_id=0)
        print("press Ctrl+C to stop the recording")

    except KeyboardInterrupt:
        print("\nInterrupted by user.")
        exit(0)
    except Exception as e:
        exit(type(e).__name__ + ": " + str(e))
```

I was not able to verify if the created files actually contain the correctly recorded sounds, respectively. But the code ran without problems on Windows. I assume you can test this more easily with your actual devices.

**Comment by comes04** [comment]
Hi Hannes,
Thanks for your quick reply and your time, this code actually works (windows) as I intended.
I just edited my last comment with the python “style”, nice tip :)
Thanks again for all your help.

**Comment by mgeier** [comment]
Thanks @HaHeho for the code, that's great!

Just out of curiosity, and more as an exercise than an actual suggestion, I tried to do it without manually creating threads:

```python
from queue import Queue

from sounddevice import InputStream
from soundfile import SoundFile

fs = 44100
channels = 2
device1 = 1
device2 = 2


def create_callback(q):

    def callback(data, frames, time, status):
        if status:
            print(status)
        q.put(data.copy())

    return callback


q1 = Queue()
q2 = Queue()

stream1 = InputStream(
    device=device1,
    samplerate=fs,
    channels=channels,
    callback=create_callback(q1),
)
stream2 = InputStream(
    device=device2,
    samplerate=fs,
    channels=channels,
    callback=create_callback(q2),
)

sf1 = SoundFile(
    file=f"rec_device_{device1}.wav",
    mode="w",
    samplerate=int(stream1.samplerate),
    channels=stream1.channels,
)
sf2 = SoundFile(
    file=f"rec_device_{device2}.wav",
    mode="w",
    samplerate=int(stream2.samplerate),
    channels=stream2.channels,
)

with sf1, sf2:
    with stream1, stream2:
        print("press Ctrl+C to stop the recording")
        try:
            while True:
                sf1.write(q1.get())
                sf2.write(q2.get())
        except KeyboardInterrupt:
            print("\nInterrupted by user.")
```

This is just to show that in general it is not necessary to manually create threads, but in many cases, especially more complicated ones than this simple example, it totally makes sense to use `threading.Thread`.

**Comment by HaHeho** [comment]
@comes04 feel free to close the Issue if your problem / question was solved! :)

**Comment by josephernest** [comment]
Nice solutions with threading (@HaHeho) and without (@mgeier)!

I never think about using a `Queue`, that's a good idea here.

Would it be the same to use:

* Solution 1: a global `DATA = []`, then in the audio callback: `DATA.append(data)`, then in the main loop `sf1.write(...)` the data coming from the list. Just to be sure, what's the advantage of using a Queue over this solution?

* Solution 2: `sf1.write(data)` directly in the audio callback, instead of putting the data in the Queue?

See you!

**Comment by mgeier** [comment]
> a global `DATA = []`, then in the audio callback: `DATA.append(data)`, then in the main loop `sf1.write(...)` the data coming from the list. Would this work too?

Maybe. Maybe in some situations, maybe not in others?

> Just to be sure, what's the advantage of using a Queue over this solution?

The queue was explicitly created for inter-thread communication, it is guaranteed to be thread-safe.

Other things might also be thread-safe. Or they might be accidentally thread-safe and in a different Python version they might not be anymore.

> `sf1.write(data)` directly in the audio callback, instead of putting the data in the Queue?

The problem here is that writing to a file is an operation where the OS is involved, and it might take an unexpected amount of time. If it takes too long, this might lead to audio drop-outs.

Of course, writing to the queue might lead to memory allocations which also might involve the OS, but this is generally considered to be less of a problem.

Anyway, if you want to have 100% reliability, you should probably not use Python. And no general-purpose OS and computer.

**Comment by pavankalyan066** [comment]
@mgeier 

Your approach works fine.

Myself working on creation of application that process the audio continuously and return text but only problem now is how to process audio bytes directly without saving it to audio file and it should process only if we have any audio bytes else it should wait/keep listening till it get some data in the queue.

Thank you.
