### ISSUE TITLE
Can't play to any audio devices, there's 3 duplicates listed for every device on my machine.

### ISSUE THREAD

**Issue by Iamgoofball** [spatialaudio/python-sounddevice#339]
```
Traceback (most recent call last):
  File "noname.py", line 444, in VCFile
    sd.play(data, fs, device=self.SpeakerName.GetValue())
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 174, in play
    ctx.start_stream(OutputStream, samplerate, ctx.output_channels,
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 2573, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 1488, in __init__
    _StreamBase.__init__(self, kind='output', wrap_callback='array',
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 811, in __init__
    _get_stream_parameters(kind, device, channels, dtype, latency,
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 2650, in _get_stream_parameters
    device = _get_device_id(device, kind, raise_on_error=True)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sounddevice.py", line 2798, in _get_device_id
    raise ValueError('Multiple ' + kind + ' devices found for ' +
ValueError: Multiple output devices found for 'Headphones (COWIN E7 Stereo)':
[6] Headphones (COWIN E7 Stereo), MME
[18] Headphones (COWIN E7 Stereo), Windows DirectSound
[30] Headphones (COWIN E7 Stereo), Windows WASAPI
```

The code in question is extremely basic;

```
data, fs = sf.read(outpath, dtype='float32')
sd.play(data, fs, device=self.SpeakerName.GetValue())
```
The value of self.SpeakerName.GetValue() is ``Headphones (COWIN E7 Stereo)``.

According to the documentation, there's no way to just play to the first device that matches the name, since there's no way to get the IDs of those duplicates. How am I supposed to use this module if this is the case? 

Every other audio device I've tried has the same issue, and I can't just hardcode in the speaker ID, or just use the OS defaults. 
Users need to be able to specify what device they want to output the audio to, and sometimes this needs to be different from the default audio devices specified by the OS(for situations like virtual audio cable)/

**Comment by HaHeho** [comment]
Isn't using `"Headphones (COWIN E7 Stereo), MME"` (or whichever you want to use) as the explicit device name with the backend?

**Comment by Iamgoofball** [comment]
I suppose that'd work, but it's a bit of a hack to have to append ``, MME`` to every entered device name.

**Comment by HaHeho** [comment]
I don't understand why you'd call it a hack. This is literally the device name that `sounddevice` needs to identify which one you want to use (as shown in your posted error message).

If you want to for example build a user friendly GUI, where the user should not be provided with all options, you could do this easily by filtering the list of available audio devices and then append the backend (or whatever it should be called?) in code, as you described before.

**Comment by Iamgoofball** [comment]
You know, that's actually a very good point. I didn't think of it like that. Thanks!
