### ISSUE TITLE
Plot Microphone Signal(s) in Real-Time example is not working on my computer 

### ISSUE THREAD

**Issue by Wawi36** [spatialaudio/python-sounddevice#376]
Hello,
I'm currently trying to learn how audio acquisition works with sounddevice.
I've gone through the examples, and one of them (Plot Microphone Signal(s) in Real-Time example - I was very interested in it) didn't work on my computer.

I'm currently working on Windows 10 with Python 3.8.8 in Spyder 4.2.5 (the last version provided by Anaconda)
I spotted while running the example that the callback function was never used.

So I investigated the FuncAnimation from pyplot.animate. I changed the Tools->Preferences->IPython_console->Graphics->Backend to Qt4. This action allows the FuncAnimation to reload frames. I tested it and the animation works.

I tried again to run the example ‘Plot Microphone Signal(s) in Real-Time’ but the callback function is never used by the Stream.

I was wondering if someone had the same problem?
Thanks for reading and have a nice day!

**Comment by mjjohnson** [comment]
I also just tried this example and it didn't work for me. Running directly from Terminal on MacOS 10.15.7, it just prints the following and immediately exits:

```
$ ./plot_input.py 
/private/tmp/./plot_input.py:11: MatplotlibDeprecationWarning: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.animation import FuncAnimation
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/animation.py:973: UserWarning: Animation was deleted without rendering anything. This is most likely unintended. To prevent deletion, assign the Animation to a variable that exists for as long as you need the Animation.
```
