### ISSUE TITLE
Question: resume inputstream after sd.CallbackStop()

### ISSUE THREAD

**Issue by hjkaddict** [spatialaudio/python-sounddevice#383]
Hi, I would like to say thank you first for making this library.

I think this question might be more python related question rather than the library but I have no other people to ask so decided to throw question here. I am making simple speech recognition (keyword classifier) by using sounddevice to make simple voice bot on raspi. Following a few tutorials, it now gets user's sound input with sd.Inputstream then process prediction in callback function. 

My strategy is when the certain speech is detected, the callback function is stop with sd.CallbackStop() and playback an audio file. Below is the simplified code.

```
def sd_callback(rec, frames, time, status):
    
    # function that returns 'classified' to True  
    prediectionFunction()

    if classified is True:
        raise sd.CallbackStop()

stream = sd.InputStream(channels=num_channels,
                samplerate=sample_rate,
                blocksize=int(sample_rate * rec_duration),
                callback=sd_callback)

with stream: 
    while (stream.active):
        pass
    else : 
        playAudioFunction()


```
The problem is the playAudioFunction() is executed well for the first time, but python program is finished right after that. What I would like to do is to resume or restart the stream. Would you give me an idea how to implement this?

Thanks!

**Comment by HaHeho** [comment]
You will need some kind of loop around the `with stream:` statement. Probably something like an "endless loop" with an exception handler to terminate it. Not the best, but functional and a good starting point.

Code untested, but something like this.
```python
# code
print('Press [CTRL]+[C] to interrupt.')
try:
  while True:
    with stream:
      # code
except KeyboardInterrupt:
  print('Interrupted by user.')
```

**Comment by hjkaddict** [comment]
Thanks a lot, seems like it is a good starting point.
