### ISSUE TITLE
play function counfusion

### ISSUE THREAD

**Issue by kerbingamer376** [spatialaudio/python-sounddevice#40]
Hi,
I'm confused about the play() function in this library. in the documentation, it says it returns immediately, but for me, it seems to start, wait for the playback to finish, and then return. Why is this happening/has it been changed?

**Comment by mgeier** [comment]
The `play()` function is supposed to work like advertised in the documentation. When you use `blocking=False` (which is the default), it *should* return immediately. However, you might have discovered a bug ...

Can you please give a working code example that shows the unexpected behavior?

**Comment by kerbingamer376** [comment]
Oh, I was running it WITH blocking, as that's what it said in the example. Thanks! (sorry for being a noob lol)

**Comment by mgeier** [comment]
OK, no problem.

If something in the documentation isn't clear enough, please tell me!
