### ISSUE TITLE
Question about rec_gui.py "settings"?

### ISSUE THREAD

**Issue by xiaoli1996** [spatialaudio/python-sounddevice#407]
Hello, I meet a question. Now I running rec_gui.py, "Invalid number of channels [PaErrorCode -9998]" is occurred when I  click "OK" or "Cancel"  after clicking "settings" . I didn't change any settings in “settings” button,  just click "OK" or "Cancel". But the bug has not occurred when I direct click "record" and "stop", everything is normal.

**Comment by xiaoli1996** [comment]
![1](https://user-images.githubusercontent.com/52903099/171593969-af598a1c-427c-4bef-a165-b415d7d96cb4.png)
![2](https://user-images.githubusercontent.com/52903099/171593984-243cda9f-4770-4579-8396-ef5998849240.png)

**Comment by xiaoli1996** [comment]
Clicking directly "record" and "stop", everything is normal.
![3](https://user-images.githubusercontent.com/52903099/171594395-f08f6817-0e5b-4df9-9311-ae9686bebecb.png)

**Comment by mgeier** [comment]
Thanks for reporting this!

It looks like you discovered a silly mistake that I made, see #408. Can you please check if that works for you?

**Comment by xiaoli1996** [comment]
@mgeier Many thanks for your help, it solves my problem.

**Comment by mgeier** [comment]
Thanks for testing this. If there are any further problems, let me know!
