### ISSUE TITLE
Telling when a sound ends

### ISSUE THREAD

**Issue by lukeoftheaura** [spatialaudio/python-sounddevice#42]
Hi,
I'm running play() without blocking, how can I tell when playback finishes?

**Comment by mgeier** [comment]
The only think you can do is to use `wait()`. If playback is already finished, this returns immediately. If not, it waits until playback is finished.

If you write your own callback function with `sounddevice.OutputStream`, you can use the `finished_callback` argument.

What is your use case?

**Comment by mgeier** [comment]
@lukeoftheaura Does it work now for you, or do you need more help?

**Comment by lukeoftheaura** [comment]
Yeah, works now, thanks!
