### ISSUE TITLE
PortAudio not finding native ASIO

### ISSUE THREAD

**Issue by karinannfl** [spatialaudio/python-sounddevice#429]
I have a Sound Blaster Z SE audio card.  I am using PortAudio v1.9 in a C# bit code I wrote.  When PortAudio is initialized that works OK. When the host devices are enumerated in the code when it comes to finding the ASIO driver for the Z SE card it does not find the ASIO driver.  If I load ASIO4ALL then PortAudio finds the ASIO4ALL driver, so I am assuming the dll works OK.  Is there something unique about ASIO native driver for the Sound Blaster card???

Karin

**Comment by mgeier** [comment]
Sorry, I can't answer this, please ask the people from the PortAudio project: http://portaudio.com/contacts.html

**Comment by mgeier** [comment]
See https://listserv.cuit.columbia.edu/scripts/wa.exe?A2=PORTAUDIO;be97ad47.2208D&FT=M&P=&H=&S=b
