### ISSUE TITLE
how can we end playback early?

### ISSUE THREAD

**Issue by SoulProficiency** [spatialaudio/python-sounddevice#440]
just like the command of 'stop' or "terminate"?

**Comment by HaHeho** [comment]
Utilizing `KeyboardInterrupt` should work? E.g.
https://github.com/spatialaudio/python-sounddevice/blob/841e0a1b2ea2367476248e5f0fc6878154949417/examples/rec_unlimited.py#L82

**Comment by SoulProficiency** [comment]
> Utilizing `KeyboardInterrupt` should work? E.g.
> 
> https://github.com/spatialaudio/python-sounddevice/blob/841e0a1b2ea2367476248e5f0fc6878154949417/examples/rec_unlimited.py#L82

i found it's not work with a pyqt5 GUI.i try to use a thread and it's work！
here is my code:
`
class New_Thread(QThread):
    def __init__(self,wave_dir,flag):
        super(New_Thread, self).__init__()
        self.flag = flag
        self.wave_dir = wave_dir
        self.isCancel = False
    def run(self):
        if self.flag:
            data, fs = sf.read(self.wave_dir)
            # index 7 is my device 
            sd.default.device[1] = 7
            sd.play(data, samplerate=fs)
            sd.wait()
            print("true")
        else:
            # terminate() can't stop playing,so i use a new thread to play again
            data = np.empty((1000,2))
            sd.default.device[1] = 7
            sd.play(data, samplerate=8000)
            sd.stop()
            print("false")
class Example(QMainWindow):
    def __init__(self,audio_address):
        super().__init__()
        # init parameters
        # audio_address
        L = audio_address
        # use self.index to choose the audio we need
        self.index = 0
    def initUI(self):
        # play
        self.buttonOnePlay = QPushButton("play", self)
        self.buttonOnePlay.clicked.connect(self.lineOnePlay)
        self.buttonOnePlay.setStatusTip("play target audio")
        # stop
        self.buttonOneStop = QPushButton("stop", self)
        self.buttonOneStop.clicked.connect(self.lineOneStop)
        self.buttonOneStop.setStatusTip("stop target audio")
        self.buttonOneStop.setEnabled(False)
    def lineOnePlay(self):
        if self.if_thread:
            # actually,terminate() just stop a thread,can't stop playing.
            self.thread.terminate()
            self.thread.wait()
            del self.thread
            print("play del")
        self.if_thread = True
        self.thread = New_Thread(L[self.index - 1],True)
        self.thread.start()
        self.buttonOneStop.setEnabled(True)
        self.buttonSub.setEnabled(False)
    def lineOneStop(self):
        if self.if_thread:
            self.thread.terminate()
            self.thread.wait()
            del self.thread
            print("stop del")
        self.thread = New_Thread(L[self.index - 1],False)
        self.thread.start()
`

**Comment by SoulProficiency** [comment]
i found it's not work with a pyqt5 GUI.i try to use a thread and it's work！
