### ISSUE TITLE
Python: sd.query_devices() can't update audio device [Mac]

### ISSUE THREAD

**Issue by KiDo-Ruan** [spatialaudio/python-sounddevice#443]
I install portaudio by homebrew (brew install portaudio) then I use `sounddevice.query_devices()` to get all available device on my Mac, but when I change device and recall `sounddevice.query_devices()` that not update new device.
I tried to use this :
`sd._terminate()`
Change device:
`sd._initialize()`
but I can't update new device when I recall `sounddevice.query_devices()`

How do I fix it in my project? Thanks for your answer!

**Comment by mgeier** [comment]
The hardware devices are managed by the underlying PortAudio library.

If you device is not working, you can ask for support over there: http://portaudio.com/contacts.html
