### ISSUE TITLE
Provide unique alternative names for windows audio devices.

### ISSUE THREAD

**Issue by belonesox** [spatialaudio/python-sounddevice#45]
On Windows (especially in laptops) original DirectShow audio device name is not unique:

sd.query_devices()

...

```
   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out) 
>  1 Микрофон (Устройство с поддержк, MME (2 in, 0 out)
   2 Микрофон (Устройство с поддержк, MME (2 in, 0 out)
   3 Линия (Elgato Sound Capture), MME (2 in, 0 out)
   4 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  5 Динамики (Устройство с поддержк, MME (0 in, 2 out)
   6 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
```

Name for device _1_ (enabled mic) same as for device _2_ (disabled mic).

It will be great to get somehow unique "Alternative name" for devices 
(In particulary I try to get this name for default device).

```
[dshow @ 00000193d788a8a0]  "Микрофон (Устройство с поддержкой High Definition Audio)"
[dshow @ 00000193d788a8a0]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{A63B8A2D-19F7-4D35-AFA7-0C750E7B6595}"
[dshow @ 00000193d788a8a0]  "Микрофон (Устройство с поддержкой High Definition Audio)"
[dshow @ 00000193d788a8a0]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{293B27B7-BDD1-4B42-
```

**Comment by mgeier** [comment]
I'm getting the device names straight from the PortAudio library, I don't know how I could get those alternative names.
Also, those alternative names are way ugly, aren't they?
And you still don't see which one is enabled and which is disabled ...

How are those devices shown in other applications that use PortAudio, e.g. Audacity?

**Comment by mgeier** [comment]
@belonesox Ping?

**Comment by belonesox** [comment]
Sorry for delay, I reinstall Windows, to get rid of russian names for audio devices for screenshots and demos.

Yes, Audacity have same problem with device names
http://wiki.4intra.net/images/2/2f/Audio_configuration_of_HP2540p_on_Windows10_and_Audacity.png

I describe my problem here http://wiki.4intra.net/User:StasFomin/HowTo/GetDefaultMicOnWindows
and still have no solutions (how to detect unique default audio input device, using sounddevice or anything else).

**Comment by mgeier** [comment]
Thanks for the update!

Since Audacity shows the same problem, I'm quite sure it is something that should be handled in PortAudio itself.
You should write this to the PortAudio mailing list (http://portaudio.com/contacts.html)!

**Comment by belonesox** [comment]
Yes, thank you.  Actually I solved my problem (by reading audio from another unique source, webcam), but I just want to mention about such problem — sound cards with same readable names (but different alternative names).
