### ISSUE TITLE
Unable to recieve audio from microphone

### ISSUE THREAD

**Issue by elia-ashraf** [spatialaudio/python-sounddevice#479]
Hi, 

I have been trying to record audio from an external microphone using sd.InputStream() and I am unable to do so. I have been able to achieve the same with my system's microphone, but I am unble to do so with any external microphones. 

I have not been able to find any similar issues mentioned, but if there is one and you know of it, please do tag me in it.
Thank you.

**Comment by mgeier** [comment]
This question is much too vague to give an answer beyond randomly guessing.

Please create a new issue with much more information, see https://python-sounddevice.readthedocs.io/en/0.4.6/CONTRIBUTING.html#reporting-problems for some inspiration.
