### ISSUE TITLE
Please add PaWasapi_UpdateDeviceList

### ISSUE THREAD

**Issue by Swiftgti** [spatialaudio/python-sounddevice#484]
Please for windows make a distribution with PaWasapi_UpdateDeviceList enabled, its possible?
Thanks

**Comment by mgeier** [comment]
Is #486 enough or do you also need a high-level Python API for that?

**Comment by mgeier** [comment]
> There is any way to use PortAudio of jitsi ?

Yes, but I don't know what's the best way to do that on Windows (which I assume that you are using).

You might be able to put a `portaudio.dll` file somewhere in your binary search path.
Alternatively, you can just replace the file `_sounddevice_data/portaudio-binaries/libportaudio64bit.dll`.

Here are some older comments about the "hotplug" fork:

https://github.com/spatialaudio/python-sounddevice/issues/125#issuecomment-514065063

https://github.com/spatialaudio/python-sounddevice/issues/382#issuecomment-986019480

> or support it like an option?

It should already be possible, but this should be tested and documented.

> or move the project to use that fork?

The fork doesn't seem well maintained, so no.

But you could try to help the PortAudio team to include that feature into the official PortAudio codebase.
