### ISSUE TITLE
Error when ASIO devices use special encoding

### ISSUE THREAD

**Issue by shoucandanghehe** [spatialaudio/python-sounddevice#490]
The code says `All other host APIs use 'utf-8' anyway.`
This is wrong, for example on my PC there is an ASIO device that uses GBK encoding.
`b'DSD \xd7\xaa\xc2\xeb\xc6\xf7 (DoP/Native)'`
https://github.com/spatialaudio/python-sounddevice/blob/791c09db3b187257e53f79725c13c1efdb4ff458/sounddevice.py#L572-L585

btw, in my test, the `raise` at line 585 doesn't output anything, and I'm not quite sure why.
![image](https://github.com/spatialaudio/python-sounddevice/assets/51957264/71a07179-079b-4832-981e-74be10efe61f)

**Comment by mgeier** [comment]
I have merged #512, which hopefully fixes this problem.
