### ISSUE TITLE
How to get volume level of playing sound with RawOutputStream ?

### ISSUE THREAD

**Issue by JamesZBL** [spatialaudio/python-sounddevice#497]
I use np.linalg.norm(data), but It returns 15000 to 18000 when I use it with RawOutputStream. How can I get the volume level?
Or should I use OutputStream alternatively? Is there any examples ? I just find only RawOutputStream example here:[https://python-sounddevice.readthedocs.io/en/0.3.14/examples.html#play-a-very-long-sound-file]. 

Apppreciated for any help.

**Comment by JamesZBL** [comment]
Is the any example for Play file Using OutputStream? I only find the example for Play signal Using OutputStream.

**Comment by JamesZBL** [comment]
The example for Playing file is RawOutputStream. It's different.

**Comment by mgeier** [comment]
> Is the any example for Play file Using OutputStream?

The examples are there: https://github.com/spatialaudio/python-sounddevice/tree/master/examples
And the can also be seen here: https://python-sounddevice.readthedocs.io/en/0.4.6/examples.html

If I counted correctly, 4 of them use `OutputStream` and 2 of them use `RawOutputStream`.

Feel free to use GitHub's "search" function at the top of this page.
