### ISSUE TITLE
timestamps in callbacks

### ISSUE THREAD

**Issue by stvol** [spatialaudio/python-sounddevice#5]
What kind of timestamps are passed to the callback?
When I print them there are only 4 digits before the decimal point.

**Comment by mgeier** [comment]
Have a look at the [documentation for `sounddevice.Stream.time`](http://python-sounddevice.readthedocs.org/#sounddevice.Stream.time), which I directly copied from the [PortAudio documentation](http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#a2b3fb60e6949f37f7f134105ff425749).

The timestamp is just a 64-bit `float` value that represents seconds.
You shouldn't care about the absolute value of this, you should only use it for relative time (i.e. time differences).

**Comment by mgeier** [comment]
@stvol: does this answer your question?

If yes, please close the issue. If not, please add further comments.
