### ISSUE TITLE
Dropping audio/Advice on implementing a PAUSE/RESUME 

### ISSUE THREAD

**Issue by andrewfr** [spatialaudio/python-sounddevice#500]
Hi Folks:

I don't know if this is the right place to ask for advice? I am still new to audio.

I am trying to pause and resume a RawOutputStream. I am using a callback. The problem is I lose about a little bit of audio. I guess I am dropping a frame (not even a second of sound. I need to figure out how to calculate this). 

my sample rate is 24000 and block_size is 8192

More information. My threads communicate through queues.

audio_generation -> output_audio -> callback

in output_audio (a while loop)

```
while True:
        message = io_context.audio_queue.get()
        match message.type:
                 case MessageType.PAUSE:
                        io_context.output_stream.stop()
                        io_context.audio_internal_queue.put_nowait(message)
                        continue

                 case MessageType.RESUME:
                        if not io_context.output_stream.active:
                            io_context.output_stream.start()
```

My callback is similar to the sd examples

```
def callback(outdata, frames, time, status):
        assert frames == block_size
        if status.output_underflow:
            print("Output underflow: increase blocksize?", file=sys.stderr)
            raise sd.CallbackAbort
        assert not status
        try:
            message = io_context.audio_internal_queue.get()

            if message.type == MessageType.PAUSE:
                return

        except queue.Empty as e:
            print("Buffer is empty: increase buffersize?", file=sys.stderr)
            raise sd.CallbackAbort from e

        data = message.data

        if len(data) <= len(outdata):
            outdata[: len(data)] = data
            outdata[len(data) :] = b"\x00" * (len(outdata) - len(data))
```

I know the pause does not work because  it arrives too late. I thought about manipulating the callback queue to have it raise a sd.CallbackStop in the callback but that is tricky.  What is the recommended way to pause and resume an audio stream?

Thanks in advance,
Andrew

**Comment by mgeier** [comment]
> I am trying to pause and resume a RawOutputStream. [...] The problem is I lose about a little bit of audio.

I'm not sure what you are expecting to happen, but stopping and re-starting a stream will not be gapless.

If you want the sound to stop, don't stop the stream, but write zeros to the stream. When you want the sound to continue, start writing the signal values again.

**Comment by mgeier** [comment]
I don't really understand what you are trying to do, so I was just guessing.

If you provide a minimal reproducible example and explain what you expect to happen that doesn't, I may be able to give you more meaningful advice.

**Comment by andrewfr** [comment]
Hi Matthais:

I am sorry for being so late in replying. I am building a voice assistant (more specifically a Dialogflow custom integration). Consequently I have to handle much of the low-level IO. So far, sounddevice is doing a fantastic job.  I am not an audio person. I have much to learn. And I still have a lot to do. Within the week, I'll try to post a small example of how I pause output.

Cheers,
Andrew

________________________________

**Comment by mgeier** [comment]
I'm closing this for now, please create a new issue once you have a MRE.

**Comment by andrewfr** [comment]
Hi Matthias:

Sorry about that. Let me get on this.

Cheers,
Andrew


________________________________
