### ISSUE TITLE
Raspberry pi: sounddevice query_devices() does not see usb devices

### ISSUE THREAD

**Issue by pr-wiley** [spatialaudio/python-sounddevice#504]
>>> import sounddevice as sd
>>> sd.query_devices()
  0 sysdefault, ALSA (0 in, 128 out)
  1 lavrate, ALSA (0 in, 128 out)
  2 samplerate, ALSA (0 in, 128 out)
  3 speexrate, ALSA (0 in, 128 out)
  4 upmix, ALSA (0 in, 8 out)
  5 vdownmix, ALSA (0 in, 6 out)
< 6 default, ALSA (0 in, 128 out)
  7 dmix, ALSA (0 in, 2 out)
>>> 

BUT

$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter
Bus 001 Device 006: ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter
Bus 001 Device 005: ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter
Bus 001 Device 004: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 003: ID 0781:55a1 SanDisk Corp. Cruzer Spark
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Why aren't the C-Media cards listed when I do sd.query_devices()? My memory is that they were, but after updating the system they aren't. I'm confused about what might have gone wrong.

System info: Raspberry Pi 4 Model B Rev 1.4. --- Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023

**Comment by mgeier** [comment]
https://github.com/spatialaudio/python-sounddevice/issues/471#issuecomment-1784838528

**Comment by pr-wiley** [comment]
Above poster here in error. Apologies for duplication.
