### ISSUE TITLE
Can I continue recording until the volume drops below a threshold?

### ISSUE THREAD

**Issue by creeper-0910** [spatialaudio/python-sounddevice#527]
I want to use sounddevice to continue recording until the volume drops below a certain value and then save it as a file, but in most examples I specify the number of seconds and record.
Is it possible to do this?

**Comment by mgeier** [comment]
Yes, this is certainly possible. You'll have to implement the signal processing, though.

**Comment by creeper-0910** [comment]
Thank you!
Do you have any samples or other reference for signal processing implementation...?

**Comment by mgeier** [comment]
No, that's out of scope for the `sounddevice` module. But you could try asking at https://dsp.stackexchange.com/, for example.

**Comment by creeper-0910** [comment]
Understood, thank you for your courteous response!
