### ISSUE TITLE
Inconsistent order of channels

### ISSUE THREAD

**Issue by victorallume** [spatialaudio/python-sounddevice#543]
I have a number of 8-channel USB sound devices on a Linux/ALSA system. Each device 4 3.5mm outputs - one for each of Front, Surround, Centre/Bass, Back. I'm using an OutputStream with callback to send data to these devices. The problem is the channel mapping within a device is not consistent, either across devices or across runs of my program, or reboots. So sometimes the first physical output jack (Front) corresponds to the first two channels in my output stream, sometimes it's the 3rd & 4th channels, etc etc. 

Any ideas how to make this consistent, or at least be able to read what output a channel is going to so I can map accordingly?

**Comment by mgeier** [comment]
The list of devices is provided by the underlying PortAudio library (which in turn somehow gets it from ALSA), and from the Python side you only get the device name, which might not help in your case.

You should ask about this in the PortAudio mailing list or issue tracker: https://portaudio.com/contacts.html

However, I think this is a known problem and has been discussed many times, and I don't think there is a straightforward solution ... but who knows, you should still ask!

**Comment by victorallume** [comment]
I've re-created the issue using alsa, so it seems it's a problem at that level, not at sound-device or portaudio. https://github.com/alsa-project/alsa-lib/issues/402
