### ISSUE TITLE
Docs: Going to https://python-sounddevice.readthedocs.io/ goes to old version of docs

### ISSUE THREAD

**Issue by JohnVillalovos** [spatialaudio/python-sounddevice#557]
If use the link https://python-sounddevice.readthedocs.io/ it will take you to the old version of the docs. Version 0.4.7. It will warn you that there is a 0.5.0 version of the docs available.

Would make sense (to me) to go to the latest version of the docs when going to: https://python-sounddevice.readthedocs.io/

**Comment by mgeier** [comment]
Thanks for reporting this!

I forgot to update it, now it should work as expected!

**Comment by JohnVillalovos** [comment]
Works now! Thank you 👍
