### ISSUE TITLE
sounddevice.PortAudioError: Error getting stream time

### ISSUE THREAD

**Issue by M0Rf30** [spatialaudio/python-sounddevice#56]
Using friture-git I've encountered this issue:
  ```
File "/usr/lib/python3.5/site-packages/sounddevice.py", line 1069, in time
    raise PortAudioError('Error getting stream time')
sounddevice.PortAudioError: Error getting stream time

```

**Comment by mgeier** [comment]
You should ask the friture-git people then.

**Comment by mgeier** [comment]
Did you get an answer there?
It might be helpful to other people who stumble upon this issue.

**Comment by M0Rf30** [comment]
Yes loop-printed line was fixed here 
https://github.com/tlecomte/friture/issues/53

**Comment by mgeier** [comment]
Thanks, that's good to know!
