### ISSUE TITLE
Question: Sending InputStream over a WebSocket

### ISSUE THREAD

**Issue by jamesstidard** [spatialaudio/python-sounddevice#57]
Hi,

I'm trying to write an application where I can stream the input of one device over a websocket for all the connected clients.

Currently I have everything set up so I can broadcast out the base64 encoded bytes returned by either `sounddevice.InputStream` or `sounddevice.RawInputStream` as they are returned by their callback. Currently this looks like:
```python
@classmethod
def handle_input_buffer(cls, data, frames, time, status):
    message = b64encode(data.copy().tostring())
    cls.broadcast(message)
```

Obviously broadcasting a stringified version of a numpy array doesn't make sense if the clients aren't Python clients. Would anyone be able to suggest what kind of format I should best send this out in - so it can be serialized by clients?

Thanks

**Comment by mgeier** [comment]
This is probably not the right place to ask this question ...

There are already many streaming solutions available, WebRTC and Icecast come to my mind, but there sure are many more.
You could look at any of those to see how they transmit their data.

If the capacity is not really limited, you can just send the bytes provided by `sounddevice.RawInputStream` as they are. I don't see any advantage in using a text encoding like base64. You can transmit binary data via WebSockets.
However, you might need some additional framing in order for clients to know at which byte they should start reading.

Anyway, I'm not the right person to answer this, and I fear those who are will not read this issue ...

**Comment by JamesStidard** [comment]
Hi @mgeier,

Thanks a lot for the response. I kinda knew this question was a bit of a shot in the dark; I've been trying to find some good resources online but I don't find many people talking around the topic - which makes me think I'm asking the wrong questions.

I will take a look at WebRTC and Icecast and play around with just sending the raw bytes over the wire.

Thanks again.
