### ISSUE TITLE
no support for arbitrary length recordings?

### ISSUE THREAD

**Issue by tgarc** [spatialaudio/python-sounddevice#59]
First off, thanks for developing this! PyAudio is kind of incomplete and seems to be pretty inactive so I'm really glad to see this project getting off the ground.

Anyway, I'm pretty new to this library so forgive me if I missed something but I can't seem to find any support for making arbitrary length recordings. So, did I miss something? And if not, do you have any plans to add this functionality in the near future?

**Comment by mgeier** [comment]
Arbitrary length recordings are beyond the scope of the built-in convenience functions.
But there is the example application [rec_unlimited.py](../blob/master/examples/rec_unlimited.py) which should help you implementing your own solution.

If you need more help, don't hesitate to ask!

**Comment by tgarc** [comment]
Ah, okay that makes perfect sense but I hadn't seen that example. I think I get it now; instead of returning a paComplete or something of the sort in the callback I just raise a CallbackStop. I think I got what I need.
