### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by AdamDulak** [spatialaudio/python-sounddevice#62]
Hi, on windows when I have devices that have polish characters in the module's name, it crashes:

```
>>> import sounddevice as sd
>>> sd.query_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin_000\AppData\Roaming\Python\Python27\site-packages\sounddevice.py", line 1887, in __repr__
    return text.encode(_sys.stdout.encoding or 'utf-8')
  File "C:\Python27\lib\encodings\cp852.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014' in position 77: character maps to <undefined>
>>> sd.query_devices()
Exception KeyboardInterrupt in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored
```

To fix this, I had to change in `sounddevice.py` line:

`return text.encode(_sys.stdout.encoding or 'utf-8')`
to:
`return text.encode('utf-8')`

**Comment by mgeier** [comment]
Thanks for the bug report!

Can you please check what the value of `_sys.stdout.encoding` is in your case?
It looks like `'cp852'`, right?
Can you change the encoding of your terminal?

What about changing the code to `return text.encode(_sys.stdout.encoding or 'utf-8', 'replace')`?

Did you check out #30?

What's up with the "threading" thing in the last line of your listing?
The `threading` module shouldn't be loaded at this point ...

BTW, your character `u'\u2014'` doesn't seem to be particularly Polish, I assume it's the "em dash", see http://www.unicode.org/charts/PDF/U2000.pdf.

**Comment by mgeier** [comment]
@AdamDulak Any news?

**Comment by AdamDulak** [comment]
Hi @mgeier 
Sorry it took so long but was busy and had no time to check or answer :) Didn't check properly what was causing the problem but you are right. Also changing it to:
> return text.encode(_sys.stdout.encoding or 'utf-8', 'replace')
does the job

**Comment by mgeier** [comment]
@AdamDulak I've just created #67. Can you please check if it works for you?

**Comment by AdamDulak** [comment]
yup, sorry again for late reply ;D good to go.
