### ISSUE TITLE
Cracling noises with Asus Xonar U7 USB audio card

### ISSUE THREAD

**Issue by Plecto123** [spatialaudio/python-sounddevice#63]
```python
t=10
Fs=48000.0

x=np.linspace(0.0, t, Fs*t)
y=np.sin(1000*2.0*np.pi*x)
myrecording = sd.playrec(y, Fs, channels=2, blocking=True)
```

`sd.playrec()` worked fine with my previous USB sound card, but it makes crackling noises with my new Asus Xonar U7 card. I thought it might be an issue with the sound card and RPI and not specifically the `sounddevice` package, but playing wav files with `aplay` is without crackling so I don't know. Is there any way to fix this?

![http://i68.tinypic.com/14bizrk.jpg](http://i68.tinypic.com/14bizrk.jpg)
http://i68.tinypic.com/14bizrk.jpg

**Comment by mgeier** [comment]
You should check for buffer under-/overflows by running [sd.get_status()](python-sounddevice.readthedocs.io/#sounddevice.get_status) right after `sd.playrec()`.

If there are under-/overflows, you should try a larger block size with `blocksize=1024` or `blocksize=2048`.

If not, I don't really know ...
Your waveform indeed looks quite nasty.

**Comment by Plecto123** [comment]
How do I get the information out of  sd.get_status()? My python skills aren't that great :(

**Comment by mgeier** [comment]
Have a look at the [play_file.py](../blob/master/examples/play_file.py) example.

You can just print the returned `status` variable.

**Comment by Plecto123** [comment]
Printing the status variable gets me nothing, seems like it's empty. It says that the status variable is of type "<class 'sounddevice.CallbackFlags'>" which I'm not sure of what is, can it simply be printed?

**Comment by mgeier** [comment]
Yes, it can simply be printed.
If there are no errors, it will just print an empty string.
If you want to avoid printing empty strings, you can use it like in the aforementioned example.

Here's the docs: http://python-sounddevice.readthedocs.io/#sounddevice.CallbackFlags
You can also look at the source code, the relevant part is the `__str__()` method, which automatically gets called by `print()`.

If you don't get any over-/underflow errors, I don't really know what's going wrong.

Can you please still try it with different block sizes?

Do you also hear the strange noise while `playrec()` is running or is it only in the recording?

Does the same strange noise appear if you only use `play()` or only use `rec()`?

**Comment by Plecto123** [comment]
Same thing happens with the sd.play(). Simply recording from a different frequency generator gives a fine result so it definitely has to do with playback.

Block size of 1024 or 2048 made no difference. Neither does changing sample rate, all sample rates give the same crackling although higher sample rates reduces the time between cracks. One exception being using a Fs of 44100 which results in pure static. 

Since everything was fine with my previous USB sound card, could this be a driver issue?

**Comment by Plecto123** [comment]
Alright, I did something here. I used scipy.io.wavfile.read to get a song stored as wav and played it with sd.play() and it sound perfect. How does sd.play() interpret the array I create with scipy.io.wavfile.read() and the array I create with np.sin() differently?

**Comment by Plecto123** [comment]
It seems to be with the data types. The wave file is dtype=int16 while the sine wave I'm playing is a np.float64. My thinking was to simply create an int instead of a float by:

x=np.linspace(0.0, t, Fs*t)
y=32000*np.sin(1000*2.0*np.pi*x)
y=y.astype(np.int16)

But that gave me this result when using sd.play() or sd.playrec():

http://i64.tinypic.com/2ensx8y.jpg

Why this happens is beyond me. Increasing the block size will increase the on/off time that can been seen in the image. I'm having a hard time understanding how sounddevice can differentiate between two int16 arrays as the wav file plays just fine.

**Comment by mgeier** [comment]
I have no idea. This is really strange.

When I try your code, it works fine. I hear a single uninterrupted tone for 10 seconds.

Can you please try to save your generated signal (`y`) to a WAV file and then read it back in and play it?

I guess the generated signal looks fine when you plot it, right?

Did you try using your sound card with other software that uses PortAudio (e.g. Audacity)?

BTW, you can simply drag images into the comments here (while editing), then they will be directly visible without having to click on a link.

**Comment by Plecto123** [comment]
I generated it as a wav file, transferred it to my computer and it plays just fine, plotting the waveform shows that the array itself is without any issues. This has to do with sd.play() which for some reason is struggeling to handle the data even after it has been converted to a wav file and back into a int16 array :(

**Comment by mgeier** [comment]
The `sounddevice` module *theoretically* supports `float64`, `float32`, `int32`, `int16`, `int8` and `uint8`. And it shouldn't matter if you create the signal with NumPy or if you load it from a file.

You could try using the newest release of PortAudio (19.6.0). I guess there is no Raspbian package yet, so you'll have to compile it manually.

**Comment by Plecto123** [comment]
The issue was with the dimension of the array. Giving the sd.play() a two dimensional array for both left and right channel made it work :) Don't ask me why :(

**Comment by mgeier** [comment]
Great that you found a way that works!

It would still be interesting to find out if I can do something to avoid such errors in the future.

What was the dimension of the array when it worked and when it didn't work?
What were their shapes?

**Comment by Plecto123** [comment]
print y.dtype, y.shape, y.ndim, y.size, type(y)
>>int16 (48000, 2) 2 96000 <type 'numpy.ndarray'>

While the one that gave the result in the image above:
>>int16 (48000,) 1 48000 <type 'numpy.ndarray'>

Using int32 does not seem to work though, it just outputs nothing and records loud static regardless.

![capture](https://cloud.githubusercontent.com/assets/24659483/21632877/b711cf58-d24a-11e6-91b1-9eb2a1f4a358.JPG)

I also have a different problem that's not directly related to the topic of this thread though. I have a function that calculated the THD+N of a signal. Sending the y-array directly to this function returns a THD+N of something like 0.0003%, but sending the signal after it has been played and recorded gives a THD+N of 0.14% or there abouts. Calculating the THD+N of sine waves generated by my phone returns about 0.02% which is reasonable from a phone I guess. This USB sound card is supposed to ble able to output 0.0006 % THD+N at 1khz, so why does it output 0.14%? :\ 

I really appreciete the replies by the way :)

**Comment by mgeier** [comment]
Just to make sure that I understand this correctly:
This only happens with one specific USB sound card, right?
If you use a different sound card, it doesn't happen?

This very much looks like a problem of PortAudio and the driver of the USB sound card.

Did you try Audacity?
Or any other app from http://portaudio.com/apps.html?

**Comment by mgeier** [comment]
@Plecto123 Any news on this?
