### ISSUE TITLE
sd.query_devices not seeing all devices?

### ISSUE THREAD

**Issue by MarkAPitt** [spatialaudio/python-sounddevice#71]
Hello,
Could you possibly provide insight into the following problem.

`sd.query_devices()` generates the output below. There is an ASIO driver available which is not being picked up. The second set of listings is generated by the pyo package, which sees and uses the ASIO driver; this is how I know it is available and working fine. The sound card is an SB Audigy 5/Rx with the latest driver. We are running Python 2.7.11 on Windows 7 (32-bit). The sounddevice module works fine in all other respects!

```
   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone (Sound Blaster Audig, MME (2 in, 0 out)
   2 Stereo Mix (Realtek High Defini, MME (2 in, 0 out)
   3 "What U Hear" (Sound Blaster Au, MME (2 in, 0 out)
   4 Line-In (Sound Blaster Audigy 5, MME (2 in, 0 out)
   5 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  6 Speakers (Sound Blaster Audigy , MME (0 in, 8 out)
   7 SPDIF Out (Sound Blaster Audigy, MME (0 in, 2 out)
   8 Speakers / Headphones (Realtek , MME (0 in, 2 out)
   9 SPDIF Out (Sound Blaster Audigy 5/Rx), Windows WASAPI (0 in, 2 out)
  10 Speakers (Sound Blaster Audigy 5/Rx), Windows WASAPI (0 in, 2 out)
  11 Speakers / Headphones (Realtek High Definition Audio), Windows WASAPI (0 in, 2 out)
  12 Stereo Mix (Realtek High Definition Audio), Windows WASAPI (2 in, 0 out)
  13 "What U Hear" (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  14 Microphone (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  15 Line-In (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  16 S, Windows WDM-KS (0 in, 2 out)
  17 S, Windows WDM-KS (2 in, 8 out
```

Pyo AUDIO devices:

```
0: IN, name: Microsoft Sound Mapper - Input, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
1: IN, name: Microphone (Sound Blaster Audig, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
2: IN, name: Stereo Mix (Realtek High Defini, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
3: IN, name: "What U Hear" (Sound Blaster Au, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
4: IN, name: Line-In (Sound Blaster Audigy 5, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
5: OUT, name: Microsoft Sound Mapper - Output, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
6: OUT, name: Speakers (Sound Blaster Audigy , host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
7: OUT, name: SPDIF Out (Sound Blaster Audigy, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
8: OUT, name: Speakers / Headphones (Realtek , host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
9: IN, name: Primary Sound Capture Driver, host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
10: IN, name: Microphone (Sound Blaster Audigy 5/Rx), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
11: IN, name: Stereo Mix (Realtek High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
12: IN, name: "What U Hear" (Sound Blaster Audigy 5/Rx), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
13: IN, name: Line-In (Sound Blaster Audigy 5/Rx), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
14: OUT, name: Primary Sound Driver, host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
15: OUT, name: Speakers (Sound Blaster Audigy 5/Rx), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
16: OUT, name: SPDIF Out (Sound Blaster Audigy 5/Rx), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
17: OUT, name: Speakers / Headphones (Realtek High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
18: IN, name: Creative ASIO, host api index: 2, default sr: 48000 Hz, latency: 0.050000 s
18: OUT, name: Creative ASIO, host api index: 2, default sr: 48000 Hz, latency: 0.050000 s
19: IN, name: Realtek ASIO, host api index: 2, default sr: 44100 Hz, latency: 0.008707 s
19: OUT, name: Realtek ASIO, host api index: 2, default sr: 44100 Hz, latency: 0.008707 s
20: IN, name: SBAudigy5/Rx ASIO 24/96[D000], host api index: 2, default sr: 96000 Hz, latency: 0.050000 s
20: OUT, name: SBAudigy5/Rx ASIO 24/96[D000], host api index: 2, default sr: 96000 Hz, latency: 0.050000 s
21: IN, name: SBAudigy5/Rx ASIO[D000], host api index: 2, default sr: 48000 Hz, latency: 0.050000 s
21: OUT, name: SBAudigy5/Rx ASIO[D000], host api index: 2, default sr: 48000 Hz, latency: 0.050000 s
22: OUT, name: SPDIF Out (Sound Blaster Audigy 5/Rx), host api index: 3, default sr: 44100 Hz, latency: 0.003000 s
23: OUT, name: Speakers (Sound Blaster Audigy 5/Rx), host api index: 3, default sr: 44100 Hz, latency: 0.003000 s
24: OUT, name: Speakers / Headphones (Realtek High Definition Audio), host api index: 3, default sr: 48000 Hz, latency: 0.003000 s
25: IN, name: Stereo Mix (Realtek High Definition Audio), host api index: 3, default sr: 48000 Hz, latency: 0.003000 s
26: IN, name: "What U Hear" (Sound Blaster Audigy 5/Rx), host api index: 3, default sr: 44100 Hz, latency: 0.003000 s
27: IN, name: Microphone (Sound Blaster Audigy 5/Rx), host api index: 3, default sr: 44100 Hz, latency: 0.003000 s
28: IN, name: Line-In (Sound Blaster Audigy 5/Rx), host api index: 3, default sr: 44100 Hz, latency: 0.003000 s
29: OUT, name: Speakers (Realtek HD Audio output), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
30: IN, name: Jack Mic (Realtek HD Audio Front Mic input), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
31: IN, name: Stereo Mix (Realtek HD Audio Stereo input), host api index: 4, default sr: 48000 Hz, latency: 0.010000 s
32: OUT, name: SPDIF Out (SB Audigy 5/Rx SpdifOut [D000]), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
33: IN, name: Wave (SB Audigy 5/Rx [D000]), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
34: IN, name: Microphone (SB Audigy 5/Rx [D000]), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
35: IN, name: Line-In (SB Audigy 5/Rx [D000]), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
36: OUT, name: Speakers (SB Audigy 5/Rx [D000]), host api index: 4, default sr: 44100 Hz, latency: 0.010000 s
```

**Comment by mgeier** [comment]
I don't know, but let's find out!

You should check which PortAudio version you are using. You can do that with `sd.get_portaudio_version()`. I don't know how it's done with `pyo`.

Which version of `sounddevice` are you using?
In the last version (0.3.6) I changed the DLL to a newer PortAudio version, are you using that?
Either way, you should check the other available DLL.

If that doesn't shed light on the problem, you can try to install Christoph Gohlke's wheel package for `sounddevice`: http://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice

You can also try any other PortAudio DLL you can find ...

**Comment by MarkAPitt** [comment]
ok.
We are using version 0.3.6 of sounddevice, and portaudio version 1899 V19-devel (built Oct 8, 2013)

**Comment by mgeier** [comment]
This is very strange, it should use a newer PortAudio version.

How did you install the `sounddevice` module?

What is the output of the following code?

```python
from ctypes.util import find_library
find_library('portaudio')
```

Did you try the Gohlke wheels?

**Comment by MarkAPitt** [comment]
Thank you for the suggestions. I had wondered. There was indeed an old version of portaudio earlier in the search path. All works fine now.

In case others encounter a similar issue, note that [find_library()](https://docs.python.org/3/library/ctypes.html) does work on Windows. _None_ is always returned.

**Comment by mgeier** [comment]
Great. I'm glad that it works now.
Just out of curiosity, can you please post your new list of devices?

Thanks for pointing out that `find_library()` doesn't work. I thought it would work if a file named `portaudio.dll` is in Python's path.
Do you know another way to find out if the DLL in `_sounddevice_data/` is used or another one from somewhere else?

**Comment by MarkAPitt** [comment]
The new list is below.
I wish I knew. Such a routine would be handy. Off hand, one thing that could be done is to alert the user to the presence of multiple copies of portaudio on the device by searching through the entire dir structure.

   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone (Sound Blaster Audig, MME (2 in, 0 out)
   2 Stereo Mix (Realtek High Defini, MME (2 in, 0 out)
   3 "What U Hear" (Sound Blaster Au, MME (2 in, 0 out)
   4 Line-In (Sound Blaster Audigy 5, MME (2 in, 0 out)
   5 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  6 Speakers (Sound Blaster Audigy , MME (0 in, 2 out)
   7 SPDIF Out (Sound Blaster Audigy, MME (0 in, 2 out)
   8 Speakers / Headphones (Realtek , MME (0 in, 2 out)
   9 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
  10 Microphone (Sound Blaster Audigy 5/Rx), Windows DirectSound (2 in, 0 out)
  11 Stereo Mix (Realtek High Definition Audio), Windows DirectSound (2 in, 0 out)
  12 "What U Hear" (Sound Blaster Audigy 5/Rx), Windows DirectSound (2 in, 0 out)
  13 Line-In (Sound Blaster Audigy 5/Rx), Windows DirectSound (2 in, 0 out)
  14 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
  15 Speakers (Sound Blaster Audigy 5/Rx), Windows DirectSound (0 in, 2 out)
  16 SPDIF Out (Sound Blaster Audigy 5/Rx), Windows DirectSound (0 in, 2 out)
  17 Speakers / Headphones (Realtek High Definition Audio), Windows DirectSound (0 in, 2 out)
  18 Creative ASIO, ASIO (14 in, 20 out)
  19 Realtek ASIO, ASIO (2 in, 2 out)
  20 SBAudigy5/Rx ASIO 24/96[D000], ASIO (2 in, 8 out)
  21 SBAudigy5/Rx ASIO[D000], ASIO (14 in, 20 out)
  22 SPDIF Out (Sound Blaster Audigy 5/Rx), Windows WASAPI (0 in, 2 out)
  23 Speakers (Sound Blaster Audigy 5/Rx), Windows WASAPI (0 in, 2 out)
  24 Speakers / Headphones (Realtek High Definition Audio), Windows WASAPI (0 in, 2 out)
  25 Stereo Mix (Realtek High Definition Audio), Windows WASAPI (2 in, 0 out)
  26 "What U Hear" (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  27 Microphone (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  28 Line-In (Sound Blaster Audigy 5/Rx), Windows WASAPI (2 in, 0 out)
  29 Speakers (Realtek HD Audio output), Windows WDM-KS (0 in, 2 out)
  30 Jack Mic (Realtek HD Audio Front Mic input), Windows WDM-KS (2 in, 0 out)
  31 Stereo Mix (Realtek HD Audio Stereo input), Windows WDM-KS (2 in, 0 out)
  32 SPDIF Out (SB Audigy 5/Rx SpdifOut [D000]), Windows WDM-KS (0 in, 2 out)
  33 Wave (SB Audigy 5/Rx [D000]), Windows WDM-KS (2 in, 0 out)
  34 Microphone (SB Audigy 5/Rx [D000]), Windows WDM-KS (2 in, 0 out)
  35 Line-In (SB Audigy 5/Rx [D000]), Windows WDM-KS (2 in, 0 out)
  36 Speakers (SB Audigy 5/Rx [D000]), Windows WDM-KS (0 in, 8 out)

**Comment by mgeier** [comment]
Thanks, looks good!

If you find something out about getting information on the used DLL, please let me know.

In the meantime, we can close this issue, right?
