### ISSUE TITLE
Stream.close() function seems to hang when called from finished_callback

### ISSUE THREAD

**Issue by AodhAnd** [spatialaudio/python-sounddevice#78]
Hi,

FYI, I'm using sounddevice in its last version (v0.3.7), with PortAudio relying on ALSA (Fedora 25).

I'm building the basis of a sound player/recorder/analyzer for an experimental setup (something related to bubbles, but that's completely out of subject here... ^^).

So, I have some calls to the `stop()` method of a RawOutputStream object in my code and I'm using the `finished_callback` to make some proper clean up (closing the file, resetting everything sound-related) when I actually want the stream to be stopped (i.e. not paused). I have no trouble whatsoever, as long as I only ask for pause, but when my `stream_cleanup()` functions actually gets called, I can detect (with some trivial `print()` tests) that the `close()` function has a hanging behavior. 
However, I'm still able to resume the stream where it stopped after calling this cleanup function (which is clearly *not* the intended behavior !).

Here are two parts of my code that I think should clarify what I just wrote above:
```python
# How the finished_callback is defined
def finished_callback():
    if not self._pause_flag.is_set():
        # If the stream is not stopped for a simple pause, clean up
        self.stream_cleanup()
# [...]
# How my cleanup function is defined
def stream_cleanup(self):
    try:
        # Resources have to be cleaned properly
        print("Before")
        self._stream.close()
        print("After")
        self._sndfile.close()
        # For security reasons
        self._stream = None
        self._sndfile = None
        # Everything went fine
        print("Stopped audio stream")
    except (AttributeError, OSError):
        print("Can't stop unexisting audio stream!")
```
-> "Before" gets printed correctly, "After" never does, unless `self._stream.close()` is commented out, but that doesn't sound very clean.

I've seen your recent pull request #75 in which you discussed something similar, but you were pointing that hanging problem only when the `stop()` method hadn't been called before. Which is definitely not the case here, since the `finished_callback` is actually called when I ask the stream to stop, with the `stop()` function...

Do you have any idea how this could be solved in a cleaner way ?

**Comment by tgarc** [comment]
| something related to bubbles,

Like literal physical bubbles? Sounds interesting :o

Ah, so, you cannot operate on the stream in the finished_callback, or at least not stop/abort/close it. This is a portaudio behavior. In fact, from what I've seen calling stop()/abort() will block until your finished_callback has returned so obviously calling close() inside the callback will cause the thread to hang.

I would suggest using the `with` statement, i.e.,

```
with RawStream() as stream:
    # do stuff
```

That way it's guaranteed that close() will be called on the stream.

**Comment by AodhAnd** [comment]
Thanks for the quick answer!

Yep, physical bubbles, like the ones we all played with when we were younger ! :smile: 

Ah ! That's interesting, although not really satisfying my needs... :/
I already thought about using the context manager functionality, but due to my design (maybe a bad one), I'm not able to do this without losing the possibility of interacting with my GUI, to manually pause or stop the media, for instance...
That's actually why I thought about this clean-up function getting called at the end of the stream and I even moved from PyAudio to sounddevice to be able to use this callback functionality that PortAudio implements (but PyAudio doesn't, yet).

To be clear, what I currently have is: a play method (linked to a PLAY button) which creates a stream appropriately (and if it doesn't already exists) and then starts without waiting for it to finish. It then exits, leaving the stream in background which can be interrupted by clicking on the PAUSE (stream can be resumed) or STOP (stream is closed) buttons. Thus, if I use the `with` statement inside the play method, I'm afraid I will only be able to launch the pause and stop methods when the stream has actually finished playing.

Two solutions I've been (and am) thinking about:
- raising a signal inside the `finished_callback`. The signal would then be watched regularly by a sort of recurring timer to call the `stream_cleanup` function at the right time (maybe not thread-safe depending on the implementation...)
- doing everything directly stream-related in a secondary thread and sending signals to it when an interrupting action has to be performed. That way, I would be sure that the stream is handled thread-safely and that it doesn't interfere with the GUI in the main thread.
It's just that I can't see these come with the mess of handling threads (which I'm not quite comfortable using in Python, yet), and I wanted to keep the app the simplest possible. I guess, I will go for the 2nd option, that way I should have less trouble integrating the video part later, using a similar pattern.

Wow, a long message from my side, again. ^^" Anyway, thank you again, it helped me think a bit further :wink:

**Comment by mgeier** [comment]
It is indeed off-topic, but I would still be interested in seeing some pictures of the bubbles, or even a video!

The documentation is not very specific about the problem you are describing, but I assume this statement about the `callback` argument is also true for the `finished_callback` argument (see the [sounddevice.Stream](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.Stream) docs):

> With the exception of `cpu_load` it is not permissible to call PortAudio API functions from within the stream callback.

The two solutions you have mentioned should work, but if your situation allows it, there might be another, better choice:

What about creating the stream before PLAY (probably at program startup) and keeping it running after STOP?

You could implement a callback function that simply writes zeros to the output. And whenever PLAY is pressed, it starts writing the appropriate audio data until it's finished and afterwards again zeros.

In this scenario, you need to do the cleanup only once, at the very end of your program.

I've implemented such a callback function in C in https://github.com/mgeier/python-rtmixer/, but a similar (but probably simpler) thing could be done in Python as well.

**Comment by tgarc** [comment]
OK so let me try to understand what you want to accomplish wrt the audio part of your application:

> To be clear, what I currently have is: a play method (linked to a PLAY button) which creates a stream appropriately (and if it doesn't already exists) and then starts without waiting for it to finish. It then exits, leaving the stream in background which can be interrupted by clicking on the PAUSE (stream can be resumed) or STOP (stream is closed) buttons.

So it sounds like you just want to be able to start and stop a single stream. So why do you want to `close` the stream every time the user hits stop? Why not just call `stop`? It is perfectly possible to start and stop an open stream as much as you want. Then you only need to `close` your stream once when the application exits.

**Comment by AodhAnd** [comment]
Thank you guys for your answers. I'm building the app progressively, but in the medium/long term, I want to be able to read different files throughout an experiment session, so I'm afraid your solutions won't apply in that case.

@mgeier Yeah, I had seen that line in [PortAudio's doc](http://www.portaudio.com/docs/v19-doxydocs/portaudio_8h.html#a8a60fb2a5ec9cbade3f54a9c978e2710) as a note, but it never occurred to me that it would apply also for the `finished_callback`... :/ 
Even more so, since the documentation of `PaStreamFinishedCallback` [doesn't have that note](http://www.portaudio.com/docs/v19-doxydocs/portaudio_8h.html#ab2530ee0cb756c67726f9074d3482ef2).

So I'm not sure I'm gonna use your suggestion, but I think I'll have an eye on your C cleanup callback, it might still be interesting for my personal knowledge.

As for the bubbles themselves, I won't be able to send you that kind of picture or video for now, but when I've reached that part of the project, I'll try to remember and show you some demo of the experiment ;)

**Comment by mgeier** [comment]
It shouldn't be a problem to handle multiple files, either at different times or at the same time. You should still use a single stream with a single callback. The callback just has to be written in a way that it can receive the data, add multiple signals if they appear at the same time, and play zeros whenever no signal is available.

> your C cleanup callback

It's not a cleanup callback, it's just the "normal" audio callback.

**Comment by mgeier** [comment]
@AodhAnd Any news on the bubbles?
