### ISSUE TITLE
where do the portaudio dlls get installed to ?

### ISSUE THREAD

**Issue by stuaxo** [spatialaudio/python-sounddevice#8]
Just wondering where these get installed to, and if there is an API to find the location ?

**Comment by mgeier** [comment]
Next to the main module `sounddevice.py` there should be a sub-directory called `_sounddevice_data` holding the DLL for your system.

Once you've loaded the `sounddevice` module, you can get the location of `sounddevice.py` from the `__file__` attribute:

```python
import sounddevice as sd
print(sd.__file__)
```

If this doesn't work (e.g. if there is an error during import), you can try to load the dummy package `_sounddevice_data` (which only exists on Windows and OSX) and get its path with:

```python
import _sounddevice_data
print(_sounddevice_data.__path__)
```

If you want to try a different DLL, it should be enough to call it `portaudio.dll` (without `lib`!) and put it somewhere on the Python path.

BTW, if you want to know where the pre-packaged DLLs came from, have a look here: https://github.com/spatialaudio/portaudio-binaries

**Comment by stuaxo** [comment]
Cheers :)
