### ISSUE TITLE
Conversion digital-analog

### ISSUE THREAD

**Issue by azi92rach** [spatialaudio/python-sounddevice#92]
Hi, could you tell me how the output is implemented? 
I mean, how the the voltage(volts) of the sound card output is controlled? Does exist any min-max of these values?

**Comment by mgeier** [comment]
The exact voltage depends on your sound card. You may find some information in its user manual.
See also https://en.wikipedia.org/wiki/Line_level.

If you want to know the exact voltage in your case, you should measure it.
From the point of view of the `sounddevice` module, a "full scale" digital signal has (unitless) floating-point values from -1.0 to +1.0. The module has no knowledge about the details of the sound card you are using and it has no idea what voltage will appear at the output.

**Comment by mgeier** [comment]
PS: The output voltage of course also depends on the mixer settings of your operating system.

**Comment by azi92rach** [comment]
Ok, thank you! I am using the Asus xonar XD (https://www.asus.com/Sound-Cards/Xonar_DX/) to play sounds up to 40kHz. I am using you library to play this vector: 

FsOut = 192000
t = 1
np.sin(2*np.pi*F*np.linspace(0,t,FsOut))

changing F from 1000 to 40000. I found that there is no sound played more than 22-24kHz. 
I saw that the sound card (in the web page) reaches 192kHz as sample rate. 
I thoung that I shold play up to 30kHz as minimum. Could you explain me where I am wrong? Maybe your library is filtering the high frequency?

**Comment by mgeier** [comment]
TBH, I have no experience with sample rates bigger than 48000 Hz. But I would definitely expect that you should be able to play 30 kHz easily if your device uses a sampling rate of 192 kHz.

The `sounddevice` module definitely doesn't do any filtering; the PortAudio library might, but I really don't think so. The audio driver might do some filtering, but I don't think so either.
I think any filtering (mainly the anti-aliasing filter) should happen on the hardware (but I'm really just guessing).

How do you even check this stuff?
If you try to play the sound with a "normal" loudspeaker, this loudspeaker will not be able to play those frequencies.
And of course you wouldn't be able to hear them anyway.
Are you using an external measurement device?
A simple way to check if all frequencies are passed through would be to connect a cable from one output of the sound device to one input and check if all the expected frequencies are there.

**Comment by azi92rach** [comment]
I used an oscilloscope and a microphone system device!
Anyway I found it. It was a Ubuntu settings on /etc/pulse/daemon.conf
Thanks anyway!!

**Comment by tgarc** [comment]
@azi92rach fwiw, I wouldn't use pulseaudio if you care at all about latency and xruns (which it sounds like you might)

**Comment by azi92rach** [comment]
@tgarc what do you suggest?

**Comment by tgarc** [comment]
Use ALSA directly without plugins. For example here's my audio device listing...

```
   0 HDA Intel PCH: ALC221 Analog (hw:0,0), ALSA (2 in, 2 out)
   1 HDA Intel PCH: ALC221 Alt Analog (hw:0,2), ALSA (2 in, 0 out)
   2 HDA NVidia: HDMI 0 (hw:1,3), ALSA (0 in, 8 out)
   3 HDA NVidia: HDMI 1 (hw:1,7), ALSA (0 in, 8 out)
   4 HDA NVidia: HDMI 2 (hw:1,8), ALSA (0 in, 8 out)
   5 HDA NVidia: HDMI 3 (hw:1,9), ALSA (0 in, 8 out)
   6 front, ALSA (0 in, 2 out)
   7 surround40, ALSA (0 in, 2 out)
   8 surround51, ALSA (0 in, 2 out)
   9 surround71, ALSA (0 in, 2 out)
  10 pulse, ALSA (32 in, 32 out)
  11 dmix, ALSA (0 in, 2 out)
* 12 default, ALSA (32 in, 32 out)
```

Device indices 0 and 1 are for my onboard audio device (you'll notice the hw:x,x in the name). ALSA can also be configured with plugins that will do things like mixing, combining multiple audio devices into one virtual device, resampling, etc etc. There's a short overview of alsa configuration files here:

    https://www.alsa-project.org/main/index.php/Asoundrc

Pulseaudio will do all kinds of funny things to your audio because it's meant to be used as a mixer for general purpose usage. Use your hardware device directly (without any plugins) for best performance.

**Comment by azi92rach** [comment]
@tgarc thanks for this info. I am not an sound expert but it is very important for me the latency. 
Could you help me to set the computer to have the better performance? 
I am using the Asus Xonar DX on Ubuntu with the sounddevice library. 
This is my list of devices that I have: 

   0 HDA Intel PCH: ALC887-VD Digital (hw:0,1), ALSA (0 in, 2 out)
   1 HDA Intel PCH: ALC887-VD Alt Analog (hw:0,2), ALSA (2 in, 0 out)
   2 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
   3 Xonar DX: Multichannel (hw:1,0), ALSA (2 in, 8 out)
   4 Xonar DX: Digital (hw:1,1), ALSA (2 in, 2 out)
   5 Xonar DX: Multichannel (hw:2,0), ALSA (2 in, 0 out)
   6 Xonar DX: Digital (hw:2,1), ALSA (2 in, 2 out)
   7 iec958, ALSA (0 in, 2 out)
   8 spdif, ALSA (0 in, 2 out)
   9 hdmi, ALSA (0 in, 8 out)
  10 pulse, ALSA (32 in, 32 out)
* 11 default, ALSA (32 in, 32 out)
  12 system, JACK Audio Connection Kit (2 in, 2 out)
  13 PulseAudio JACK Sink, JACK Audio Connection Kit (2 in, 0 out)
  14 PulseAudio JACK Source, JACK Audio Connection Kit (0 in, 2 out)

Looking this list I think that I am using ALSA right? If no, how I can set it?
Thanks

**Comment by tgarc** [comment]
@azi92rach 

I recommend reading up a bit on ALSA to get a better understanding of what is going on. But the short story is that ALSA supports plugins that provide functionality in software that supplements the functionality of the audio hardware. (The ubuntu `default` device is one such an example - it's configured for 32 channels of audio, regardless of how many channels the audio hardware supports).

Again, any of the device that include a `(hw:x,x)` in their name are the most direct connection to the hardware and will give you the best performance.

**Comment by azi92rach** [comment]
Thanks @tgarc! I was reading about it. So in this case using sounddevice I should only play in my case the sound as: 
sd.play(soundVec, device=3) 

Right? nothing else!

**Comment by mgeier** [comment]
@azi92rach You should also specify the sampling rate of your `soundVec`. If you don't, the default sampling rate of the device is used, which may not be the right one!

**Comment by azi92rach** [comment]
Yes, what I did! Thanks, now it is clear.

**Comment by tgarc** [comment]
@azi92rach 

Yes, sounds right. Glad to help !
