### ISSUE TITLE
Question: possible to record only select channels with RawInputStream?

### ISSUE THREAD

**Issue by drammock** [spatialaudio/python-sounddevice#95]
I am dealing with the following situation: a MacOS computer with an external A-to-D box (M-Audio FastTrack Ultra 8R) that talks to the computer via USB.  The FastTrack *only* exports 24-bit audio, so I must use `RawInputStream`.  Moreover, I need to support variable-duration recordings.  I've got it working (based on [this example](https://python-sounddevice.readthedocs.io/en/0.3.8/examples.html#recording-with-arbitrary-duration)). However, the audio I need to record happens to be on channel 5 of the external box, and I've been asked not to switch around which mics go into which channels, so to get everything to work I've had to read in 5 channels (currently the script also writes out 5 channels, but I'd prefer to read/write only 1 channel).  Is there a way to do a `RawInputStream` that only listens to specific channels?  Here's the relevant bit of my code (the [callback function](https://github.com/drammock/gend-intel/blob/master/run-experiment.py#L191-L204)).

**Comment by tgarc** [comment]
> The FastTrack only exports 24-bit audio, so I must use RawInputStream.

It's okay in any case to use `dtype='int32'` - you'll just end up with some extra zero bits. But looking at your code it seems you're manually doing this anyway! Just specify int32 and let the backend deal with the padding.

> Is there a way to do a RawInputStream that only listens to specific channels?

Actually, yes! For coreaudio there is a way using `CoreAudioSettings`. There is an example in the docs that uses AsioSettings which should be easily adaptable for your use case:

http://python-sounddevice.readthedocs.io/en/0.3.8/#sounddevice.AsioSettings

I've not used coreaudio myself but sounds like it should work.

**Comment by drammock** [comment]
Awesome, I'll try that and report back. Thanks @tgarc

**Comment by mgeier** [comment]
Just to stress what @tgarc said: PortAudio should be able to convert to all
formats, even if the sound card only supplies 24-bit PCM. If that doesn't
work, please provide the error message.

I'm not sure if storing PCM_32 files makes most sense, since this format is
quite uncommon. I would consider using FLOAT instead.

**Comment by drammock** [comment]
Thanks all.  I confirm that `dtype='int32'` works with incoming 24-bit audio, and that `CoreAudioSettings(channel_map=[4])` worked to select only input channel 5.
