### ISSUE TITLE
Query soundcard for supported sample rates

### ISSUE THREAD

**Issue by alfredwidell** [spatialaudio/python-sounddevice#96]
Hello,

I'm missing a function that seem to be available in PortAudio and that is the option to query the soundcard for supported sample rates. The function "Pa_IsFormatSupported" is available in the C implementation but I cannot find it in sounddevice. I think it would be a good feature to implement.
See: http://portaudio.com/docs/v19-doxydocs/querying_devices.html

Thanks

**Comment by mgeier** [comment]
I took the liberty of renaming it and splitting it into two functions:

http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.check_input_settings
http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.check_output_settings

I didn't expect that anybody would actually use this ... just out of curiosity: what is your use case?

**Comment by alfredwidell** [comment]
Ok thanks, I did not realize the function was there. I will try it. My use case is to list all available sample rates of an arbitrary soundcard so it can be listed for the user. The user will then be able to pick the sample rate of choice.

**Comment by alfredwidell** [comment]
I've tried it now. The function does not seem to return any information independent on what sample rate I choose.

I run it like this:
`test = sounddevice.check_input_settings(device=48, channels=2, dtype='float32', extra_settings=None, samplerate=44100)`

The variable `test` is returning `None` independently on what sampling rate I test with, valid or not valid for the soundcard. I was expecting to get some True/False return or similar? I get error messages for faulty `device`, `channels` and `dtype` but not for faulty `samplerate`.

**Comment by mgeier** [comment]
The documentation says:

>  If the settings are supported, the function does nothing; if not, an exception is raised.

IOW, the return value (if there is one) is always `None`.

What sampling rates did you try?
Probably they *are* supported (or at least PortAudio thinks so)?
Did you try zero? A negative number?

I can find numbers that raise an error, both on macOS and Linux:

    sounddevice.PortAudioError: Invalid sample rate [PaErrorCode -9997]

What OS/hostAPI are you using?

**Comment by alfredwidell** [comment]
I'm testing it on another computer now (also Windows 10 and ASIO) and it is throwing the error message for unsupported sample rates like you describe. I don't know what went wrong earlier, it seems to be working now!

Thanks for your support and thank you for a great Python implementation of PortAudio.

**Comment by mgeier** [comment]
Thanks for the kind words!

If the function works on one computer/soundcard and doesn't work on another, it is likely a bug in PortAudio (or in the audio driver itself).
You should report this to the PortAudio project, but it would be helpful if you had a small example program in C that shows this problem ...

**Comment by mgeier** [comment]
@alfredwidell Is there still an issue? If not, can I close this?

**Comment by jkpubsrc** [comment]
I got the same error trying similar things: I use the python sounddevice module. 22kHz seems not to be supported - which is very strange.

**Comment by alfredwidell** [comment]
Could it be that you ask for 22000 Hz when it should be 22050 Hz? Sound cards tend to support only sample rate multiples of 44100 and 48000 Hz. You should also check that your sound card support 22050 Hz, not all sound card's does.
