### ISSUE TITLE
Sounddevice records too much noise

### ISSUE THREAD

**Issue by pajpax** [spatialaudio/python-sounddevice#97]
Hello,
I'm trying to record audio with sounddevice library (latest version) on RaspberryPi 3 model B v1.2 with raspbian installed and updated.
I'm using usb sound card for microphone input.
Here is the simple script for recording: [sound.zip](https://github.com/spatialaudio/python-sounddevice/files/1220879/sound.zip)

My problem is that sounddevice records so much noise, that it hurts my ears when I listen to the recorded file. Sometimes after fresh RPi boot, the first recording works ok, but when I try to record second time, then it records the noise.
Other times (most of the time), it records the noise even after fresh boot. 

I don't think its because of the usb sound card, because the script I'm using works ok with that card on my desktop pc (arch linux) and with the same version of the sounddevice.

I've tired recording with arecord program, which uses alsa and it works ok every time and I've also tried recording with audacity, which uses portaudio library and it also works ok.
Do you have any idea why is this happening?

Thanks

**Comment by mgeier** [comment]
Are there any messages on the terminal?

**Comment by pajpax** [comment]
There is "input overflow" message every time. I did not investigate this, because it gives me the same message on my desktop pc and the recording is working fine there.

**Comment by mgeier** [comment]
Whenever there is an overflow message, your recording is potentially ruined. You shouldn't take those lightly.

Make them go away and your noise will go away.

**Comment by tgarc** [comment]
Could you paste a minimal version of your program that reproduces the
problem? I can't get to the zip on my phone.

Hard to say without a further description of the noise. It could simply be
that the way you've saved or are playing back the audio is ill formatted.

**Comment by pajpax** [comment]
Yes, it's possible that I'm using the library in the wrong way. mgeier suggested that I should get rid of the "input overflow" problem, but I didn't get to it yet - and I don't know what is causing this yet.

Here is the code from the .zip:
```python

import sys
import time
import queue

import sounddevice as sd
import soundfile as sf

RECORD_TIME = 10

q = queue.Queue()
rec_start = int(time.time())

dev_info = sd.query_devices(2, 'input')
# samplerate = int(dev_info['default_samplerate'])
samplerate = 48000

def data_callback(input_data, frames, time, status):
    if status:
        print(status, file=sys.stderr)
    q.put(input_data.copy())

with sf.SoundFile('test.wav', mode='x', samplerate=samplerate, channels=2) as file:
    with sd.InputStream(samplerate=samplerate, device=2, channels=2, callback=data_callback):
        rec_time = int(time.time()) - rec_start
        
        while rec_time <= RECORD_TIME:
            file.write(q.get())
            rec_time = int(time.time()) - rec_start

```

**Comment by tgarc** [comment]
well one thing that could be the cause is that I believe the default 'subtype' for wav is pcm_16 whereas the default sounddevice encoding is float32. try specifying subtype as 'float' for the audio file

**Comment by mgeier** [comment]
My guess is that PortAudio simply doesn't choose good default values for this particular hardware/driver.

@pajpax You should experiment with different values for `latency` and `blocksize`. I think it is very likely that if you use something like `blocksize=2048`, your problem goes away.

**Comment by pajpax** [comment]
**@tgarc** Setting the subtype as 'float' didn't help.

**@mgeier** Setting the blocksize=2048 also didn't help, but when I set the blocksize to 18000 and above, it's working fine and I don't get any "input overflow" messages.

**Comment by mgeier** [comment]
@pajpax I'm glad that you found a value that works! It seems quite big to me, but I don't have any experience with RaspPi, so I don't know if that's normal or not.

Can you please try what `blocksize` you need for the `wire.py` example?

You can also try to keep the default `blocksize=0` and play around with different `latency` values.

Since you said that it works with Audacity, can you please check which buffer/latency settings you are using in Audacity?

There might also be some "virtual" devices available with different capabilities, can you please show the list of devices (`sd.query_devices()`) for your RaspPi?

**Comment by tgarc** [comment]
@pajpax 

Can you characterize the noise at all? When you say "it's so loud it hurts my ears" that makes me think you have an encoding problem, unless your audio is already very close to clipping levels, which is why I suggested that your ``subtype`` could be wrong. 

Could you show the ``dtype`` of the ``InputStream`` along with the ``subtype`` of the SoundFile in your above example? Also showing the details of the device that you selected as mgeier suggested would be helpful.

Also, just to check this isn't due to pilot error...can you verify that you're running the exact same code on your raspi as on your host computer? (There must be at least one difference - the device index is most likely different between the two versions.) There's no reason I know of that would point to the raspi being the culprit.

**Comment by pajpax** [comment]
**Output of sd.query_devices():**
0 bcm2835 ALSA: - (hw:0,0), ALSA (0 in, 2 out)
1 bcm2835 ALSA: IEC958/HDMI (hw:0,1), ALSA (0 in, 2 out)
2 USB Audio Device: - (hw:1,0), ALSA (2 in, 2 out)
3 USB Audio Device: #1 (hw:1,1), ALSA (0 in, 2 out)
4 sysdefault, ALSA (0 in, 128 out)
5 default, ALSA (0 in, 128 out)
6 dmix, ALSA (0 in, 2 out)

**Audacity settings (all the settings of recording I could find):**
Sample rate: 48000
Sample format: 32-bit float
Audio to buffer: 100ms
Latency correction: -130ms

**Sample recording with noise:** [noise.zip](https://github.com/spatialaudio/python-sounddevice/files/1232393/noise.zip)

**@mgeier**
I was testing wire.py. I was running it like this: ./wire.py -i 2 -s 48000. I did not set any blocksize and it was behaving very strange. At one run of the script, it was working fine and at another run of the script it was recording the noise again. This behaviour was random. 
After that, I was setting blocksize to higher values, the latency of audio playback was getting bigger and the recording of noise was still random, just like when I didn't set any blocksize. When I set blocksize to 18000, the playback wasn't working at all and the script was not responding to "Return" key.
After this, I tested my script again, but didn't set the blocksize so it was default value (0). And this time it was behaving exactly like wire.py. Working at one run, and recording noise at another run - I don't know what to think of this anymore.

**@tgarc**
I've uploaded 10s recording so you can hear the noise with your own ears.

Here is the information you requested. It's output from the same script as I've posted before, except I've set subtype='float' parameter to SoundFile() (and still recording the noise).
subtype of soundfile: FLOAT
dtype of InputStream: float32

And yes, I'm sure I'm using the same code on RaspPi and on my desktop pc. The only difference in the code is the device index just like you said.

**Comment by mgeier** [comment]
Wow, you got yourself some impressive noise there!
I totally didn't expect that, I thought you mean some clicking artifacts or dropouts or something ...

There's something going very wrong here.
One might get a similar noise when misinterpreting the data type of the audio samples, but in your code everything seems fine, and you say that happens only some of the times ...

I think you should descent to C realms for further testing, in order to check if it's a problem with PortAudio itself. You have a compiler on your RaspPi, right?

You can try a file like this, named `wire.c`:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <portaudio.h>

PaDeviceIndex device = 2;
PaTime latency = 0.1;
unsigned long blocksize = 0;
double samplerate = 48000.0;
PaSampleFormat format = paFloat32;
int channels = 1;

int callback(const void *input, void *output, unsigned long frame_count
  , const PaStreamCallbackTimeInfo* t, PaStreamCallbackFlags f, void* u)
{
  const float* in = input;
  float* out = output;
  for (int i = 0; i < frame_count; i++) { out[i] = in[i]; }
  if (f) { printf("xrun\n"); }
  return paContinue;
}

int main()
{
  PaError err = Pa_Initialize();
  if (err != paNoError) {
    printf("PortAudio error (init): %s\n", Pa_GetErrorText(err)); return 1;
  }
  PaStreamParameters out = { device, channels, format, latency, NULL };
  PaStreamParameters in = { device, channels, format, latency, NULL };
  PaStream* s = NULL;
  err = Pa_OpenStream(&s, &in, &out, samplerate, blocksize, 0, callback, NULL);
  if (err != paNoError) {
    printf("PortAudio error (open): %s\n", Pa_GetErrorText(err)); return 1;
  }
  err = Pa_StartStream(s);
  if (err != paNoError) {
    printf("PortAudio error (start): %s\n", Pa_GetErrorText(err)); return 1;
  }
  sleep(5);
  return 0;
}
```

And a `Makefile`:

```make
LDLIBS = -lportaudio

wire:
```

Then you can run

    make
    ./wire

... and check if the same thing happens.
You can play around with the settings in the code (and don't forget to re-compile!).

**Comment by pajpax** [comment]
When I compile and run that code, it gives me this output:
```
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
```
I managed to find simillar problems like this and it could be that these are only warning messages about wrong alsa configuration files for devices. 
Any idea how to get rid of these messages? Recording is not working, btw.

**Comment by mgeier** [comment]
Yes, those messages can be ignored. And yes, I do know a way to silence them, because I did it for the `sounddevice` module: #12. But that's really not the point here.

> Recording is not working, btw.

This isn't supposed to record anything, it's supposed to pass the input through to the output, just like the `wire.py` example.

Do you hear anything?
Any noise?

At least there are no "xrun" messages. If you reduce the `blocksize`/`latency`, those should appear at some point.

**Comment by pajpax** [comment]
Im sorry, I was not clear enough. By "not recording" I simply ment that I dont hear any sound. I know its supposed to work exactly like wire.py.

**Comment by pajpax** [comment]
The reason why I didn't hear anything was because I had my headphones connected to RPi audio output jack, not the usb sound card output jack. Wire.py was using RPi audio output.
The C program using portaudio library is behaving exactly like wire.py. Working fine at one run and "recording" noise at another run.
So this is either portaudio problem or RPi problem.

**Comment by tgarc** [comment]
pretty unique problem you have there! the white noise is even further confounding.

So does setting the blocksize to 18000 fix your problem permanently?

And I'm assuming that you have no issues with other audio devices?

But you also say that this issue doesn't occur when using audacity? That's curious because audacity uses Portaudio as the backend...

**Comment by pajpax** [comment]
**@tgarc**
1. With blocksize set to 18000, I get the noise (and "input overflow" message) in one out of 5 runs of my script. When I go higher (20k or 24k), I get no "input overflow" messages and recording is fine - I've run it many times - but that doesn't mean it fixed the problem permanently.

2. I'm not using any other audio devices, only headphones and there is just a little cracking noise when playing sound on the RPi, but that is a known RPi issue - probably not connected with my recording noise problem.

3. No, this doesn't happen in audacity. I've made like 15 recordings in audacity and not a single one of them recorded that noise.

**Comment by pajpax** [comment]
Thank you for all your help. I'm closing this, since it's not a sounddevice issue.

**Comment by tgarc** [comment]
If you could, let us know what you find out!

**Comment by Joxephizer** [comment]
Just try to reduce the volume of recording audio 80% or less

**Comment by dcssi** [comment]
I was having the same issue,  noice while recording.  I tried everything looking for it, after a while i figured out that it was me looking for it that generated it.   I was running my code under the debugger, even do I was using multiple processes, the debugger stopping one may cause the other processes to wait too.  Running the code without debugger removed all noice from my audio
