### ISSUE TITLE
Latency 

### ISSUE THREAD

**Issue by azi92rach** [spatialaudio/python-sounddevice#98]
Hi, 

I am using sounddevice to trig a sound when an event occurs. 

Now I am testing the latency that the sound have, I mean I want to know how many time there is between the event and the sound triggered. 

I am using Ubuntu and I installed the lowlatency kernel. I have 3 sound card Asusu DX installed as you can see here: 

```
   0 Xonar DX: Multichannel (hw:0,0), ALSA (2 in, 8 out)
   1 Xonar DX: Digital (hw:0,1), ALSA (2 in, 2 out)
   2 HDA Intel PCH: ALC887-VD Analog (hw:1,0), ALSA (2 in, 2 out)
   3 HDA Intel PCH: ALC887-VD Digital (hw:1,1), ALSA (0 in, 2 out)
   4 HDA Intel PCH: ALC887-VD Alt Analog (hw:1,2), ALSA (2 in, 0 out)
   5 HDA Intel PCH: HDMI 0 (hw:1,3), ALSA (0 in, 8 out)
   6 Xonar DX: Multichannel (hw:2,0), ALSA (2 in, 8 out)
   7 Xonar DX: Digital (hw:2,1), ALSA (2 in, 2 out)
   8 Xonar DX: Multichannel (hw:3,0), ALSA (2 in, 8 out)
   9 Xonar DX: Digital (hw:3,1), ALSA (2 in, 2 out)
  10 sysdefault, ALSA (128 in, 128 out)
  11 front, ALSA (0 in, 8 out)
  12 surround40, ALSA (0 in, 4 out)
  13 surround41, ALSA (0 in, 6 out)
  14 surround50, ALSA (0 in, 6 out)
  15 surround51, ALSA (0 in, 6 out)
  16 surround71, ALSA (0 in, 8 out)
  17 iec958, ALSA (0 in, 2 out)
  18 spdif, ALSA (2 in, 2 out)
  19 pulse, ALSA (32 in, 32 out)
  20 dmix, ALSA (0 in, 2 out)
* 21 default, ALSA (32 in, 32 out)
```

I note that when I use the following command the latency is about 45ms: 
`sd.play(sound, blocking=False, device = 0)` 

And if I remove the device info as the following the latency was about 10ms
`sd.play(sound, blocking=False)` 

Could you help me? I need less latency possible, and I need to play different sounds using different cards. So I can't use the default output to play the sound, I need to specify which card.

**Comment by tgarc** [comment]
it's hard to tell what you're asking for help with...Your example just shows that one device has a different latency than another; thats not unexpected. Each hardware device has its own inherent latency and virtual devices will have latency on top of that depending on the configuration.

As a starting point for optimizing for latency did you know you can pass a  latency parameter to the play() function? It's mentioned in the docs [here](https://python-sounddevice.readthedocs.io/en/0.3.8/index.html?highlight=latency#sounddevice.Stream.latency). You can just try passing latency='low' and see how it effects your measured latency.

**Comment by mgeier** [comment]
It could also be interesting to see what the `'default_low_output_latency'` and `'default_high_output_latency'` values of the different devices are. You get them when you specify a `device` argument with `sd.query_devices()`.

If you really want to reduce latency, you should be aware that `sd.play()` starts a fresh PortAudio stream with each invocation, which also takes some amount of time (but I have no clue how much that is).
You can probably reduce the latency further, if you start an `sd.OutputStream` and then use the `write()` method on it to trigger the sound.
Or you can try to write your own callback function.

And just out of curiosity: how are you measuring the latency?

**Comment by azi92rach** [comment]
Maybe I didn't explain well. I said that I have 3 sound card, but for the moment I am using only one. 

@tgarc, as you suggested here (https://github.com/spatialaudio/python-sounddevice/issues/92) I used the function `sd.play(sound, blocking=False, device = 0)` to control directly the hardware. In this case the latency is about 45ms. Otherwise, when I used the function `sd.play(sound, blocking=False)` without specify the hardware (but the sound is coming from the same sound card) the latency is about 10ms. 
As you said, I fixed the latency to 'low' and now using the function `sd.play(sound, blocking=False, device = 0, latency='low')` the latency is about 12ms. It is better than before. 
I was just interesting why this appends.

@mgeier I saw the two o see what the `default_low_output_latency `and  `default_high_output_latency`, you can see here the results:

```

>>> sd.query_devices()
   0 HDA Intel PCH: ALC887-VD Analog (hw:0,0), ALSA (2 in, 2 out)
   1 HDA Intel PCH: ALC887-VD Digital (hw:0,1), ALSA (0 in, 2 out)
   2 HDA Intel PCH: ALC887-VD Alt Analog (hw:0,2), ALSA (2 in, 0 out)
   3 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
   4 Xonar DX: Multichannel (hw:1,0), ALSA (2 in, 8 out)
   5 Xonar DX: Digital (hw:1,1), ALSA (2 in, 2 out)
   6 Xonar DX: Multichannel (hw:2,0), ALSA (2 in, 8 out)
   7 Xonar DX: Digital (hw:2,1), ALSA (2 in, 2 out)
   8 Xonar DX: Multichannel (hw:3,0), ALSA (2 in, 8 out)
   9 Xonar DX: Digital (hw:3,1), ALSA (2 in, 2 out)
  10 sysdefault, ALSA (128 in, 128 out)
  11 front, ALSA (0 in, 2 out)
  12 surround40, ALSA (0 in, 2 out)
  13 surround51, ALSA (0 in, 2 out)
  14 surround71, ALSA (0 in, 2 out)
  15 iec958, ALSA (0 in, 2 out)
  16 spdif, ALSA (0 in, 2 out)
  17 hdmi, ALSA (0 in, 8 out)
  18 pulse, ALSA (32 in, 32 out)
  19 dmix, ALSA (0 in, 2 out)
* 20 default, ALSA (32 in, 32 out)
>>> sd.query_devices(20)
{'hostapi': 0, 'default_samplerate': 44100.0, 'name': 'default', 'default_high_output_latency': 0.034829931972789115, 'default_high_input_latency': 0.034829931972789115, 'default_low_input_latency': 0.008707482993197279, 'default_low_output_latency': 0.008707482993197279, 'max_input_channels': 32, 'max_output_channels': 32}
>>> sd.query_devices(4)
{'hostapi': 0, 'default_samplerate': 44100.0, 'name': 'Xonar DX: Multichannel (hw:1,0)', 'default_high_output_latency': 0.034829931972789115, 'default_high_input_latency': 0.034829931972789115, 'default_low_input_latency': 0.008707482993197279, 'default_low_output_latency': 0.008707482993197279, 'max_input_channels': 2, 'max_output_channels': 8}
>>> sd.query_devices(6)
{'hostapi': 0, 'default_samplerate': 44100.0, 'name': 'Xonar DX: Multichannel (hw:2,0)', 'default_high_output_latency': 0.034829931972789115, 'default_high_input_latency': 0.034829931972789115, 'default_low_input_latency': 0.008707482993197279, 'default_low_output_latency': 0.008707482993197279, 'max_input_channels': 2, 'max_output_channels': 8}


```
They are the same, right? It is strange for me. 
Moreover I saw the function `write()`. It is not possible to play it on background right? 

To compute the latency I am using a National Instrument card connected by RCA cable to sound card and an other cable to an Arduino card that trig the event. In the figure you can see the 2 signals.

![test](https://user-images.githubusercontent.com/11569373/29455181-79be7444-8410-11e7-9a73-a05ba576ba4e.jpg)

**Comment by malfatti** [comment]
I do the opposite, I trigger stuff using sound :) but I also need a low latency. Indeed, I have much better results with `OutputStream()`. I achieved ~2ms latency with the following setup:

- Linux RT kernel;
  Consider the [Xenomai](https://xenomai.org//troubleshooting-a-dual-kernel-configuration/#kconf) and the [ProAudio](http://proaudio.tuxfamily.org/wiki/index.php?title=Realtime_%28RT%29_Kernel#Adjust_important_settings) tutorials on kernel options

- Jack audio server (without pulseaudio);
- Using sd.OutputStream():
```python
import sounddevice as SD

SD.default.device = 'system'
SD.default.samplerate = 192000
SD.default.blocksize = 384
SD.default.channels = 2
Stim = SD.OutputStream(dtype='float32')

## Generate your sound arrays
# BG = blahblah
# Gap = arrayofzeros
# Pulse = loremipsum

Stim.start()
for Sound in [BG, Gap, Pulse, BG]:
    Stim.write(Sound)

Stim.stop()
```

**Comment by azi92rach** [comment]
Thanks @malfatti! 
I have some question:
1. Is this solution works to trigger 3 different sound using 3 different soundcard at the same time? 
2. Is this solution works in backgronud? 

Because my system needs to run 3 different tasks in the same time, and each one has to control one soundcard.

**Comment by malfatti** [comment]
Sure :)

There should be a simpler way, but to deal with 3 streams and simultaneous write I would use the `threading` package:

```python
import numpy as np
import sounddevice as SD

from threading import Thread

## Set your things
Rate = 192000       # in Hz
BlockSize = 384     # in samples
ChsPerDevice = 1    # in number
Duration = 3        # in seconds
DeviceIndex = [0, 1, 2]


## Apply settings
SD.default.samplerate = Rate
SD.default.blocksize = BlockSize
SD.default.channels = ChsPerDevice


## Create streams
Streams = [SD.OutputStream(dtype='float32', device=Index) for Index in DeviceIndex]


## Define thread class
class Play(Thread):
    def __init__(self, Stream, Sound):
       Thread.__init__(self)
       self.Stream = Stream
       self.Sound = Sound
    
    def run(self):
        self.Stream.write(self.Sound)


## Generate your sound arrays
BG = np.random.uniform(-0.3, 0.3, size=(ChsPerDevice, Rate*Duration))
Pulse = np.random.uniform(-1, 1, size=(ChsPerDevice, Rate*Duration))
Gap = np.zeros((ChsPerDevice, Rate*Duration))

Stim = [BG, Pulse, Gap] # Order according to what you want each card to output


## Create threads
Threads = [Play(Stream, Stim[S]) for S, Stream in enumerate(Streams)]


## Play
for S in Streams S.start()
for T in Threads: T.start()

# Do whatever other thing while stimuli are played
# and whenever you want to wait for them all to finish, just:
for T in Threads: T.join()
for S in Streams S.stop()
```

Unfortunately I cannot test, since I only have one sound card :)

**Comment by azi92rach** [comment]
Thanks @malfatti! I will try it. 
One question, in this case to use jack audio server I should run 3 jack audio server right? each one for each sound card.

**Comment by malfatti** [comment]
Precisely. I don't know, however, how this would impact on the performance (since all three would have RT priority). I never used 2 jack instances simultaneously.

**Comment by azi92rach** [comment]
Thank @malfatti! 
At the end I created a function based on OutputStrem and I had a 3-4ms of latency.
